/**
 * ASTRO SIVAM - brand asset pipeline guards.
 *
 * The logo is regenerated by scripts/build_logo_assets.py, which supports two
 * artwork variants (`ornate` and `modern`) and can write into a scratch folder
 * without touching the live files. These checks keep that pipeline honest:
 * a future edit must not silently drop a variant, break the preview path, or
 * leave the icon cache-bust behind.
 *
 * The geometric guard on the modern mark's sun/crescent separation lives in
 * scripts/modern_mark.py (verify_composition) and runs on every build.
 */

import assert from 'node:assert/strict';
import { existsSync, readFileSync, statSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { resolve } from 'node:path';

const root = process.cwd();
const read = (p: string) => readFileSync(resolve(root, p), 'utf8');
const has = (p: string) => existsSync(resolve(root, p));

const PASS: string[] = [];
const FAIL: string[] = [];
function check(desc: string, condition: boolean) {
  (condition ? PASS : FAIL).push(desc);
}

// --- the builder exists and understands both variants ---------------------- //
const builder = read('scripts/build_logo_assets.py');
for (const variant of ['ornate', 'modern']) {
  check(`Asset builder supports the "${variant}" variant`, builder.includes(`"${variant}":`));
}
check('Asset builder exposes --variant', builder.includes('"--variant"'));
check('Asset builder exposes --target (scratch folder)', builder.includes('"--target"'));
check('A scratch --target implies no live write', builder.includes('args.live if args.live is not None else args.target is None'));
const defaultVariant = builder.match(/ap\.add_argument\("--variant"[\s\S]*?default="([^"]+)"/i)?.[1];
check('Default live artwork variant matches the modern website mark', defaultVariant === 'modern');
check('PDF artwork defaults to the same variant as the website',
  builder.includes('pdf_variant = args.pdf_variant or args.variant')
  && builder.includes('pdf_emblem = emblem if (pdf_variant or variant) == variant'));
check('Live mode always re-embeds BOTH base64 logo modules together',
  builder.includes('ASTRO_LOGO_BASE64') && builder.includes('EMBEDDED_LOGO_BASE64'));

// --- the modern mark is drawn, not raster ---------------------------------- //
const modernMark = read('scripts/modern_mark.py');
const geometry = read('scripts/modern_mark_geometry.py');
check('Modern mark is generated as vector-style geometry (no AI raster source)',
  modernMark.includes('def render_mark') && modernMark.includes('ImageDraw'));
check('Modern mark draws exactly twelve rasi dots', modernMark.includes('for i in range(12)'));
check('Composition rules live in a stdlib-only module (testable without PIL)',
  geometry.includes('def verify_composition') && geometry.includes('def crescent_metrics')
  && !/\bPIL\b/.test(geometry));
check('Modern mark has a composition guard that fails loudly',
  geometry.includes('raise SystemExit')
  && geometry.includes('tip_clearance') && geometry.includes('< min_clearance'));
check('The composition guard runs on every modern build',
  builder.includes('mm.verify_composition()'));

// the guard genuinely rejects a bad geometry - executed, not just grepped
let guardFired = false;
try {
  execFileSync('python3', ['-c', `
import sys, dataclasses
sys.path.insert(0, 'scripts')
from modern_mark_geometry import Proportions, verify_composition
verify_composition(dataclasses.replace(Proportions(), sun_radius=0.20, sun_offset_x=-0.02))
`], { cwd: root, stdio: 'pipe' });
} catch {
  guardFired = true;
}
check('Composition guard actually rejects a collapsed layout (executed)', guardFired);

// and the shipped proportions pass their own guard
let shippedOk = true;
try {
  execFileSync('python3', ['-c', `
import sys
sys.path.insert(0, 'scripts')
from modern_mark_geometry import verify_composition
verify_composition()
`], { cwd: root, stdio: 'pipe' });
} catch {
  shippedOk = false;
}
check('Shipped modern-mark proportions pass the composition guard', shippedOk);

// --- brand artwork must carry the name + slogan only ---------------------- //
// Service lists belong in page copy, never baked into the logo. This is what
// keeps "Jathagam / Porutham / Baby Naming / Muhurtham" from creeping back into
// a generated social card or lockup.
const SERVICE_NAMES = /jathagam|porutham|baby\s*naming|muhurtham/i;
for (const generator of ['scripts/build_logo_assets.py', 'scripts/modern_mark.py']) {
  check(`No service name appears in ${generator}`, !SERVICE_NAMES.test(read(generator)));
}
check('The one-time strip of the service list is recorded in a migration script',
  has('scripts/strip_og_tagline.py'));
check('The OG card generator no longer lays out a tagline',
  !builder.includes('tag_font') && !builder.includes('tag_track'));
check('The stripped ornate master is the one the builder consumes',
  builder.includes('logo_og_card.jpg'));

// --- size-based legibility rule -------------------------------------------- //
// The twelve-dot ring turns to mush below ~44px, so small favicons must fall
// back to the reduced mark. The threshold lives in the stdlib-only geometry
// module so it can be exercised without an imaging library.
check('Geometry module owns the size rule',
  geometry.includes('DOTS_MIN_PX') && geometry.includes('def mark_for_size'));
check('The asset builder uses the shared rule, not its own copy',
  builder.includes('mm.DOTS_MIN_PX') && builder.includes('mark_for_size(size)')
  && !/^DOTS_MIN_PX\s*=\s*\d+/m.test(builder));
check('Builder documents why the rule exists',
  builder.includes('liability below DOTS_MIN_PX'));

let sizeRuleOk = false;
try {
  const out = execFileSync('python3', ['-c', `
import sys
sys.path.insert(0, 'scripts')
from modern_mark_geometry import DOTS_MIN_PX, mark_for_size
assert 16 <= DOTS_MIN_PX <= 64, DOTS_MIN_PX
assert mark_for_size(16) == "reduced"
assert mark_for_size(32) == "reduced"
assert mark_for_size(DOTS_MIN_PX) == "dotted"
assert mark_for_size(48) == "dotted"
assert mark_for_size(192) == "dotted"
print("ok")
`], { cwd: root, stdio: 'pipe' }).toString();
  sizeRuleOk = out.includes('ok');
} catch {
  sizeRuleOk = false;
}
check('Size rule picks the reduced mark below the threshold and the full mark above it (executed)',
  sizeRuleOk);

// --- the live logo contract must not regress -------------------------------- //
check('Browser emblem is served from public/',
  has('public/astrosivam_logo.png') && statSync(resolve(root, 'public/astrosivam_logo.png')).size > 1024);
const publishedEmblem = readFileSync(resolve(root, 'public/astrosivam_logo.png'));
check('Vite navbar emblem matches the published website emblem',
  has('src/assets/astrosivam_logo.png')
  && readFileSync(resolve(root, 'src/assets/astrosivam_logo.png')).equals(publishedEmblem));
check('Official full logo is present in public/',
  has('public/astrosivam_full_logo.png') && statSync(resolve(root, 'public/astrosivam_full_logo.png')).size > 1024);
check('Favicon 16x16 is present in public/',
  has('public/favicon-16x16.png') && statSync(resolve(root, 'public/favicon-16x16.png')).size > 0);
check('Favicon 32x32 is present in public/',
  has('public/favicon-32x32.png') && statSync(resolve(root, 'public/favicon-32x32.png')).size > 0);
check('Favicon 48x48 is present in public/',
  has('public/favicon-48x48.png') && statSync(resolve(root, 'public/favicon-48x48.png')).size > 0);
check('Favicon ICO is present in public/',
  has('public/favicon.ico') && statSync(resolve(root, 'public/favicon.ico')).size > 0);
check('Apple touch icon is present in public/',
  has('public/apple-touch-icon.png') && statSync(resolve(root, 'public/apple-touch-icon.png')).size > 0);
check('Android Chrome 192 icon is present in public/',
  has('public/android-chrome-192x192.png') && statSync(resolve(root, 'public/android-chrome-192x192.png')).size > 0);
check('Android Chrome 512 icon is present in public/',
  has('public/android-chrome-512x512.png') && statSync(resolve(root, 'public/android-chrome-512x512.png')).size > 0);
check('PHP API keeps its own bundled logo',
  has('api/assets/astrosivam_logo.png') && statSync(resolve(root, 'api/assets/astrosivam_logo.png')).size < 80 * 1024);
check('Social share card is a 1200x630 JPEG (served, not PNG)',
  has('public/astrosivam_og_image.jpg'));

// --- icon cache-busting ----------------------------------------------------- // A stale ?v= means browsers and social scrapers keep serving the old mark.
const indexHtml = read('index.html');
const seo = read('src/components/common/SEO.tsx');
const version = (indexHtml.match(/favicon-32x32\.png\?v=(\d+)/) || [])[1];
check('Favicons carry a cache-bust version', Boolean(version));
check('SEO default share image carries the same cache-bust version',
  Boolean(version) && seo.includes(`astrosivam_og_image.jpg?v=${version}`));
check('Social card is the OG image, not the raw emblem',
  !/og:image" content="[^"]*astrosivam_logo\.png/.test(indexHtml));

console.log('\n--- BRAND ASSET PIPELINE ---');
for (const p of PASS) console.log(`  [PASS] ${p}`);
for (const f of FAIL) console.log(`  [FAIL] ${f}`);
console.log(`\n  ${PASS.length} passed, ${FAIL.length} failed`);
if (FAIL.length) process.exit(1);
