<?php
/**
 * ASTRO SIVAM source-based astrologer - local knowledge-base mode.
 *
 * Every reply is assembled from ASTRO SIVAM's own sources only:
 *
 *   1. the customer's own report readings (AstroEngine's per-area summary,
 *      rebuilt from the saved order inputs - the same text as the PDF),
 *   2. the curated classical rules in knowledge/ai-astrologer/rules/
 *      life-areas.json, evaluated against the customer's chart,
 *   3. the remedies registry (knowledge/ai-astrologer/rules/remedies.json),
 *   4. the fixed refusal routes and guardrails.
 *
 * Nothing is generated by a language model, so nothing unreviewed can reach a
 * customer, and the chat works on any host with no paid service. The same
 * output guard (AstroAiProvider::checkReply) still runs on every reply.
 *
 * Returns the same shape as AstroAiProvider::answer() so the endpoint and the
 * browser do not need to know which mode produced the answer.
 */

require_once __DIR__ . '/ai_astrologer_provider.php';

class AstroAiOffline
{
    /** Life-area id => key prefix of AstroEngine's summary texts. */
    const SUMMARY_KEYS = [
        'health' => 'health',
        'wealth' => 'wealth',
        'education' => 'education',
        'career' => 'career',
        'marriage' => 'marriage',
        'property' => 'family',
        'travel-foreign' => 'foreignTravel',
        'current-guidance' => 'currentPeriodGuidance',
    ];

    /**
     * Extra everyday words per area, on top of customerPhrases in
     * life-areas.json, so plain questions ("will I get a job", "when is my
     * wedding") still find the right card without a model to interpret them.
     */
    const EXTRA_PHRASES = [
        'career' => ['job', 'jobs', 'work', 'office', 'promotion', 'boss', 'business', 'salary', 'profession', 'employment', 'career',
            'வேலை', 'உத்தியோகம்', 'தொழில்', 'பதவி', 'வியாபாரம்', 'नौकरी', 'काम', 'व्यापार', 'व्यवसाय', 'प्रमोशन', 'करियर', 'कैरियर', 'तरक्की'],
        'marriage' => ['marriage', 'married', 'marry', 'wedding', 'wife', 'husband', 'spouse', 'partner', 'love', 'relationship', 'divorce', 'child', 'children', 'baby',
            'திருமணம்', 'கல்யாணம்', 'மனைவி', 'கணவர்', 'காதல்', 'குழந்தை', 'विवाह', 'शादी', 'पत्नी', 'पति', 'प्रेम', 'संतान', 'बच्चे'],
        'wealth' => ['money', 'wealth', 'finance', 'income', 'debt', 'loan', 'savings', 'rich', 'financial',
            'பணம்', 'செல்வம்', 'வருமானம்', 'கடன்', 'சேமிப்பு', 'धन', 'पैसा', 'आय', 'कर्ज', 'बचत'],
        'education' => ['study', 'studies', 'exam', 'education', 'college', 'school', 'degree', 'university',
            'படிப்பு', 'கல்வி', 'தேர்வு', 'பரீட்சை', 'पढ़ाई', 'शिक्षा', 'परीक्षा'],
        'property' => ['house', 'home', 'land', 'property', 'flat', 'apartment', 'vehicle', 'car',
            'வீடு', 'நிலம்', 'சொத்து', 'வாகனம்', 'घर', 'जमीन', 'संपत्ति', 'मकान', 'वाहन'],
        'travel-foreign' => ['abroad', 'foreign', 'travel', 'visa', 'overseas', 'settle', 'migrate', 'australia', 'canada', 'usa', 'uk', 'new zealand',
            'வெளிநாடு', 'பயணம்', 'விசா', 'विदेश', 'यात्रा', 'वीज़ा', 'वीजा'],
        'health' => ['health', 'sick', 'illness', 'pain', 'tired', 'sleep', 'stress', 'anxiety',
            'உடல்நலம்', 'நோய்', 'தூக்கம்', 'மன அழுத்தம்', 'स्वास्थ्य', 'बीमार', 'नींद', 'तनाव'],
        'current-guidance' => ['dasha', 'dasa', 'bhukti', 'period', 'this year', 'next year', 'future', 'sade sati', 'ezharai', 'nakshatra', 'star', 'panchangam', 'horoscope', 'chart', 'my life',
            'தசை', 'திசை', 'புக்தி', 'ஏழரை', 'நட்சத்திரம்', 'ஜாதகம்', 'எதிர்காலம்', 'இந்த வருடம்', 'பஞ்சாங்கம்',
            'दशा', 'भुक्ति', 'साढ़े साती', 'नक्षत्र', 'कुंडली', 'भविष्य', 'इस साल'],
    ];

    /** Words that make a question about the running period itself. */
    const PERIOD_WORDS = ['dasha', 'dasa', 'bhukti', 'mahadasha', 'antardasha', 'sade sati', 'nakshatra', 'birth star', 'panchangam', 'panchang',
        'தசை', 'திசை', 'புக்தி', 'ஏழரை', 'நட்சத்திரம்', 'பஞ்சாங்கம்', 'दशा', 'भुक्ति', 'साढ़े साती', 'नक्षत्र', 'पंचांग'];

    const REMEDY_WORDS = ['remedy', 'remedies', 'pariharam', 'parikaram', 'parihara', 'mantra', 'temple', 'pooja', 'puja', 'prayer', 'fasting', 'charity',
        'பரிகாரம்', 'மந்திரம்', 'கோயில்', 'கோவில்', 'பூஜை', 'விரதம்', 'தானம்', 'उपाय', 'मंत्र', 'मंदिर', 'पूजा', 'व्रत', 'दान'];

    const TIMING_WORDS = ['when', 'which year', 'how long', 'what time', 'எப்போது', 'எப்பொழுது', 'எந்த வருடம்', 'எவ்வளவு காலம்', 'कब', 'किस साल', 'कितने समय'];

    const GREETING_WORDS = ['hi', 'hello', 'hey', 'vanakkam', 'namaste', 'namaskar', 'good morning', 'good evening', 'thanks', 'thank you',
        'வணக்கம்', 'நன்றி', 'नमस्ते', 'नमस्कार', 'धन्यवाद'];

    /** Rule-vocabulary graha => names a customer might type. */
    const PLANET_NAMES = [
        'Surya' => ['surya', 'sun', 'suriyan', 'சூரியன்', 'सूर्य'],
        'Chandra' => ['chandra', 'moon', 'chandran', 'சந்திரன்', 'चंद्र', 'चन्द्र'],
        'Sevvai' => ['sevvai', 'chevvai', 'mars', 'kuja', 'mangal', 'செவ்வாய்', 'मंगल'],
        'Budha' => ['budha', 'budhan', 'mercury', 'புதன்', 'बुध'],
        'Guru' => ['guru', 'jupiter', 'brihaspati', 'குரு', 'गुरु', 'बृहस्पति'],
        'Sukra' => ['sukra', 'sukran', 'shukra', 'venus', 'சுக்கிரன்', 'சுக்ரன்', 'शुक्र'],
        'Sani' => ['sani', 'shani', 'saturn', 'சனி', 'शनि'],
        'Rahu' => ['rahu', 'ராகு', 'राहु'],
        'Ketu' => ['ketu', 'கேது', 'केतु'],
    ];

    // ------------------------------------------------------------------
    // Entry point
    // ------------------------------------------------------------------

    /**
     * @param array|null $chart   AstroAiProvider chart facts (may carry 'summary' and 'labels').
     * @param array      $context customerName, chartHeader, dashaEndDate, ...
     * @return array{content:string, bubbles:array, sourceLine:string, areaId:?string, handoff:bool, mode:string}
     */
    public static function answer(string $question, string $language, ?array $chart, array $context = []): array
    {
        $lang = in_array($language, ['en', 'ta', 'hi'], true) ? $language : 'en';
        $q = mb_strtolower(trim($question), 'UTF-8');
        $name = trim((string) ($context['customerName'] ?? ''));
        if ($name === '' || $name === 'there') {
            $name = '';
        }

        // 1. Fixed refusal routes always win (legal, money, medicine, lifespan, curse, price).
        $retrieved = AstroAiProvider::retrieve($question, $lang, $chart);
        if (!empty($retrieved['refusal']) && ($retrieved['refusal']['route'] ?? '') === 'no-sales'
            && ($extra = self::matchExtraArea($q)) !== null) {
            // "how much money will I earn" is a wealth question, not a price question.
            $retrieved = self::retrieveArea($extra, $question, $lang, $chart);
        }
        if (!empty($retrieved['refusal'])) {
            $text = self::refusalText((string) $retrieved['refusal']['route'], (string) $retrieved['refusal']['text'], $lang);
            return self::finish([$text], '', null, true, $lang);
        }

        // 2. A plain greeting gets a greeting and the list of topics.
        if (self::isGreeting($q)) {
            return self::finish([self::greeting($name, $lang, $chart !== null), self::topicsLine($lang)], '', null, false, $lang);
        }

        // Area choice on WHOLE words (the shared retrieve() matches substrings,
        // so "current" would hit the property phrase "rent"). Re-scope the
        // rules when the whole-word winner differs.
        $areaId = self::matchExtraArea($q);
        if ($areaId !== null && $areaId !== ($retrieved['areaId'] ?? null)) {
            $retrieved = self::retrieveArea($areaId, $question, $lang, $chart);
        }

        $planet = self::mentionedPlanet($q);
        $wantsRemedy = self::containsAny($q, self::REMEDY_WORDS);

        // 3. A remedy question with no life-area: remedies registry only.
        if ($areaId === null && ($wantsRemedy || $planet !== null)) {
            $bubbles = [self::remedyText($planet ?? self::dashaPlanet($chart), $lang)];
            if ($chart === null) {
                $bubbles[] = self::personalHint($lang);
            }
            return self::finish($bubbles, self::remedySourceLine($planet ?? self::dashaPlanet($chart)), null, false, $lang);
        }

        // 4. Nothing in the knowledge base matches: say so honestly and offer the astrologer.
        if ($areaId === null) {
            return self::finish([self::noMatchText($lang), self::topicsLine($lang)], '', null, true, $lang);
        }

        // 5. A life-area answer.
        $bubbles = self::areaBubbles($areaId, $retrieved, $question, $lang, $chart, $context, $name);
        if ($wantsRemedy || $planet !== null) {
            $bubbles[] = self::remedyText($planet ?? self::dashaPlanet($chart), $lang);
        }
        if ($areaId === 'health') {
            $bubbles[] = self::doctorLine($lang);
        }

        $sourceLine = AstroAiProvider::tamilOnlySourceLine((string) ($retrieved['sourceLine'] ?? ''));
        return self::finish($bubbles, $sourceLine, $areaId, $areaId === 'health', $lang);
    }

    // ------------------------------------------------------------------
    // Life-area answers
    // ------------------------------------------------------------------

    private static function areaBubbles(string $areaId, array $retrieved, string $question, string $lang, ?array $chart, array $context, string $name): array
    {
        $title = (string) ($retrieved['cardTitle'] ?? $areaId);
        $bubbles = [];

        if ($areaId === 'current-guidance') {
            return self::currentGuidanceBubbles($retrieved, $question, $lang, $chart, $name);
        }

        if ($chart === null) {
            $bubbles[] = self::t($lang, [
                'en' => 'Here is how Tamil astrology reads ' . $title . ':',
                'ta' => $title . ' பற்றி தமிழ் ஜோதிடம் சொல்வது:',
                'hi' => $title . ' के बारे में तमिल ज्योतिष क्या कहता है:',
            ]) . "\n" . self::generalAreaText($areaId, $lang);
            $bubbles[] = self::personalHint($lang);
            return $bubbles;
        }

        // The customer's own report reading for this card.
        $summary = self::summaryText($chart, $areaId, $lang);
        $intro = self::t($lang, [
            'en' => ($name !== '' ? $name . ', h' : 'H') . 'ere is what your horoscope shows for ' . $title . ':',
            'ta' => ($name !== '' ? $name . ', ' : '') . 'உங்கள் ஜாதகப்படி ' . $title . ':',
            'hi' => ($name !== '' ? $name . ', ' : '') . 'आपकी कुंडली के अनुसार ' . $title . ':',
        ]);
        $bubbles[] = $intro . "\n" . ($summary !== '' ? $summary : self::generalAreaText($areaId, $lang));

        // Classical rules that actually fired on this chart.
        $ruleLines = [];
        $tips = [];
        foreach (($retrieved['rules'] ?? []) as $rule) {
            if (count($ruleLines) >= 2) {
                break;
            }
            $meaning = trim((string) ($rule['meaning'] ?? ''));
            if ($meaning === '') {
                continue;
            }
            $ruleLines[] = '• ' . $meaning;
            foreach (($rule['practical'] ?? []) as $p) {
                $tips[] = (string) $p;
            }
        }
        if ($ruleLines) {
            $bubbles[] = self::t($lang, [
                'en' => 'What the classical Tamil texts add for your chart:',
                'ta' => 'உங்கள் ஜாதகத்திற்கு மரபு தமிழ் நூல்கள் சொல்வது:',
                'hi' => 'आपकी कुंडली पर शास्त्रीय तमिल ग्रंथ क्या जोड़ते हैं:',
            ]) . "\n" . implode("\n", $ruleLines);
        }
        // Practical steps are written in English in the rule base.
        if ($tips && $lang === 'en') {
            $bubbles[] = 'Practical steps: ' . implode('; ', array_slice(array_values(array_unique($tips)), 0, 3)) . '.';
        }

        if (self::containsAny(mb_strtolower($question, 'UTF-8'), self::TIMING_WORDS)) {
            $period = self::periodLine($chart, $lang);
            if ($period !== '') {
                $bubbles[] = $period . ' ' . self::t($lang, [
                    'en' => 'Astrology shows favourable and slower periods, not fixed dates - your own effort decides the outcome.',
                    'ta' => 'ஜோதிடம் சாதகமான மற்றும் மெதுவான காலங்களை காட்டுகிறது, உறுதியான தேதிகளை அல்ல - உங்கள் முயற்சியே முடிவை தீர்மானிக்கும்.',
                    'hi' => 'ज्योतिष अनुकूल और धीमे समय दिखाता है, तय तारीखें नहीं - परिणाम आपके प्रयास पर निर्भर है।',
                ]);
            }
        }

        return $bubbles;
    }

    private static function currentGuidanceBubbles(array $retrieved, string $question, string $lang, ?array $chart, string $name): array
    {
        $bubbles = [];
        if ($chart === null) {
            $bubbles[] = self::generalAreaText('current-guidance', $lang);
            $bubbles[] = self::personalHint($lang);
        } else {
            $period = self::periodLine($chart, $lang);
            $star = self::starLine($chart, $lang);
            if ($name !== '' && $lang === 'en' && $period !== '') {
                $period = lcfirst($period);
            }
            $first = trim(($name !== '' ? $name . ', ' : '') . $period . ($star !== '' ? ' ' . $star : ''));
            $bubbles[] = $first !== '' ? $first : self::generalAreaText('current-guidance', $lang);
            $summary = self::summaryText($chart, 'current-guidance', $lang);
            if ($summary !== '') {
                $bubbles[] = $summary;
            }
            $bubbles[] = self::t($lang, [
                'en' => 'The Mahadasha is the broad chapter of life you are in; the Bhukti is the shorter section inside it, and it shapes the present most closely.',
                'ta' => 'மகாதசை என்பது நீங்கள் இருக்கும் வாழ்க்கையின் பெரிய அத்தியாயம்; புக்தி அதற்குள் உள்ள சிறு பகுதி - தற்போதைய நிலையை அதுவே நெருக்கமாக காட்டுகிறது.',
                'hi' => 'महादशा जीवन का बड़ा अध्याय है; भुक्ति उसके भीतर का छोटा हिस्सा है, और वर्तमान को वही सबसे करीब से दिखाती है।',
            ]);
        }

        // The panchangam explanation, when the customer asks about it. The rule
        // text opens with a one-sentence instruction; the rest is customer-facing.
        foreach (($retrieved['rules'] ?? []) as $rule) {
            if (($rule['id'] ?? '') === 'current-panchangam-difference') {
                $text = (string) ($rule['meaning'] ?? '');
                $cut = $lang === 'hi' ? mb_strpos($text, '। ', 0, 'UTF-8') : mb_strpos($text, '. ', 0, 'UTF-8');
                if ($cut !== false) {
                    $bubbles[] = trim(mb_substr($text, $cut + 2, null, 'UTF-8'));
                }
            }
        }
        return $bubbles;
    }

    /** Re-runs retrieval scoped to one area (used when only an extra phrase matched). */
    private static function retrieveArea(string $areaId, string $question, string $lang, ?array $chart): array
    {
        $kb = json_decode((string) file_get_contents(self::kbFile('/knowledge/ai-astrologer/rules/life-areas.json')), true) ?: [];
        foreach (($kb['areas'] ?? []) as $area) {
            if (($area['id'] ?? '') !== $areaId) {
                continue;
            }
            $rules = [];
            $sources = [];
            foreach (($area['rules'] ?? []) as $rule) {
                if (!AstroAiProvider::evaluateCondition($rule['condition'] ?? [], $chart, $question)) {
                    continue;
                }
                $labels = [];
                foreach (($rule['source'] ?? []) as $s) {
                    if (($s['level'] ?? 'book') !== 'suppressed') {
                        $labels[] = AstroAiProvider::formatCitation($s, $lang);
                    }
                }
                $rules[] = [
                    'id' => $rule['id'],
                    'meaning' => $rule['meaning'][$lang] ?? ($rule['meaning']['en'] ?? ''),
                    'easing' => $rule['easing'] ?? '',
                    'practical' => $rule['practical'] ?? [],
                    'sources' => $labels,
                ];
                $sources = array_merge($sources, $labels);
            }
            $unique = array_values(array_unique($sources));
            return [
                'areaId' => $areaId,
                'cardTitle' => $area['cardTitle'][$lang] ?? ($area['cardTitle']['en'] ?? $areaId),
                'rules' => $rules,
                'sourceLine' => $unique ? 'Source: ' . implode(' · ', array_slice($unique, 0, 3)) : '',
                'refusal' => null,
            ];
        }
        return ['areaId' => $areaId, 'cardTitle' => $areaId, 'rules' => [], 'sourceLine' => '', 'refusal' => null];
    }

    private static function kbFile(string $rel): string
    {
        foreach ([dirname(__DIR__, 2) . $rel, dirname(__DIR__) . $rel] as $candidate) {
            if (is_file($candidate)) {
                return $candidate;
            }
        }
        return dirname(__DIR__, 2) . $rel;
    }

    // ------------------------------------------------------------------
    // Chart-derived lines
    // ------------------------------------------------------------------

    private static function summaryText(array $chart, string $areaId, string $lang): string
    {
        $prefix = self::SUMMARY_KEYS[$areaId] ?? null;
        if ($prefix === null) {
            return '';
        }
        $suffix = $lang === 'ta' ? 'Ta' : ($lang === 'hi' ? 'Hi' : 'En');
        $text = trim((string) ($chart['summary'][$prefix . $suffix] ?? ''));
        if ($text === '' && $suffix !== 'En') {
            $text = trim((string) ($chart['summary'][$prefix . 'En'] ?? ''));
        }
        return $text;
    }

    private static function periodLine(?array $chart, string $lang): string
    {
        if ($chart === null) {
            return '';
        }
        $labels = $chart['labels'] ?? [];
        $maha = (string) ($labels['dasha'][$lang] ?? ($chart['currentDasha'] ?? ''));
        $bhukti = (string) ($labels['bhukti'][$lang] ?? ($chart['currentAntardasha'] ?? ''));
        $end = (string) ($chart['dashaEndDate'] ?? '');
        if ($maha === '') {
            return '';
        }
        if ($lang === 'ta') {
            return 'நீங்கள் தற்போது ' . $maha . ' மகாதசை' . ($bhukti !== '' ? ', ' . $bhukti . ' புக்தியில்' : 'யில்') . ' இருக்கிறீர்கள்'
                . ($end !== '' ? '; இந்த புக்தி ' . $end . ' வரை நீடிக்கும்.' : '.');
        }
        if ($lang === 'hi') {
            return 'आप अभी ' . $maha . ' महादशा' . ($bhukti !== '' ? ' और ' . $bhukti . ' भुक्ति' : '') . ' में हैं'
                . ($end !== '' ? '; यह भुक्ति ' . $end . ' तक चलेगी।' : '।');
        }
        return 'You are now in ' . $maha . ' Mahadasha' . ($bhukti !== '' ? ' with ' . $bhukti . ' Bhukti' : '')
            . ($end !== '' ? ', which runs until ' . $end . '.' : '.');
    }

    private static function starLine(array $chart, string $lang): string
    {
        $labels = $chart['labels'] ?? [];
        $star = (string) ($labels['nakshatra'][$lang] ?? ($chart['moonNakshatra'] ?? ''));
        $rasi = (string) ($labels['rasi'][$lang] ?? ($chart['moonSign'] ?? ''));
        $lagna = (string) ($labels['lagna'][$lang] ?? ($chart['lagna'] ?? ''));
        if ($star === '' && $rasi === '' && $lagna === '') {
            return '';
        }
        if ($lang === 'ta') {
            return 'உங்கள் லக்னம் ' . $lagna . ', ராசி ' . $rasi . ', நட்சத்திரம் ' . $star . '.';
        }
        if ($lang === 'hi') {
            return 'आपका लग्न ' . $lagna . ', राशि ' . $rasi . ' और नक्षत्र ' . $star . ' है।';
        }
        return 'Your Lagna is ' . $lagna . ', your Moon sign (Rasi) is ' . $rasi . ' and your birth star is ' . $star . '.';
    }

    /** Rule-vocabulary graha of the running Mahadasha, if a chart is attached. */
    private static function dashaPlanet(?array $chart): ?string
    {
        $p = (string) ($chart['currentDasha'] ?? '');
        return $p !== '' && isset(self::PLANET_NAMES[$p]) ? $p : null;
    }

    // ------------------------------------------------------------------
    // Remedies
    // ------------------------------------------------------------------

    private static function remedyText(?string $planet, string $lang): string
    {
        $reg = json_decode((string) file_get_contents(self::kbFile('/knowledge/ai-astrologer/rules/remedies.json')), true) ?: [];
        if ($planet !== null) {
            foreach (($reg['grahas'] ?? []) as $g) {
                if (($g['graha'] ?? '') !== $planet) {
                    continue;
                }
                $label = $lang === 'ta' ? (string) ($g['tamil'] ?? $planet) . ' (' . $planet . ')'
                    : ($lang === 'hi' ? (string) ($g['hindi'] ?? $planet) . ' (' . $planet . ')' : $planet);
                $l = self::t($lang, [
                    'en' => ['Simple remedies for ', 'Day: ', 'Prayer: ', 'Charity: ', 'Temple: '],
                    'ta' => [' - எளிய பரிகாரங்கள்', 'கிழமை: ', 'வழிபாடு: ', 'தானம்: ', 'கோயில்: '],
                    'hi' => [' - सरल उपाय', 'दिन: ', 'प्रार्थना: ', 'दान: ', 'मंदिर: '],
                ]);
                $head = $lang === 'en' ? $l[0] . $label . ':' : $label . $l[0] . ':';
                return $head
                    . "\n• " . $l[1] . ($g['weekday'] ?? '')
                    . "\n• " . $l[2] . ($g['mantra']['simple'] ?? '')
                    . "\n• " . $l[3] . ($g['charity'] ?? '')
                    . "\n• " . $l[4] . ($g['temple']['name'] ?? '')
                    . "\n" . self::t($lang, [
                        'en' => 'Do what you can with devotion - no costly ritual is needed.',
                        'ta' => 'உங்களால் முடிந்ததை பக்தியுடன் செய்யுங்கள் - செலவான சடங்குகள் தேவையில்லை.',
                        'hi' => 'जो संभव हो, श्रद्धा से करें - महंगे अनुष्ठान की आवश्यकता नहीं है।',
                    ]);
            }
        }
        $lines = [];
        foreach (($reg['universal'] ?? []) as $u) {
            $lines[] = '• ' . ($u['offer'] ?? '');
        }
        return self::t($lang, [
            'en' => 'Simple remedies our texts recommend for everyone:',
            'ta' => 'எல்லோருக்கும் எங்கள் நூல்கள் பரிந்துரைக்கும் எளிய பரிகாரங்கள்:',
            'hi' => 'हमारे ग्रंथ सबके लिए ये सरल उपाय बताते हैं:',
        ]) . "\n" . implode("\n", array_slice($lines, 0, 3));
    }

    private static function remedySourceLine(?string $planet): string
    {
        $reg = json_decode((string) file_get_contents(self::kbFile('/knowledge/ai-astrologer/rules/remedies.json')), true) ?: [];
        $ids = [];
        foreach (($reg['grahas'] ?? []) as $g) {
            if ($planet !== null && ($g['graha'] ?? '') === $planet) {
                foreach (($g['source'] ?? []) as $s) {
                    $ids[] = (string) ($s['id'] ?? '');
                }
            }
        }
        $ids = array_values(array_filter(array_unique($ids), [AstroAiProvider::class, 'isCitableId']));
        return $ids ? 'Source: ' . implode(' · ', array_slice($ids, 0, 3)) : '';
    }

    // ------------------------------------------------------------------
    // Fixed texts
    // ------------------------------------------------------------------

    private static function refusalText(string $route, string $routeText, string $lang): string
    {
        $isLegal = $route === 'decline-with-referral' && stripos($routeText, 'legal') !== false;
        $key = $isLegal ? 'legal' : $route;
        $texts = [
            'legal' => [
                'en' => 'Astrology cannot replace legal advice. For a court case or any legal matter, please speak to a qualified lawyer. If you like, I can explain the general nature of your current Dasha period instead.',
                'ta' => 'ஜோதிடம் சட்ட ஆலோசனைக்கு மாற்றாகாது. நீதிமன்ற வழக்கு அல்லது சட்ட விஷயங்களுக்கு தகுதியான வழக்கறிஞரை அணுகவும். விரும்பினால், உங்கள் தற்போதைய தசா காலத்தின் பொதுவான தன்மையை விளக்குகிறேன்.',
                'hi' => 'ज्योतिष कानूनी सलाह का विकल्प नहीं है। अदालत के मामले या किसी कानूनी विषय के लिए कृपया किसी योग्य वकील से मिलें। चाहें तो मैं आपकी वर्तमान दशा का सामान्य स्वरूप समझा सकता हूँ।',
            ],
            'decline-with-referral' => [
                'en' => 'I cannot give investment or trading advice. Please speak to a registered financial adviser before any investment. If you like, I can tell you what your chart says about wealth in general.',
                'ta' => 'முதலீடு அல்லது பங்கு வர்த்தக ஆலோசனை என்னால் வழங்க இயலாது. எந்த முதலீட்டிற்கும் முன் பதிவு பெற்ற நிதி ஆலோசகரை அணுகவும். விரும்பினால், உங்கள் ஜாதகத்தில் பொதுவான தன நிலையை சொல்கிறேன்.',
                'hi' => 'मैं निवेश या ट्रेडिंग की सलाह नहीं दे सकता। किसी भी निवेश से पहले पंजीकृत वित्तीय सलाहकार से मिलें। चाहें तो मैं बता सकता हूँ कि आपकी कुंडली धन के बारे में सामान्य रूप से क्या कहती है।',
            ],
            'health-guardrail' => [
                'en' => 'I cannot suggest any medicine, tablet or dose. Please follow the advice of a qualified doctor. I can share what your chart says about general well-being and simple routines, if that helps.',
                'ta' => 'எந்த மருந்தையோ மாத்திரையையோ அளவையோ என்னால் பரிந்துரைக்க இயலாது. தயவுசெய்து தகுதியான மருத்துவர் ஆலோசனையை பின்பற்றவும். விரும்பினால், உங்கள் ஜாதகப்படி பொதுவான நல்வாழ்வு பற்றி சொல்கிறேன்.',
                'hi' => 'मैं कोई दवा, गोली या खुराक नहीं बता सकता। कृपया योग्य डॉक्टर की सलाह मानें। चाहें तो मैं आपकी कुंडली के अनुसार सामान्य स्वास्थ्य-दिनचर्या के बारे में बता सकता हूँ।',
            ],
            'refuse-prediction' => [
                'en' => 'This is not something astrology should predict, and I will not try. What I can do is explain your current period and the simple remedies for it - or you can tap "Talk to our astrologer" and speak to our astrologer personally.',
                'ta' => 'இதை ஜோதிடம் கணிக்கக் கூடாது; நானும் முயற்சிக்க மாட்டேன். உங்கள் தற்போதைய காலத்தையும் அதற்கான எளிய பரிகாரங்களையும் விளக்க முடியும் - அல்லது "எங்கள் ஜோதிடருடன் பேசுங்கள்" என்பதை அழுத்தி எங்கள் ஜோதிடரிடம் நேரடியாக பேசலாம்.',
                'hi' => 'यह ऐसी बात नहीं है जिसकी भविष्यवाणी ज्योतिष को करनी चाहिए, और मैं ऐसा नहीं करूँगा। मैं आपकी वर्तमान अवधि और उसके सरल उपाय समझा सकता हूँ - या "हमारे ज्योतिषी से बात करें" दबाकर सीधे हमारे ज्योतिषी से बात करें।',
            ],
            'decline-respectfully' => [
                'en' => 'I cannot confirm or deny such things. The ordinary practices our texts recommend are a temple visit, daily japa and a small act of charity. If you feel troubled again and again, please tap "Talk to our astrologer".',
                'ta' => 'இது போன்றவற்றை உறுதிப்படுத்தவோ மறுக்கவோ என்னால் இயலாது. கோயில் தரிசனம், தினசரி ஜபம், சிறு தானம் ஆகியவையே எங்கள் நூல்கள் சொல்லும் எளிய வழிகள். தொடர்ந்து மன வருத்தம் இருந்தால் "எங்கள் ஜோதிடருடன் பேசுங்கள்" என்பதை அழுத்தவும்.',
                'hi' => 'मैं ऐसी बातों की पुष्टि या खंडन नहीं कर सकता। हमारे ग्रंथ सामान्य उपाय बताते हैं - मंदिर दर्शन, नित्य जप और थोड़ा दान। यदि बार-बार परेशानी हो, तो कृपया "हमारे ज्योतिषी से बात करें" दबाएँ।',
            ],
            'no-sales' => [
                'en' => 'Prices for all reports are shown on the Services page and at checkout in your dashboard. I am here for astrology questions - ask me anything about your chart.',
                'ta' => 'அனைத்து அறிக்கைகளின் விலையும் சேவைகள் பக்கத்திலும் உங்கள் டாஷ்போர்டில் செக்அவுட்டிலும் காட்டப்படும். ஜோதிட கேள்விகளுக்காக நான் இங்கே இருக்கிறேன் - உங்கள் ஜாதகம் பற்றி எதையும் கேளுங்கள்.',
                'hi' => 'सभी रिपोर्ट की कीमतें सेवाएँ पेज पर और आपके डैशबोर्ड के चेकआउट में दिखाई जाती हैं। मैं ज्योतिष प्रश्नों के लिए हूँ - अपनी कुंडली के बारे में कुछ भी पूछें।',
            ],
        ];
        return $texts[$key][$lang] ?? ($texts['refuse-prediction'][$lang]);
    }

    private static function generalAreaText(string $areaId, string $lang): string
    {
        $texts = [
            'health' => [
                'en' => 'Health is read mainly from the 1st house (Lagna) and its lord, which stand for the body and vitality, with the 6th house for minor ailments and recovery, and the 8th and 12th houses for long treatment and rest. The Moon shows the mind and sleep.',
                'ta' => 'உடல்நலம் முக்கியமாக 1-ஆம் வீடு (லக்னம்) மற்றும் லக்னாதிபதியால் பார்க்கப்படுகிறது - இவை உடலையும் உயிர்சக்தியையும் குறிக்கும். 6-ஆம் வீடு சிறு தொந்தரவுகளையும் குணமாவதையும், 8, 12-ஆம் வீடுகள் நீண்ட சிகிச்சையையும் ஓய்வையும் காட்டும். சந்திரன் மனதையும் தூக்கத்தையும் குறிக்கும்.',
                'hi' => 'स्वास्थ्य मुख्य रूप से पहले भाव (लग्न) और लग्नेश से देखा जाता है, जो शरीर और जीवन-शक्ति के कारक हैं। छठा भाव छोटी शिकायतें और स्वास्थ्य-लाभ, तथा आठवाँ और बारहवाँ भाव लंबा उपचार और विश्राम दिखाते हैं। चंद्रमा मन और नींद का कारक है।',
            ],
            'wealth' => [
                'en' => 'Wealth is read from the 2nd house (savings, family wealth and speech) and the 11th house (income and gains), with their lords. A link between these houses and the 6th, 8th or 12th shows expense or delay. Guru (Jupiter) is the natural significator of wealth.',
                'ta' => 'செல்வம் 2-ஆம் வீடு (சேமிப்பு, குடும்ப சொத்து, வாக்கு) மற்றும் 11-ஆம் வீடு (வருமானம், லாபம்), அவற்றின் அதிபதிகளால் பார்க்கப்படுகிறது. இவை 6, 8, 12-ஆம் வீடுகளுடன் தொடர்புடையால் செலவு அல்லது தாமதம் காட்டும். குரு செல்வத்தின் இயற்கை காரகர்.',
                'hi' => 'धन दूसरे भाव (बचत, पारिवारिक धन, वाणी) और ग्यारहवें भाव (आय और लाभ) तथा उनके स्वामियों से देखा जाता है। इनका छठे, आठवें या बारहवें भाव से संबंध खर्च या देरी दिखाता है। गुरु धन के नैसर्गिक कारक हैं।',
            ],
            'education' => [
                'en' => 'Education is read from the 5th house (learning, memory and intelligence) and its lord, from Budha (Mercury) for study and speech, and from the 9th house for higher study and teachers. The periods of Budha, Guru and Sukra are traditionally treated as supportive for exams.',
                'ta' => 'கல்வி 5-ஆம் வீடு (அறிவு, நினைவாற்றல்) மற்றும் அதன் அதிபதி, படிப்பு மற்றும் வாக்கிற்கு புதன், உயர்கல்வி மற்றும் ஆசிரியருக்கு 9-ஆம் வீடு ஆகியவற்றால் பார்க்கப்படுகிறது. புதன், குரு, சுக்கிரன் காலங்கள் தேர்வுகளுக்கு சாதகமாக கருதப்படுகின்றன.',
                'hi' => 'शिक्षा पाँचवें भाव (विद्या, स्मृति, बुद्धि) और उसके स्वामी, पढ़ाई व वाणी के लिए बुध, तथा उच्च शिक्षा और गुरु के लिए नवें भाव से देखी जाती है। बुध, गुरु और शुक्र की दशाएँ परीक्षा के लिए परंपरागत रूप से सहायक मानी जाती हैं।',
            ],
            'career' => [
                'en' => 'Career is read from the 10th house (profession and public standing) and its lord. The 7th house shows business and partners, and Sani (Saturn) shows steady, hard-earned work. The running Dasha and Bhukti show when change is favoured.',
                'ta' => 'தொழில் 10-ஆம் வீடு (உத்தியோகம், சமூக அந்தஸ்து) மற்றும் அதன் அதிபதியால் பார்க்கப்படுகிறது. 7-ஆம் வீடு வியாபாரம், கூட்டாளிகளை காட்டும்; சனி நிலையான உழைப்பை குறிக்கும். நடப்பு தசை, புக்தி மாற்றத்திற்கு சாதகமான காலத்தை காட்டும்.',
                'hi' => 'करियर दसवें भाव (व्यवसाय और प्रतिष्ठा) और उसके स्वामी से देखा जाता है। सातवाँ भाव व्यापार और साझेदार दिखाता है, और शनि स्थिर, परिश्रम से मिला काम। चल रही दशा और भुक्ति बताती है कि बदलाव कब अनुकूल है।',
            ],
            'marriage' => [
                'en' => 'Marriage is read from the 7th house (spouse and partnership) and its lord, with Sukra (Venus) as the significator of marriage, and Guru (Jupiter). Sevvai (Kuja) dosha is checked from the Lagna, Moon and Venus, and is always judged by matching both charts, never from one chart alone.',
                'ta' => 'திருமணம் 7-ஆம் வீடு (வாழ்க்கைத் துணை) மற்றும் அதன் அதிபதி, திருமண காரகர் சுக்கிரன், குரு ஆகியவற்றால் பார்க்கப்படுகிறது. செவ்வாய் தோஷம் லக்னம், சந்திரன், சுக்கிரனிலிருந்து பார்க்கப்படுகிறது; அது எப்போதும் இரு ஜாதகங்களையும் பொருத்திப் பார்த்தே முடிவு செய்யப்படும்.',
                'hi' => 'विवाह सातवें भाव (जीवनसाथी) और उसके स्वामी, विवाह के कारक शुक्र, और गुरु से देखा जाता है। मंगल (कुज) दोष लग्न, चंद्र और शुक्र से देखा जाता है, और हमेशा दोनों कुंडलियों के मिलान से ही आँका जाता है।',
            ],
            'property' => [
                'en' => 'Home, land and property are read from the 4th house and its lord, with the Moon for peace at home. Saturn, Rahu or Ketu in the 4th can show repeated moves or delays before settling.',
                'ta' => 'வீடு, நிலம், சொத்து 4-ஆம் வீடு மற்றும் அதன் அதிபதியால் பார்க்கப்படுகிறது; வீட்டு அமைதிக்கு சந்திரன். 4-ஆம் வீட்டில் சனி, ராகு அல்லது கேது இருந்தால் இடமாற்றங்கள் அல்லது நிலைபெற தாமதம் காட்டும்.',
                'hi' => 'घर, भूमि और संपत्ति चौथे भाव और उसके स्वामी से देखी जाती है, तथा घर की शांति के लिए चंद्रमा। चौथे भाव में शनि, राहु या केतु बार-बार स्थान-परिवर्तन या स्थिर होने में देरी दिखा सकते हैं।',
            ],
            'travel-foreign' => [
                'en' => 'Travel and fortune abroad are read from the 9th house (long journeys and fortune) and the 12th house (living away from the birthplace), with Rahu, which the classical texts link to foreign lands.',
                'ta' => 'பயணமும் வெளிநாட்டு அதிர்ஷ்டமும் 9-ஆம் வீடு (நீண்ட பயணம், பாக்கியம்), 12-ஆம் வீடு (பிறந்த இடத்தை விட்டு வாழ்வது), மற்றும் வெளிநாட்டுடன் தொடர்புடைய ராகு ஆகியவற்றால் பார்க்கப்படுகிறது.',
                'hi' => 'यात्रा और विदेश में भाग्य नवें भाव (लंबी यात्रा और भाग्य), बारहवें भाव (जन्मस्थान से दूर निवास) और राहु से देखे जाते हैं, जिसे शास्त्र विदेश से जोड़ते हैं।',
            ],
            'current-guidance' => [
                'en' => 'Your present phase of life is read from the Vimshottari Dasha system: the Mahadasha is the broad chapter of life you are in, and the Bhukti is the shorter section inside it. Saturn\'s transit from your Moon sign (including Sade Sati) adds the present-day layer.',
                'ta' => 'உங்கள் தற்போதைய வாழ்க்கை நிலை விம்சோத்தரி தசா முறையால் பார்க்கப்படுகிறது: மகாதசை வாழ்க்கையின் பெரிய அத்தியாயம், புக்தி அதற்குள் உள்ள சிறு பகுதி. உங்கள் ராசியிலிருந்து சனியின் கோசாரம் (ஏழரை சனி உட்பட) தற்போதைய நிலையை சேர்க்கும்.',
                'hi' => 'आपके जीवन का वर्तमान चरण विंशोत्तरी दशा पद्धति से देखा जाता है: महादशा जीवन का बड़ा अध्याय है और भुक्ति उसके भीतर का छोटा हिस्सा। आपकी चंद्र राशि से शनि का गोचर (साढ़े साती सहित) वर्तमान की परत जोड़ता है।',
            ],
        ];
        return $texts[$areaId][$lang] ?? ($texts[$areaId]['en'] ?? '');
    }

    private static function personalHint(string $lang): string
    {
        return self::t($lang, [
            'en' => 'For a reading of your own horoscope, open this chat from a completed report in My Dashboard - I can then answer from your own chart.',
            'ta' => 'உங்கள் சொந்த ஜாதகப் பலனுக்கு, என் டாஷ்போர்டில் முடிந்த அறிக்கையிலிருந்து இந்த உரையாடலைத் திறக்கவும் - அப்போது உங்கள் ஜாதகத்திலிருந்தே பதில் சொல்வேன்.',
            'hi' => 'अपनी कुंडली का फल जानने के लिए, मेरे डैशबोर्ड में किसी पूर्ण रिपोर्ट से यह चैट खोलें - तब मैं आपकी अपनी कुंडली से उत्तर दूँगा।',
        ]);
    }

    private static function doctorLine(string $lang): string
    {
        return self::t($lang, [
            'en' => 'This is an astrological indication only, not a diagnosis. For any health concern, please see a qualified doctor.',
            'ta' => 'இது ஜோதிட அறிகுறி மட்டுமே, நோய் கண்டறிதல் அல்ல. உடல்நலம் தொடர்பான எந்த கவலைக்கும் தகுதியான மருத்துவர் ஆலோசனையைப் பெறவும்.',
            'hi' => 'यह केवल ज्योतिषीय संकेत है, निदान नहीं। स्वास्थ्य की किसी भी चिंता के लिए कृपया योग्य डॉक्टर से मिलें।',
        ]);
    }

    private static function greeting(string $name, string $lang, bool $hasChart): string
    {
        $who = $name !== '' ? ' ' . $name : '';
        return self::t($lang, [
            'en' => 'Vanakkam' . $who . '! I am the ASTRO SIVAM astrology assistant. I answer from our own Tamil astrology sources'
                . ($hasChart ? ' and your horoscope.' : '.'),
            'ta' => 'வணக்கம்' . $who . '! நான் ASTRO SIVAM ஜோதிட உதவியாளர். எங்கள் சொந்த தமிழ் ஜோதிட நூல்களிலிருந்து'
                . ($hasChart ? ' உங்கள் ஜாதகத்தை வைத்து' : '') . ' பதில் சொல்கிறேன்.',
            'hi' => 'नमस्ते' . $who . '! मैं ASTRO SIVAM ज्योतिष सहायक हूँ। मैं हमारे अपने तमिल ज्योतिष स्रोतों'
                . ($hasChart ? ' और आपकी कुंडली' : '') . ' से उत्तर देता हूँ।',
        ]);
    }

    private static function topicsLine(string $lang): string
    {
        return self::t($lang, [
            'en' => 'You can ask me about: career, marriage, wealth, well-being, education, property, travel abroad, your current Dasha period, or remedies (pariharam). For example: "How is my career?"',
            'ta' => 'நீங்கள் கேட்கலாம்: தொழில், திருமணம், செல்வம், ஆரோக்கியம், கல்வி, சொத்து, வெளிநாட்டு பயணம், தற்போதைய தசை, அல்லது பரிகாரங்கள். உதாரணம்: "என் தொழில் எப்படி இருக்கும்?"',
            'hi' => 'आप पूछ सकते हैं: करियर, विवाह, धन, आरोग्य, शिक्षा, संपत्ति, विदेश यात्रा, वर्तमान दशा, या उपाय। उदाहरण: "मेरा करियर कैसा रहेगा?"',
        ]);
    }

    private static function noMatchText(string $lang): string
    {
        return self::t($lang, [
            'en' => 'I could not find this in our astrology sources, and I would rather not guess. You can tap "Talk to our astrologer" and our astrologer will reply to you personally.',
            'ta' => 'இதை எங்கள் ஜோதிட நூல்களில் என்னால் காண முடியவில்லை; ஊகித்து சொல்ல விரும்பவில்லை. "எங்கள் ஜோதிடருடன் பேசுங்கள்" என்பதை அழுத்தினால் எங்கள் ஜோதிடர் உங்களுக்கு நேரடியாக பதிலளிப்பார்.',
            'hi' => 'यह मुझे हमारे ज्योतिष स्रोतों में नहीं मिला, और मैं अनुमान नहीं लगाना चाहता। "हमारे ज्योतिषी से बात करें" दबाएँ, हमारे ज्योतिषी आपको स्वयं उत्तर देंगे।',
        ]);
    }

    // ------------------------------------------------------------------
    // Helpers
    // ------------------------------------------------------------------

    /** Picks the language entry from a {en,ta,hi} map. */
    private static function t(string $lang, array $map)
    {
        return $map[$lang] ?? $map['en'];
    }

    private static function containsAny(string $q, array $words): bool
    {
        foreach ($words as $w) {
            if (self::hasWord($q, (string) $w)) {
                return true;
            }
        }
        return false;
    }

    /**
     * Latin words match on word boundaries ("sun" must not match "sunday",
     * "uk" must not match "luck"); Tamil/Hindi match as substrings because
     * case endings attach to the word.
     */
    private static function hasWord(string $q, string $w): bool
    {
        $w = mb_strtolower(trim($w), 'UTF-8');
        if ($w === '') {
            return false;
        }
        if (preg_match('/^[a-z0-9 \']+$/', $w) === 1) {
            return preg_match('/(?<![a-z])' . preg_quote($w, '/') . '(?![a-z])/u', $q) === 1;
        }
        return mb_strpos($q, $w, 0, 'UTF-8') !== false;
    }

    private static function isGreeting(string $q): bool
    {
        if (mb_strlen($q, 'UTF-8') > 30) {
            return false;
        }
        return self::containsAny($q, self::GREETING_WORDS) && self::matchExtraArea($q) === null
            && !self::containsAny($q, self::REMEDY_WORDS);
    }

    private static function areaPhrases(): array
    {
        static $phrases = null;
        if ($phrases !== null) {
            return $phrases;
        }
        $phrases = self::EXTRA_PHRASES;
        $kb = json_decode((string) file_get_contents(self::kbFile('/knowledge/ai-astrologer/rules/life-areas.json')), true) ?: [];
        foreach (($kb['areas'] ?? []) as $area) {
            $id = (string) ($area['id'] ?? '');
            foreach (($area['customerPhrases'] ?? []) as $list) {
                foreach ((array) $list as $p) {
                    $phrases[$id][] = (string) $p;
                }
            }
        }
        foreach ($phrases as $id => $list) {
            $phrases[$id] = array_values(array_unique($list));
        }
        return $phrases;
    }

    private static function matchExtraArea(string $q): ?string
    {
        $best = null;
        $bestScore = 0;
        $generic = 0;
        foreach (self::areaPhrases() as $areaId => $words) {
            $score = 0;
            foreach ($words as $w) {
                if (self::hasWord($q, $w)) {
                    $score += mb_strlen($w, 'UTF-8');
                }
            }
            // current-guidance is the generic fallback; any specific area wins over it.
            if ($areaId === 'current-guidance') {
                $generic = $score;
                continue;
            }
            if ($score > $bestScore) {
                $best = $areaId;
                $bestScore = $score;
            }
        }
        // A question about the period itself ("what is my current dasha")
        // stays with current-guidance even if it also names an area word;
        // a soft word like "this year" does not outrank a specific area.
        if ($best === null) {
            return $generic > 0 ? 'current-guidance' : null;
        }
        return self::containsAny($q, self::PERIOD_WORDS) ? 'current-guidance' : $best;
    }

    private static function mentionedPlanet(string $q): ?string
    {
        foreach (self::PLANET_NAMES as $graha => $names) {
            foreach ($names as $n) {
                if (self::hasWord($q, $n)) {
                    return $graha;
                }
            }
        }
        return null;
    }

    /**
     * Caps the bubbles at four, puts the source line on the last one, and runs
     * the same output guard on every local reply. A health word without a doctor
     * line gets the doctor line; anything else that fails ships the safe
     * fallback and offers the astrologer.
     */
    private static function finish(array $bubbles, string $sourceLine, ?string $areaId, bool $handoff, string $lang): array
    {
        $bubbles = array_values(array_filter(array_map('trim', $bubbles), static function ($b) {
            return $b !== '';
        }));
        if (count($bubbles) > 4) {
            $head = array_slice($bubbles, 0, 3);
            $head[] = implode("\n\n", array_slice($bubbles, 3));
            $bubbles = $head;
        }

        $check = AstroAiProvider::checkReply(implode("\n\n", $bubbles), $lang);
        if (!$check['ok'] && $check['violations'] === ['health topic without advising a qualified doctor']) {
            $bubbles[] = self::doctorLine($lang);
            $check = AstroAiProvider::checkReply(implode("\n\n", $bubbles), $lang);
        }
        if (!$check['ok']) {
            error_log('AI Astrologer (knowledge-base mode) guard rejected a reply: ' . implode('; ', $check['violations']));
            $fallback = AstroAiProvider::fallbackReply($lang);
            return ['content' => $fallback, 'bubbles' => [$fallback], 'sourceLine' => '',
                'areaId' => $areaId, 'handoff' => true, 'mode' => 'knowledge-base'];
        }

        if ($sourceLine !== '') {
            $bubbles[count($bubbles) - 1] .= "\n" . $sourceLine;
        }
        return [
            'content' => implode("\n\n", $bubbles),
            'bubbles' => $bubbles,
            'sourceLine' => $sourceLine,
            'areaId' => $areaId,
            'handoff' => $handoff,
            'mode' => 'knowledge-base',
        ];
    }
}
