<?php
/**
 * ASTRO SIVAM source-based astrologer - local knowledge-base mode.
 *
 * Every reply is assembled from ASTRO SIVAM's own sources only:
 *
 *   1. the customer's own report readings (AstroEngine's per-area summary,
 *      rebuilt from the saved order inputs - the same text as the PDF),
 *   2. the curated classical rules in knowledge/ai-astrologer/rules/
 *      life-areas.json, evaluated against the customer's chart,
 *   3. the remedies registry (knowledge/ai-astrologer/rules/remedies.json),
 *   4. the fixed refusal routes and guardrails.
 *
 * Nothing is generated by a language model, so nothing unreviewed can reach a
 * customer, and the chat works on any host with no paid service. The same
 * output guard (AstroAiProvider::checkReply) still runs on every reply.
 *
 * Returns the same shape as AstroAiProvider::answer() so the endpoint and the
 * browser do not need to know which mode produced the answer.
 */

require_once __DIR__ . '/ai_astrologer_provider.php';

class AstroAiOffline
{
    /** Life-area id => key prefix of AstroEngine's summary texts. */
    const SUMMARY_KEYS = [
        'health' => 'health',
        'wealth' => 'wealth',
        'education' => 'education',
        'career' => 'career',
        'marriage' => 'marriage',
        'property' => 'family',
        'travel-foreign' => 'foreignTravel',
        'current-guidance' => 'currentPeriodGuidance',
    ];

    /**
     * Extra everyday words per area, on top of customerPhrases in
     * life-areas.json, so plain questions ("will I get a job", "when is my
     * wedding") still find the right card without a model to interpret them.
     */
    const EXTRA_PHRASES = [
        'career' => ['job', 'jobs', 'work', 'office', 'promotion', 'boss', 'business', 'salary', 'profession', 'employment', 'career',
            'வேலை', 'உத்தியோகம்', 'தொழில்', 'பதவி', 'வியாபாரம்', 'नौकरी', 'काम', 'व्यापार', 'व्यवसाय', 'प्रमोशन', 'करियर', 'कैरियर', 'तरक्की'],
        'marriage' => ['marriage', 'married', 'marry', 'wedding', 'wife', 'husband', 'spouse', 'partner', 'love', 'relationship', 'divorce', 'child', 'children', 'baby',
            'திருமணம்', 'கல்யாணம்', 'மனைவி', 'கணவர்', 'காதல்', 'குழந்தை', 'विवाह', 'शादी', 'पत्नी', 'पति', 'प्रेम', 'संतान', 'बच्चे'],
        'wealth' => ['money', 'wealth', 'finance', 'income', 'debt', 'loan', 'savings', 'rich', 'financial',
            'பணம்', 'செல்வம்', 'வருமானம்', 'கடன்', 'சேமிப்பு', 'धन', 'पैसा', 'आय', 'कर्ज', 'बचत'],
        'education' => ['study', 'studies', 'exam', 'education', 'college', 'school', 'degree', 'university',
            'படிப்பு', 'கல்வி', 'தேர்வு', 'பரீட்சை', 'पढ़ाई', 'शिक्षा', 'परीक्षा'],
        'property' => ['house', 'home', 'land', 'property', 'flat', 'apartment', 'vehicle', 'car',
            'வீடு', 'நிலம்', 'சொத்து', 'வாகனம்', 'घर', 'जमीन', 'संपत्ति', 'मकान', 'वाहन'],
        'travel-foreign' => ['abroad', 'foreign', 'travel', 'visa', 'overseas', 'settle', 'migrate', 'australia', 'canada', 'usa', 'uk', 'new zealand',
            'வெளிநாடு', 'பயணம்', 'விசா', 'विदेश', 'यात्रा', 'वीज़ा', 'वीजा'],
        'health' => ['health', 'sick', 'illness', 'pain', 'tired', 'sleep', 'stress', 'anxiety',
            'உடல்நலம்', 'நோய்', 'தூக்கம்', 'மன அழுத்தம்', 'स्वास्थ्य', 'बीमार', 'नींद', 'तनाव'],
        'current-guidance' => ['dasha', 'dasa', 'bhukti', 'period', 'this year', 'next year', 'future', 'sade sati', 'ezharai', 'nakshatra', 'star', 'panchangam', 'horoscope', 'chart', 'my life',
            'தசை', 'திசை', 'புக்தி', 'ஏழரை', 'நட்சத்திரம்', 'ஜாதகம்', 'எதிர்காலம்', 'இந்த வருடம்', 'பஞ்சாங்கம்',
            'दशा', 'भुक्ति', 'साढ़े साती', 'नक्षत्र', 'कुंडली', 'भविष्य', 'इस साल'],
    ];

    /** Words that make a question about the running period itself. */
    const PERIOD_WORDS = ['dasha', 'dasa', 'bhukti', 'mahadasha', 'antardasha', 'sade sati', 'nakshatra', 'birth star', 'panchangam', 'panchang',
        'தசை', 'திசை', 'புக்தி', 'ஏழரை', 'நட்சத்திரம்', 'பஞ்சாங்கம்', 'दशा', 'भुक्ति', 'साढ़े साती', 'नक्षत्र', 'पंचांग'];

    const REMEDY_WORDS = ['remedy', 'remedies', 'pariharam', 'parikaram', 'parihara', 'mantra', 'temple', 'pooja', 'puja', 'prayer', 'fasting', 'charity',
        'பரிகாரம்', 'மந்திரம்', 'கோயில்', 'கோவில்', 'பூஜை', 'விரதம்', 'தானம்', 'उपाय', 'मंत्र', 'मंदिर', 'पूजा', 'व्रत', 'दान'];

    const TIMING_WORDS = ['when', 'which year', 'how long', 'what time', 'எப்போது', 'எப்பொழுது', 'எந்த வருடம்', 'எவ்வளவு காலம்', 'कब', 'किस साल', 'कितने समय'];

    const GREETING_WORDS = ['hi', 'hello', 'hey', 'vanakkam', 'namaste', 'namaskar', 'good morning', 'good evening',
        'வணக்கம்', 'नमस्ते', 'नमस्कार'];

    /**
     * Everyday small talk, per reply id. Phrases are checked before the astrology
     * areas, so "how are you" or "what's your name" is answered here instead of
     * being handed to the astrologer. Order matters: the first id that matches wins.
     */
    const SMALL_TALK_PHRASES = [
        'nice' => ['nice to meet you', 'nice to meet', 'pleasure to meet', 'உங்களைச் சந்தித்ததில்', 'आपसे मिलकर', 'मिलकर खुशी'],
        'bye' => ['bye', 'goodbye', 'good bye', 'good night', 'see you', 'take care', 'விடைபெறுகிறேன்', 'अलविदा', 'शुभ रात्रि'],
        'thanks' => ['thank you', 'thanks', 'thank u', 'thank', 'நன்றி', 'धन्यवाद', 'शुक्रिया'],
        'wellbeing' => ['how are you', 'how r u', 'how are u', 'how do you do', 'what\'s up', 'whats up', 'எப்படி இருக்கீங்க', 'எப்படி இருக்கிறீர்கள்', 'எப்படி இருக்கிறீங்க', 'आप कैसे हैं', 'आप कैसे हो'],
        'origin' => ['where are you from', 'where do you live', 'where are you', 'where r u', 'where do you come from', 'நீங்கள் எங்கிருந்து', 'எங்கிருந்து வருகிறீர்கள்', 'आप कहाँ से', 'आप कहां से'],
        'name' => ['what\'s your name', 'what is your name', 'your name', 'who are you', 'who am i talking', 'உங்கள் பெயர்', 'நீங்கள் யார்', 'आपका नाम', 'आप कौन'],
        'bot' => ['are you a bot', 'are you a robot', 'are you human', 'are you real', 'are you ai', 'are you an ai', 'are you a human', 'நீங்கள் மனிதரா', 'आप इंसान', 'आप रोबोट'],
        'age' => ['how old are you', 'your age', 'உங்கள் வயது', 'आपकी उम्र'],
        'help' => ['what can you do', 'how can you help', 'what do you do', 'what can i ask', 'help', 'உதவி', 'आप क्या कर', 'मदद'],
    ];

    /** Rule-vocabulary graha => names a customer might type. */
    const PLANET_NAMES = [
        'Surya' => ['surya', 'sun', 'suriyan', 'சூரியன்', 'सूर्य'],
        'Chandra' => ['chandra', 'moon', 'chandran', 'சந்திரன்', 'चंद्र', 'चन्द्र'],
        'Sevvai' => ['sevvai', 'chevvai', 'mars', 'kuja', 'mangal', 'செவ்வாய்', 'मंगल'],
        'Budha' => ['budha', 'budhan', 'mercury', 'புதன்', 'बुध'],
        'Guru' => ['guru', 'jupiter', 'brihaspati', 'குரு', 'गुरु', 'बृहस्पति'],
        'Sukra' => ['sukra', 'sukran', 'shukra', 'venus', 'சுக்கிரன்', 'சுக்ரன்', 'शुक्र'],
        'Sani' => ['sani', 'shani', 'saturn', 'சனி', 'शनि'],
        'Rahu' => ['rahu', 'ராகு', 'राहु'],
        'Ketu' => ['ketu', 'கேது', 'केतु'],
    ];

    // ------------------------------------------------------------------
    // Entry point
    // ------------------------------------------------------------------

    /**
     * @param array|null $chart   AstroAiProvider chart facts (may carry 'summary' and 'labels').
     * @param array      $context customerName, chartHeader, dashaEndDate, ...
     * @return array{content:string, bubbles:array, sourceLine:string, areaId:?string, handoff:bool, mode:string}
     */
    public static function answer(string $question, string $language, ?array $chart, array $context = []): array
    {
        $lang = in_array($language, ['en', 'ta', 'hi'], true) ? $language : 'en';
        $q = mb_strtolower(trim($question), 'UTF-8');
        $name = trim((string) ($context['customerName'] ?? ''));
        if ($name === '' || $name === 'there') {
            $name = '';
        }

        // GUIDED MODE — the customer picked a curated option, so the answer
        // path is fixed by the menu instead of guessed from wording. Order,
        // complaint, dosha and remedy options never enter refusal or area
        // matching; area options skip matching and go straight to their card.
        $guided = (isset($context['guided']) && is_array($context['guided'])) ? $context['guided'] : null;
        $guidedKind = $guided !== null ? (string) ($guided['kind'] ?? 'area') : null;
        if ($guidedKind === 'order') {
            $escalate = ($guided['escalate'] ?? false) === true;
            return self::finish(self::orderBubbles($guided, $lang, $context, $chart, $name), '', null, $escalate, $lang);
        }
        if ($guidedKind === 'complaint') {
            return self::finish([self::complaintAck($lang)], '', null, true, $lang);
        }
        if ($guidedKind === 'dosha') {
            return self::finish(self::doshaBubbles($guided, $lang, $chart, $name), '', null, false, $lang);
        }
        if ($guidedKind === 'service') {
            // The customer's own Wedding Matching / Baby Naming / Subha
            // Muhurtham report. Read from it, never re-judged.
            $route = self::serviceRoute($guided, $lang, $context, $name);
            return self::finish($route['bubbles'], '', null, (bool) ($route['handoff'] ?? false), $lang);
        }
        if ($guidedKind === 'remedy') {
            $planet = (isset($guided['planet']) && is_string($guided['planet']) && isset(self::PLANET_NAMES[$guided['planet']]))
                ? $guided['planet'] : null;
            $target = $planet ?? self::dashaPlanet($chart);
            $bubbles = [self::remedyText($target, $lang)];
            if (($guided['focus'] ?? '') === 'temple') {
                $temple = self::templeText($lang);
                if ($temple !== '') {
                    $bubbles[] = $temple;
                }
            }
            return self::finish($bubbles, self::remedySourceLine($target), null, false, $lang);
        }

        // 1. Fixed refusal routes always win (legal, money, medicine, lifespan, curse, price).
        $retrieved = AstroAiProvider::retrieve($question, $lang, $chart);
        if (!empty($retrieved['refusal']) && ($retrieved['refusal']['route'] ?? '') === 'no-sales'
            && ($extra = self::matchExtraArea($q)) !== null) {
            // "how much money will I earn" is a wealth question, not a price question.
            $retrieved = self::retrieveArea($extra, $question, $lang, $chart);
        }
        if (!empty($retrieved['refusal'])) {
            $text = self::refusalText((string) $retrieved['refusal']['route'], (string) $retrieved['refusal']['text'], $lang);
            return self::finish([$text], '', null, true, $lang);
        }

        // 2. Small talk and greetings are answered here, never handed to the astrologer.
        $talk = self::smallTalkBubbles($q, $lang);
        if (self::isGreeting($q)) {
            $greeting = self::greeting($name, $lang, $chart !== null);
            return self::finish($talk !== [] ? array_merge([$greeting], $talk) : [$greeting, self::topicsLine($lang)], '', null, false, $lang);
        }
        if ($talk !== []) {
            return self::finish($talk, '', null, false, $lang);
        }

        // A guided area option names its own card, so it skips matching
        // entirely: the menu cannot miss, and a wording change in the menu
        // can never route a customer to the wrong card.
        if ($guidedKind === 'area' && is_string($guided['area'] ?? null) && ($guided['area'] ?? '') !== '') {
            $forcedArea = (string) $guided['area'];
            $forced = self::retrieveArea($forcedArea, $question, $lang, $chart);
            $bubbles = self::areaBubbles($forcedArea, $forced, $question, $lang, $chart, $context, $name, !empty($guided['timing']));
            if (!empty($guided['remedy'])) {
                $bubbles[] = self::remedyText(self::dashaPlanet($chart), $lang);
            }
            if ($forcedArea === 'health') {
                $bubbles[] = self::doctorLine($lang);
            }
            $sourceLine = AstroAiProvider::tamilOnlySourceLine((string) ($forced['sourceLine'] ?? ''));
            return self::finish($bubbles, $sourceLine, $forcedArea, $forcedArea === 'health', $lang);
        }

        // Area choice on WHOLE words (the shared retrieve() matches substrings,
        // so "current" would hit the property phrase "rent"). Re-scope the
        // rules when the whole-word winner differs.
        $areaId = self::matchExtraArea($q);
        if ($areaId !== null && $areaId !== ($retrieved['areaId'] ?? null)) {
            $retrieved = self::retrieveArea($areaId, $question, $lang, $chart);
        }

        $planet = self::mentionedPlanet($q);
        $wantsRemedy = self::containsAny($q, self::REMEDY_WORDS);

        // 3. A remedy question with no life-area: remedies registry only.
        if ($areaId === null && ($wantsRemedy || $planet !== null)) {
            $bubbles = [self::remedyText($planet ?? self::dashaPlanet($chart), $lang)];
            if ($chart === null) {
                $bubbles[] = self::personalHint($lang);
            }
            return self::finish($bubbles, self::remedySourceLine($planet ?? self::dashaPlanet($chart)), null, false, $lang);
        }

        // 4. Nothing in the knowledge base matches: say so honestly and offer the astrologer.
        if ($areaId === null) {
            return self::finish([self::noMatchText($lang), self::topicsLine($lang)], '', null, true, $lang);
        }

        // 5. A life-area answer.
        $bubbles = self::areaBubbles($areaId, $retrieved, $question, $lang, $chart, $context, $name);
        if ($wantsRemedy || $planet !== null) {
            $bubbles[] = self::remedyText($planet ?? self::dashaPlanet($chart), $lang);
        }
        if ($areaId === 'health') {
            $bubbles[] = self::doctorLine($lang);
        }

        $sourceLine = AstroAiProvider::tamilOnlySourceLine((string) ($retrieved['sourceLine'] ?? ''));
        return self::finish($bubbles, $sourceLine, $areaId, $areaId === 'health', $lang);
    }

    // ------------------------------------------------------------------
    // Life-area answers
    // ------------------------------------------------------------------

    private static function areaBubbles(string $areaId, array $retrieved, string $question, string $lang, ?array $chart, array $context, string $name, bool $forceTiming = false): array
    {
        $title = (string) ($retrieved['cardTitle'] ?? $areaId);
        $bubbles = [];

        if ($areaId === 'current-guidance') {
            return self::currentGuidanceBubbles($retrieved, $question, $lang, $chart, $name);
        }

        if ($chart === null) {
            $bubbles[] = self::t($lang, [
                'en' => 'Here is how Tamil astrology reads ' . $title . ':',
                'ta' => $title . ' பற்றி தமிழ் ஜோதிடம் சொல்வது:',
                'hi' => $title . ' के बारे में तमिल ज्योतिष क्या कहता है:',
            ]) . "\n" . self::generalAreaText($areaId, $lang);
            $bubbles[] = self::personalHint($lang);
            return $bubbles;
        }

        // The customer's own report reading for this card.
        $summary = self::summaryText($chart, $areaId, $lang);
        $intro = self::t($lang, [
            'en' => ($name !== '' ? $name . ', h' : 'H') . 'ere is what your horoscope shows for ' . $title . ':',
            'ta' => ($name !== '' ? $name . ', ' : '') . 'உங்கள் ஜாதகப்படி ' . $title . ':',
            'hi' => ($name !== '' ? $name . ', ' : '') . 'आपकी कुंडली के अनुसार ' . $title . ':',
        ]);
        $bubbles[] = $intro . "\n" . ($summary !== '' ? $summary : self::generalAreaText($areaId, $lang));

        // Classical rules that actually fired on this chart.
        $ruleLines = [];
        $tips = [];
        foreach (($retrieved['rules'] ?? []) as $rule) {
            if (count($ruleLines) >= 2) {
                break;
            }
            $meaning = trim((string) ($rule['meaning'] ?? ''));
            if ($meaning === '') {
                continue;
            }
            $ruleLines[] = '• ' . $meaning;
            foreach (($rule['practical'] ?? []) as $p) {
                $tips[] = (string) $p;
            }
        }
        if ($ruleLines) {
            $bubbles[] = self::t($lang, [
                'en' => 'What the classical Tamil texts add for your chart:',
                'ta' => 'உங்கள் ஜாதகத்திற்கு மரபு தமிழ் நூல்கள் சொல்வது:',
                'hi' => 'आपकी कुंडली पर शास्त्रीय तमिल ग्रंथ क्या जोड़ते हैं:',
            ]) . "\n" . implode("\n", $ruleLines);
        }
        // Practical steps are written in English in the rule base.
        if ($tips && $lang === 'en') {
            $bubbles[] = 'Practical steps: ' . implode('; ', array_slice(array_values(array_unique($tips)), 0, 3)) . '.';
        }

        if ($forceTiming || self::containsAny(mb_strtolower($question, 'UTF-8'), self::TIMING_WORDS)) {
            $period = self::periodLine($chart, $lang);
            if ($period !== '') {
                $bubbles[] = $period . ' ' . self::t($lang, [
                    'en' => 'Astrology shows favourable and slower periods, not fixed dates - your own effort decides the outcome.',
                    'ta' => 'ஜோதிடம் சாதகமான மற்றும் மெதுவான காலங்களை காட்டுகிறது, உறுதியான தேதிகளை அல்ல - உங்கள் முயற்சியே முடிவை தீர்மானிக்கும்.',
                    'hi' => 'ज्योतिष अनुकूल और धीमे समय दिखाता है, तय तारीखें नहीं - परिणाम आपके प्रयास पर निर्भर है।',
                ]);
            }
        }

        return $bubbles;
    }

    private static function currentGuidanceBubbles(array $retrieved, string $question, string $lang, ?array $chart, string $name): array
    {
        $bubbles = [];
        if ($chart === null) {
            $bubbles[] = self::generalAreaText('current-guidance', $lang);
            $bubbles[] = self::personalHint($lang);
        } else {
            $period = self::periodLine($chart, $lang);
            $star = self::starLine($chart, $lang);
            if ($name !== '' && $lang === 'en' && $period !== '') {
                $period = lcfirst($period);
            }
            $first = trim(($name !== '' ? $name . ', ' : '') . $period . ($star !== '' ? ' ' . $star : ''));
            $bubbles[] = $first !== '' ? $first : self::generalAreaText('current-guidance', $lang);
            $summary = self::summaryText($chart, 'current-guidance', $lang);
            if ($summary !== '') {
                $bubbles[] = $summary;
            }
            $bubbles[] = self::t($lang, [
                'en' => 'The Mahadasha is the broad chapter of life you are in; the Bhukti is the shorter section inside it, and it shapes the present most closely.',
                'ta' => 'மகாதசை என்பது நீங்கள் இருக்கும் வாழ்க்கையின் பெரிய அத்தியாயம்; புக்தி அதற்குள் உள்ள சிறு பகுதி - தற்போதைய நிலையை அதுவே நெருக்கமாக காட்டுகிறது.',
                'hi' => 'महादशा जीवन का बड़ा अध्याय है; भुक्ति उसके भीतर का छोटा हिस्सा है, और वर्तमान को वही सबसे करीब से दिखाती है।',
            ]);
        }

        // The panchangam explanation, when the customer asks about it. The rule
        // text opens with a one-sentence instruction; the rest is customer-facing.
        foreach (($retrieved['rules'] ?? []) as $rule) {
            if (($rule['id'] ?? '') === 'current-panchangam-difference') {
                $text = (string) ($rule['meaning'] ?? '');
                $cut = $lang === 'hi' ? mb_strpos($text, '। ', 0, 'UTF-8') : mb_strpos($text, '. ', 0, 'UTF-8');
                if ($cut !== false) {
                    $bubbles[] = trim(mb_substr($text, $cut + 2, null, 'UTF-8'));
                }
            }
        }
        return $bubbles;
    }

    // ------------------------------------------------------------------
    // Guided-only answers: order facts, doshas, temples, complaints
    // ------------------------------------------------------------------

    /**
     * Answers the "My Order & Report" options from the customer's own order
     * row only. Facts (order number, dates, amounts, birth details) are read
     * from $context['orderDetails'], which the endpoint built from this
     * customer's order — never from another account, never a price list.
     */
    private static function orderBubbles(array $guided, string $lang, array $context, ?array $chart, string $name): array
    {
        $details = (string) ($context['orderDetails'] ?? '');
        if ($details === '' || strpos($details, 'no order attached') !== false) {
            return [self::personalHint($lang)];
        }
        $who = $name !== '' ? $name . ', ' : '';
        $topic = (string) ($guided['topic'] ?? 'status');

        if ($topic === 'payment') {
            $paid = '';
            if (preg_match('/Amount paid: ([^|]+)/', $details, $m)) {
                $paid = trim($m[1]);
            }
            $head = self::t($lang, [
                'en' => $who . 'here is what our records show for this order:',
                'ta' => $who . 'இந்த ஆர்டருக்கு எங்கள் பதிவுகள் சொல்வது:',
                'hi' => $who . 'इस ऑर्डर के लिए हमारे रिकॉर्ड यह बताते हैं:',
            ]);
            $line = $paid !== ''
                ? $paid
                : self::t($lang, [
                    'en' => 'No payment amount is recorded on this order (it may be your free first report).',
                    'ta' => 'இந்த ஆர்டரில் கட்டணத் தொகை பதிவாகவில்லை (இது உங்கள் இலவச முதல் அறிக்கையாக இருக்கலாம்).',
                    'hi' => 'इस ऑर्डर पर कोई भुगतान राशि दर्ज नहीं है (यह आपकी मुफ़्त पहली रिपोर्ट हो सकती है)।',
                ]);
            return [$head . "\n" . $line];
        }

        if ($topic === 'details') {
            $birth = '';
            if (preg_match('/Birth details used: (.+?)( \\| Report language:|$)/', $details, $m)) {
                $birth = trim($m[1]);
            }
            if ($birth === '') {
                return [self::t($lang, [
                    'en' => $who . 'I could not read the birth details on this order. Please use the correction option below and our team will check them with you.',
                    'ta' => $who . 'இந்த ஆர்டரில் பிறப்பு விவரங்களை என்னால் படிக்க முடியவில்லை. கீழே உள்ள திருத்த விருப்பத்தை பயன்படுத்தவும்; எங்கள் குழு உங்களுடன் சரிபார்க்கும்.',
                    'hi' => $who . 'मैं इस ऑर्डर के जन्म विवरण नहीं पढ़ सका। कृपया नीचे सुधार विकल्प चुनें; हमारी टीम आपसे जाँच करेगी।',
                ])];
            }
            return [self::t($lang, [
                'en' => $who . 'your chart was calculated from these details:',
                'ta' => $who . 'உங்கள் ஜாதகம் இந்த விவரங்களிலிருந்து கணிக்கப்பட்டது:',
                'hi' => $who . 'आपकी कुंडली इन्हीं विवरणों से बनाई गई:',
            ]) . "\n" . $birth];
        }

        if ($topic === 'correction') {
            return [self::t($lang, [
                'en' => $who . 'thank you for telling us. Birth details decide the whole chart, so corrections are made by our team, not in this chat. I have sent your request to them — they will contact you shortly. Please keep your correct date, time and place of birth ready.',
                'ta' => $who . 'சொன்னதற்கு நன்றி. பிறப்பு விவரங்களே முழு ஜாதகத்தையும் தீர்மானிக்கின்றன; எனவே திருத்தங்களை எங்கள் குழுவே செய்யும். உங்கள் கோரிக்கையை அவர்களுக்கு அனுப்பிவிட்டேன் — விரைவில் தொடர்பு கொள்வார்கள். சரியான தேதி, நேரம், பிறந்த இடத்தை தயாராக வைத்திருங்கள்.',
                'hi' => $who . 'बताने के लिए धन्यवाद। जन्म विवरण ही पूरी कुंडली तय करते हैं, इसलिए सुधार हमारी टीम करती है, इस चैट में नहीं। मैंने आपका अनुरोध उन्हें भेज दिया है — वे जल्द ही संपर्क करेंगे। सही तिथि, समय और जन्म स्थान तैयार रखें।',
            ])];
        }

        // status (default): delivery state + where to look.
        return [self::t($lang, [
            'en' => $who . 'here is the delivery status of your report:',
            'ta' => $who . 'உங்கள் அறிக்கையின் விநியோக நிலை:',
            'hi' => $who . 'आपकी रिपोर्ट की डिलीवरी स्थिति:',
        ]) . "\n" . $details . "\n" . self::t($lang, [
            'en' => 'If the email is not in your inbox, please check the spam folder for mail from admin@astrosivam.com.',
            'ta' => 'மின்னஞ்சல் உங்கள் இன்பாக்ஸில் இல்லையென்றால், admin@astrosivam.com-லிருந்து வந்த மெயிலுக்காக ஸ்பேம் கோப்புறையை பார்க்கவும்.',
            'hi' => 'यदि ईमेल इनबॉक्स में नहीं है, तो admin@astrosivam.com के मेल के लिए स्पैम फ़ोल्डर देखें।',
        ])];
    }

    /**
     * Answers the "Doshas in My Chart" options from the engine dosha block of
     * the bound order. The chat repeats the report's own verdict and remedy —
     * it never re-judges the chart, never calls a dosha a punishment, and
     * never attaches a frightening outcome to one.
     */
    private static function doshaBubbles(array $guided, string $lang, ?array $chart, string $name): array
    {
        $all = ($chart !== null && is_array($chart['doshaDetails'] ?? null)) ? $chart['doshaDetails'] : [];
        $wanted = (string) ($guided['dosha'] ?? 'all');
        if ($wanted !== 'all') {
            $all = array_values(array_filter($all, static function ($d) use ($wanted) {
                return ($d['key'] ?? '') === $wanted;
            }));
        }
        if (empty($all)) {
            return [
                self::t($lang, [
                    'en' => 'A dosha check needs your own chart. I could not read the dosha results for this conversation.',
                    'ta' => 'தோஷ பரிசோதனைக்கு உங்கள் சொந்த ஜாதகம் தேவை. இந்த உரையாடலுக்கான தோஷ முடிவுகளை என்னால் படிக்க முடியவில்லை.',
                    'hi' => 'दोष जाँच के लिए आपकी अपनी कुंडली चाहिए। इस बातचीत के दोष परिणाम मैं नहीं पढ़ सका।',
                ]),
                self::personalHint($lang),
            ];
        }

        $verdict = static function ($present, string $lang): string {
            if ($present === true) {
                return $lang === 'ta' ? 'உங்கள் ஜாதகத்தில் உள்ளது' : ($lang === 'hi' ? 'आपकी कुंडली में है' : 'Present in your chart');
            }
            if ($present === false) {
                return $lang === 'ta' ? 'உங்கள் ஜாதகத்தில் இல்லை' : ($lang === 'hi' ? 'आपकी कुंडली में नहीं है' : 'Not present in your chart');
            }
            return $lang === 'ta' ? 'மதிப்பிடப்படவில்லை' : ($lang === 'hi' ? 'आकलन नहीं हुआ' : 'Not assessed');
        };

        $who = $name !== '' ? $name . ', ' : '';
        $bubbles = [];
        if ($wanted === 'all') {
            $lines = [];
            foreach ($all as $d) {
                $dName = (string) ($d['name'][$lang] ?? ($d['name']['en'] ?? ''));
                $lines[] = '• ' . $dName . ' — ' . $verdict($d['present'] ?? null, $lang);
            }
            $bubbles[] = self::t($lang, [
                'en' => $who . 'here is what page 1 of your report found:',
                'ta' => $who . 'உங்கள் அறிக்கையின் பக்கம் 1 கண்டது:',
                'hi' => $who . 'आपकी रिपोर्ट के पृष्ठ 1 में यह मिला:',
            ]) . "\n" . implode("\n", $lines);
            $bubbles[] = self::t($lang, [
                'en' => 'A dosha is a configuration to be aware of and to work with, not a punishment. Tap one dosha above for its full explanation and remedy.',
                'ta' => 'தோஷம் என்பது தெரிந்துகொண்டு சமாளிக்க வேண்டிய அமைப்பே தவிர தண்டனை அல்ல. முழு விளக்கம் மற்றும் பரிகாரத்திற்கு மேலே ஒரு தோஷத்தை தேர்வு செய்யவும்.',
                'hi' => 'दोष सजा नहीं, बल्कि जानकर संभालने वाली स्थिति है। पूरे विवरण और उपाय के लिए ऊपर कोई एक दोष चुनें।',
            ]);
            return $bubbles;
        }

        $d = $all[0];
        $dName = (string) ($d['name'][$lang] ?? ($d['name']['en'] ?? ''));
        $desc = (string) ($d['description'][$lang] ?? ($d['description']['en'] ?? ''));
        $remedy = (string) ($d['remedy'][$lang] ?? ($d['remedy']['en'] ?? ''));
        $first = $who . $dName . ' — ' . $verdict($d['present'] ?? null, $lang) . '.';
        if ($desc !== '') {
            $first .= "\n" . $desc;
        }
        $bubbles[] = $first;
        if ($remedy !== '') {
            $bubbles[] = self::t($lang, [
                'en' => 'Traditional remedy from your report:',
                'ta' => 'உங்கள் அறிக்கையிலிருந்து பாரம்பரிய பரிகாரம்:',
                'hi' => 'आपकी रिपोर्ट का पारंपरिक उपाय:',
            ]) . "\n" . $remedy;
        }
        return $bubbles;
    }

    // ------------------------------------------------------------------
    // Guided service chapters: the customer's own Wedding Matching,
    // Baby Naming and Subha Muhurtham reports
    // ------------------------------------------------------------------

    /** Plain names of the service reports a guided chapter can discuss. */
    private static function serviceLabel(string $service, string $lang): string
    {
        $names = [
            'BIRTH_JATHAGAM' => ['en' => 'Birth Jathagam report', 'ta' => 'ஜன்ம ஜாதக அறிக்கை', 'hi' => 'जन्म कुंडली रिपोर्ट'],
            'MARRIAGE_COMPATIBILITY' => ['en' => 'Wedding Matching report', 'ta' => 'திருமணப் பொருத்த அறிக்கை', 'hi' => 'विवाह मिलान रिपोर्ट'],
            'BABY_NAMING' => ['en' => 'Baby Naming report', 'ta' => 'பெயர் சூட்டும் அறிக்கை', 'hi' => 'नामकरण रिपोर्ट'],
            'MUHURTHAM' => ['en' => 'Subha Muhurtham report', 'ta' => 'சுப முகூர்த்த அறிக்கை', 'hi' => 'शुभ मुहूर्त रिपोर्ट'],
            'MULTI_PERSON' => ['en' => 'Family report', 'ta' => 'குடும்ப அறிக்கை', 'hi' => 'पारिवारिक रिपोर्ट'],
        ];
        return self::t($lang, $names[$service] ?? $names['MUHURTHAM']);
    }

    /**
     * Routes a guided service option. The answer is read out of the customer's
     * own report (the porutham table, the birth-pada syllables, the muhurtham
     * calendar) - the chat never re-judges a match, never invents a syllable
     * and never names a date the report does not carry.
     *
     * @return array{bubbles:array, handoff:bool}
     */
    private static function serviceRoute(array $guided, string $lang, array $context, string $name): array
    {
        $service = strtoupper(trim((string) ($guided['service'] ?? '')));
        $topic = (string) ($guided['topic'] ?? '');
        $facts = (isset($context['serviceFacts']) && is_array($context['serviceFacts'])) ? $context['serviceFacts'] : null;
        $bound = strtoupper(trim((string) ($context['boundServiceType'] ?? '')));

        if ($facts === null || (string) ($facts['serviceType'] ?? '') !== $service) {
            // The right report is attached but could not be rebuilt here (an
            // old stored result, or a failed calculation): that is a question
            // for a person, not a nudge to attach something already attached.
            if ($bound === $service) {
                return ['bubbles' => [self::serviceUnreadableText($service, $lang, $name)], 'handoff' => true];
            }
            // Otherwise the report is not attached (or a different one is):
            // say which report is needed instead of answering from nothing.
            return ['bubbles' => self::serviceAttachBubbles($service, $bound, $lang, $name), 'handoff' => false];
        }
        if ($service === 'MARRIAGE_COMPATIBILITY' && is_array($facts['matching'] ?? null)) {
            return ['bubbles' => self::matchingBubbles($topic, $facts['matching'], $lang, $name), 'handoff' => false];
        }
        if ($service === 'BABY_NAMING' && is_array($facts['naming'] ?? null)) {
            return ['bubbles' => self::namingBubbles($topic, $facts['naming'], $lang, $name), 'handoff' => false];
        }
        if ($service === 'MUHURTHAM' && is_array($facts['muhurtham'] ?? null)) {
            return ['bubbles' => self::muhurthamBubbles($topic, $facts['muhurtham'], $lang, $name), 'handoff' => false];
        }
        // The report is attached and of the right service, but its readings
        // could not be rebuilt here (an old stored result, or a failed server
        // calculation). That is a question for a person, not for a guess.
        return ['bubbles' => [self::serviceUnreadableText($service, $lang, $name)], 'handoff' => true];
    }

    /** Asks for the report to be attached, naming the one this chat is on. */
    private static function serviceAttachBubbles(string $service, string $bound, string $lang, string $name): array
    {
        $who = $name !== '' ? $name . ', ' : '';
        $label = self::serviceLabel($service, $lang);
        $bubbles = [];
        if ($bound !== '' && $bound !== $service) {
            $bubbles[] = self::t($lang, [
                'en' => $who . 'this conversation is attached to your ' . self::serviceLabel($bound, $lang)
                    . '. To ask about your ' . $label . ', attach that report with the picker above, or open this chat from that report in My Dashboard.',
                'ta' => $who . 'இந்த உரையாடல் உங்கள் ' . self::serviceLabel($bound, $lang) . ' உடன் இணைக்கப்பட்டுள்ளது. உங்கள் '
                    . $label . ' பற்றி கேட்க, மேலே உள்ள தேர்விலிருந்து அந்த அறிக்கையை இணைக்கவும், அல்லது என் டாஷ்போர்டில் அந்த அறிக்கையிலிருந்து இந்த உரையாடலைத் திறக்கவும்.',
                'hi' => $who . 'यह बातचीत आपकी ' . self::serviceLabel($bound, $lang) . ' से जुड़ी है। अपनी ' . $label
                    . ' के बारे में पूछने के लिए ऊपर दिए चयनकर्ता से वह रिपोर्ट जोड़ें, या मेरे डैशबोर्ड में उस रिपोर्ट से यह चैट खोलें।',
            ]);
            return $bubbles;
        }
        $bubbles[] = self::t($lang, [
            'en' => $who . 'I answer this from your own ' . $label . '. Attach it with the report picker above, or open this chat from that report in My Dashboard, and I will read it for you.',
            'ta' => $who . 'இதற்கு உங்கள் சொந்த ' . $label . ' இருந்தே பதில் சொல்கிறேன். மேலே உள்ள அறிக்கைத் தேர்விலிருந்து அதை இணைக்கவும், அல்லது என் டாஷ்போர்டில் அந்த அறிக்கையிலிருந்து இந்த உரையாடலைத் திறக்கவும்.',
            'hi' => $who . 'मैं इसका उत्तर आपकी अपनी ' . $label . ' से दूँगा। ऊपर दिए चयनकर्ता से उसे जोड़ें, या मेरे डैशबोर्ड में उस रिपोर्ट से यह चैट खोलें; फिर मैं उसे पढ़कर बताऊँगा।',
        ]);
        return $bubbles;
    }

    private static function serviceUnreadableText(string $service, string $lang, string $name): string
    {
        $who = $name !== '' ? $name . ', ' : '';
        return self::t($lang, [
            'en' => $who . 'I could not read your ' . self::serviceLabel($service, $lang)
                . ' on the server just now, and I will not guess at its numbers. Please tap "Talk to our astrologer" and our astrologer will read it with you.',
            'ta' => $who . 'உங்கள் ' . self::serviceLabel($service, $lang)
                . ' இப்போது சர்வரில் என்னால் படிக்க முடியவில்லை; அதன் எண்களை ஊகித்து சொல்ல மாட்டேன். "எங்கள் ஜோதிடருடன் பேசுங்கள்" என்பதை அழுத்தினால் எங்கள் ஜோதிடர் உங்களுடன் சேர்ந்து பார்ப்பார்கள்.',
            'hi' => $who . 'मैं अभी आपकी ' . self::serviceLabel($service, $lang)
                . ' को सर्वर पर नहीं पढ़ सका, और उसके अंकों का अनुमान नहीं लगाऊँगा। "हमारे ज्योतिषी से बात करें" दबाएँ; हमारे ज्योतिषी आपके साथ उसे देखेंगे।',
        ]);
    }

    /** Uthamam / Mathimam / Porundhadhu, in the customer's language. */
    private static function poruthamStatusLabel(string $status, string $lang): string
    {
        if ($status === 'UTTHAMAM') {
            return self::t($lang, ['en' => 'Uthamam (full marks)', 'ta' => 'உத்தமம் (முழு மதிப்பெண்)', 'hi' => 'उत्तम (पूर्ण अंक)']);
        }
        if ($status === 'MADHYAMAM') {
            return self::t($lang, ['en' => 'Mathimam (partial)', 'ta' => 'மத்திமம் (பகுதி மதிப்பெண்)', 'hi' => 'मध्यम (आंशिक अंक)']);
        }
        return self::t($lang, ['en' => 'Porundhadhu (no marks)', 'ta' => 'பொருந்தாது (மதிப்பெண் இல்லை)', 'hi' => 'पोरुंदधु (अंक नहीं)']);
    }

    /** Picks the language entry of a {en,ta,hi} map built by the endpoint. */
    private static function pick($map, string $lang): string
    {
        if (!is_array($map)) {
            return trim((string) $map);
        }
        return trim((string) ($map[$lang] ?? ($map['en'] ?? '')));
    }

    /** "Chennai, Tamil Nadu, India" + "India" must not print the country twice. */
    private static function placeWithCountry(string $place, string $country): string
    {
        $place = trim($place);
        $country = trim($country);
        if ($place === '') {
            return $country;
        }
        if ($country === '' || mb_stripos($place, $country) !== false) {
            return $place;
        }
        return $place . ', ' . $country;
    }

    /** 2026-11-05 -> 05 Nov 2026, the way the report prints it. */
    private static function prettyDate(string $iso): string
    {
        if (!preg_match('/^(\d{4})-(\d{2})-(\d{2})$/', $iso, $m)) {
            return $iso;
        }
        $months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
        return $m[3] . ' ' . $months[((int) $m[2]) - 1] . ' ' . $m[1];
    }

    /**
     * Wedding Matching answers. Every number, name and verdict below is the
     * report's own: the chat repeats it, explains it, and never decides again.
     */
    private static function matchingBubbles(string $topic, array $m, string $lang, string $name): array
    {
        $who = $name !== '' ? $name . ', ' : '';
        $poruthams = array_values(array_filter((array) ($m['poruthams'] ?? []), 'is_array'));
        $groom = (string) ($m['groom']['name'] ?? '');
        $bride = (string) ($m['bride']['name'] ?? '');
        $pairLine = self::t($lang, [
            'en' => 'Read from both charts: ' . $groom . ' (' . self::pick($m['groom']['rasi'] ?? '', $lang) . ', '
                . self::pick($m['groom']['nakshatra'] ?? '', $lang) . ') and ' . $bride . ' ('
                . self::pick($m['bride']['rasi'] ?? '', $lang) . ', ' . self::pick($m['bride']['nakshatra'] ?? '', $lang) . ').',
            'ta' => 'இரு ஜாதகங்களிலிருந்தும் வாசிக்கப்பட்டது: ' . $groom . ' (' . self::pick($m['groom']['rasi'] ?? '', $lang) . ', '
                . self::pick($m['groom']['nakshatra'] ?? '', $lang) . ') மற்றும் ' . $bride . ' ('
                . self::pick($m['bride']['rasi'] ?? '', $lang) . ', ' . self::pick($m['bride']['nakshatra'] ?? '', $lang) . ').',
            'hi' => 'दोनों कुंडलियों से पढ़ा गया: ' . $groom . ' (' . self::pick($m['groom']['rasi'] ?? '', $lang) . ', '
                . self::pick($m['groom']['nakshatra'] ?? '', $lang) . ') और ' . $bride . ' ('
                . self::pick($m['bride']['rasi'] ?? '', $lang) . ', ' . self::pick($m['bride']['nakshatra'] ?? '', $lang) . ')।',
        ]);

        if ($topic === 'verdict') {
            $bubbles = [$who . self::t($lang, [
                'en' => 'the overall verdict in your Wedding Matching report:',
                'ta' => 'உங்கள் திருமணப் பொருத்த அறிக்கையின் ஒட்டுமொத்த முடிவு:',
                'hi' => 'आपकी विवाह मिलान रिपोर्ट का समग्र निर्णय:',
            ]) . "\n" . self::pick($m['verdict'] ?? '', $lang), $pairLine];
            if ((string) ($m['verdictStatus'] ?? '') !== 'UTTHAMAM') {
                $bubbles[] = self::t($lang, [
                    'en' => 'A porutham reading is guidance for both families to weigh together, not a judgement on either person. Our astrologer can go through it with you - tap "Talk to our astrologer".',
                    'ta' => 'பொருத்தப் பார்வை இரு குடும்பங்களும் சேர்ந்து எடைபோட வேண்டிய வழிகாட்டுதல்; இருவரில் யாருக்குமான தீர்ப்பு அல்ல. இதை எங்கள் ஜோதிடர் உங்களுடன் பார்க்கலாம் - "எங்கள் ஜோதிடருடன் பேசுங்கள்" என்பதை அழுத்தவும்.',
                    'hi' => 'पोरुतम पाठ दोनों परिवारों के लिए मिल-जुलकर विचारने की सलाह है, किसी व्यक्ति पर फैसला नहीं। हमारे ज्योतिषी इसे आपके साथ देख सकते हैं - "हमारे ज्योतिषी से बात करें" दबाएँ।',
                ]);
            }
            return $bubbles;
        }

        if ($topic === 'score') {
            $head = $who . self::t($lang, [
                'en' => 'your report scores this match:',
                'ta' => 'உங்கள் அறிக்கை இந்தப் பொருத்தத்திற்கு அளிக்கும் மதிப்பெண்:',
                'hi' => 'आपकी रिपोर्ट इस मिलान को दिए गए अंक:',
            ]) . "\n" . self::t($lang, [
                'en' => (string) ($m['matched'] ?? 0) . ' of ' . (string) ($m['total'] ?? 10)
                    . ' poruthams matched — ' . (string) ($m['score'] ?? 0) . ' / ' . (string) ($m['maxScore'] ?? 0)
                    . ' points (' . (string) round((float) ($m['percentage'] ?? 0)) . '%).',
                'ta' => (string) ($m['total'] ?? 10) . ' பொருத்தங்களில் ' . (string) ($m['matched'] ?? 0)
                    . ' பொருந்தியுள்ளன — ' . (string) ($m['score'] ?? 0) . ' / ' . (string) ($m['maxScore'] ?? 0)
                    . ' மதிப்பெண்கள் (' . (string) round((float) ($m['percentage'] ?? 0)) . '%).',
                'hi' => (string) ($m['total'] ?? 10) . ' में से ' . (string) ($m['matched'] ?? 0)
                    . ' पोरुतम मिले — ' . (string) ($m['score'] ?? 0) . ' / ' . (string) ($m['maxScore'] ?? 0)
                    . ' अंक (' . (string) round((float) ($m['percentage'] ?? 0)) . '%)।',
            ]);
            $lines = [];
            foreach ($poruthams as $p) {
                $lines[] = '• ' . self::pick($p['name'] ?? '', $lang) . ' — ' . (int) ($p['points'] ?? 0)
                    . '/' . (int) ($p['maxPoints'] ?? 0);
            }
            $bubbles = [$head];
            if ($lines !== []) {
                $bubbles[] = implode("\n", $lines);
            }
            return $bubbles;
        }

        if ($topic === 'poruthams') {
            $lines = [];
            foreach ($poruthams as $p) {
                if (empty($p['matched'])) {
                    continue;
                }
                $lines[] = '• ' . self::pick($p['name'] ?? '', $lang) . ' — ' . self::poruthamStatusLabel((string) ($p['status'] ?? ''), $lang)
                    . ' (' . (int) ($p['points'] ?? 0) . '/' . (int) ($p['maxPoints'] ?? 0) . ')';
            }
            if ($lines === []) {
                return [self::t($lang, [
                    'en' => 'No porutham earned marks in this match. Your report sets out each one and its remedy - our astrologer can go through it with you.',
                    'ta' => 'இந்தப் பொருத்தத்தில் எந்தப் பொருத்தமும் மதிப்பெண் பெறவில்லை. உங்கள் அறிக்கை ஒவ்வொன்றையும் அதன் பரிகாரத்துடன் காட்டுகிறது - எங்கள் ஜோதிடர் உங்களுடன் பார்க்கலாம்.',
                    'hi' => 'इस मिलान में किसी भी पोरुतम को अंक नहीं मिले। आपकी रिपोर्ट हर एक और उसका उपाय बताती है - हमारे ज्योतिषी आपके साथ देख सकते हैं।',
                ])];
            }
            return [
                $who . self::t($lang, [
                    'en' => 'these poruthams matched in your report:',
                    'ta' => 'உங்கள் அறிக்கையில் இந்தப் பொருத்தங்கள் பொருந்தின:',
                    'hi' => 'आपकी रिपोर्ट में ये पोरुतम मिले:',
                ]) . "\n" . implode("\n", $lines),
                self::t($lang, [
                    'en' => 'Uthamam means the classical condition is met in full; Mathimam means it is met in part. Your report explains each porutham in its own words.',
                    'ta' => 'உத்தமம் என்றால் அந்தச் சாஸ்திர நிபந்தனை முழுமையாக நிறைவேறியுள்ளது; மத்திமம் என்றால் பகுதியளவே. ஒவ்வொரு பொருத்தத்தையும் உங்கள் அறிக்கை அதன் சொந்த வார்த்தைகளில் விளக்குகிறது.',
                    'hi' => 'उत्तम का अर्थ है शास्त्रीय शर्त पूरी तरह पूरी हुई; मध्यम का अर्थ है आंशिक रूप से। हर पोरुतम को आपकी रिपोर्ट अपने शब्दों में समझाती है।',
                ]),
            ];
        }

        if ($topic === 'unmatched') {
            $lines = [];
            foreach ($poruthams as $p) {
                if (!empty($p['full'])) {
                    continue;
                }
                $note = self::pick($p['note'] ?? '', $lang);
                $lines[] = '• ' . self::pick($p['name'] ?? '', $lang) . ' — ' . self::poruthamStatusLabel((string) ($p['status'] ?? ''), $lang)
                    . ($note !== '' ? ': ' . $note : '');
            }
            if ($lines === []) {
                return [self::t($lang, [
                    'en' => 'Every porutham in your report earned full marks (Uthamam) for this match.',
                    'ta' => 'உங்கள் அறிக்கையில் இந்தப் பொருத்தத்திற்கு எல்லாப் பொருத்தங்களும் முழு மதிப்பெண் (உத்தமம்) பெற்றுள்ளன.',
                    'hi' => 'आपकी रिपोर्ट में इस मिलान के लिए हर पोरुतम को पूर्ण अंक (उत्तम) मिले हैं।',
                ])];
            }
            return [
                $who . self::t($lang, [
                    'en' => 'these poruthams did not earn full marks:',
                    'ta' => 'இந்தப் பொருத்தங்கள் முழு மதிப்பெண் பெறவில்லை:',
                    'hi' => 'इन पोरुतम को पूर्ण अंक नहीं मिले:',
                ]) . "\n" . implode("\n", $lines),
                self::t($lang, [
                    'en' => 'A shortfall is an indication to weigh with care, not a bar to the marriage - the classical texts give remedies for exactly this. Our astrologer can read it with both charts.',
                    'ta' => 'குறைபாடு என்பது கவனமாக எடைபோட வேண்டிய அறிகுறி, திருமணத்திற்குத் தடை அல்ல - இதற்கான பரிகாரங்களைச் சாஸ்திரங்கள் கூறுகின்றன. இரு ஜாதகங்களுடனும் எங்கள் ஜோதிடர் இதைப் பார்க்கலாம்.',
                    'hi' => 'कमी सावधानी से विचारने का संकेत है, विवाह में बाधा नहीं - शास्त्रों में इसी के लिए उपाय बताए गए हैं। हमारे ज्योतिषी दोनों कुंडलियों के साथ इसे देख सकते हैं।',
                ]),
            ];
        }

        if ($topic === 'sevvai') {
            $sevvai = is_array($m['sevvai'] ?? null) ? $m['sevvai'] : [];
            return [
                $who . self::t($lang, [
                    'en' => 'Kuja (Sevvai) Dosha in your match:',
                    'ta' => 'உங்கள் பொருத்தத்தில் செவ்வாய் தோஷம்:',
                    'hi' => 'आपके मिलान में कुज (मंगल) दोष:',
                ]) . "\n" . self::pick($sevvai['samyamLabel'] ?? '', $lang),
                self::pick($sevvai['advice'] ?? '', $lang),
            ];
        }

        // remedy
        $sevvai = is_array($m['sevvai'] ?? null) ? $m['sevvai'] : [];
        $status = (string) ($sevvai['samyamStatus'] ?? '');
        if ($status === 'BALANCED') {
            return [
                self::t($lang, [
                    'en' => 'Your report records Dosha Samyam as balanced for this match, so it advises no Kuja remedy on this count.',
                    'ta' => 'உங்கள் அறிக்கை இந்தப் பொருத்தத்திற்கு தோஷ சம்யம் சமநிலையில் உள்ளதாகப் பதிவு செய்கிறது; எனவே இந்தக் காரணத்திற்கு செவ்வாய் பரிகாரம் பரிந்துரைக்கவில்லை.',
                    'hi' => 'आपकी रिपोर्ट इस मिलान के लिए दोष साम्य संतुलित दर्ज करती है, इसलिए इस कारण से कोई मंगल उपाय नहीं बताया गया।',
                ]),
                self::t($lang, [
                    'en' => 'If you would still like to observe one, the traditional Sevvai (Angaraka) pariharam is:',
                    'ta' => 'இருந்தாலும் ஒரு பரிகாரம் செய்ய விரும்பினால், மரபான செவ்வாய் (அங்காரக) பரிகாரம்:',
                    'hi' => 'फिर भी कोई उपाय करना चाहें तो पारंपरिक मंगल (अंगारक) उपाय यह है:',
                ]) . "\n" . self::remedyText('Sevvai', $lang),
            ];
        }
        return [
            $who . self::t($lang, [
                'en' => 'your report advises these remedies for the match:',
                'ta' => 'இந்தப் பொருத்தத்திற்கு உங்கள் அறிக்கை பரிந்துரைக்கும் பரிகாரங்கள்:',
                'hi' => 'इस मिलान के लिए आपकी रिपोर्ट ये उपाय बताती है:',
            ]),
            self::pick($sevvai['advice'] ?? '', $lang),
            self::t($lang, [
                'en' => 'The traditional Sevvai (Angaraka) pariharam:',
                'ta' => 'மரபான செவ்வாய் (அங்காரக) பரிகாரம்:',
                'hi' => 'पारंपरिक मंगल (अंगारक) उपाय:',
            ]) . "\n" . self::remedyText('Sevvai', $lang),
        ];
    }

    /** Baby Naming answers: the baby's own birth star, pada sounds and names. */
    private static function namingBubbles(string $topic, array $n, string $lang, string $name): array
    {
        $who = $name !== '' ? $name . ', ' : '';
        $baby = is_array($n['baby'] ?? null) ? $n['baby'] : [];
        $babyName = trim((string) ($baby['name'] ?? ''));
        $star = self::pick($n['star'] ?? '', $lang);
        $pada = (int) ($n['pada'] ?? 0);
        $rasi = self::pick($n['rasi'] ?? '', $lang);
        $lagna = self::pick($n['lagna'] ?? '', $lang);
        $primary = self::pick($n['primarySound'] ?? '', $lang);

        if ($topic === 'star') {
            $who2 = $babyName !== '' ? $babyName . ' — ' : $who;
            return [
                $who2 . self::t($lang, [
                    'en' => 'the birth details your Namakaran report was calculated from give:',
                    'ta' => 'உங்கள் நாமகரண அறிக்கை கணிக்கப்பட்ட பிறப்பு விவரங்கள் தருவது:',
                    'hi' => 'आपकी नामकरण रिपोर्ट जिन जन्म विवरणों से बनी, वे यह बताते हैं:',
                ]) . "\n" . self::t($lang, [
                    'en' => 'Janma Nakshatra (birth star): ' . $star . "\n" . 'Pada (quarter): ' . ($pada > 0 ? (string) $pada : '—')
                        . "\n" . 'Chandra Rasi (Moon sign): ' . $rasi . "\n" . 'Lagna (ascendant): ' . $lagna,
                    'ta' => 'ஜன்ம நட்சத்திரம்: ' . $star . "\n" . 'பாதம்: ' . ($pada > 0 ? (string) $pada : '—')
                        . "\n" . 'சந்திர ராசி: ' . $rasi . "\n" . 'லக்னம்: ' . $lagna,
                    'hi' => 'जन्म नक्षत्र: ' . $star . "\n" . 'पाद (चरण): ' . ($pada > 0 ? (string) $pada : '—')
                        . "\n" . 'चंद्र राशि: ' . $rasi . "\n" . 'लग्न: ' . $lagna,
                ]),
                self::t($lang, [
                    'en' => 'The birth star and its pada decide the sounds a name may begin with.',
                    'ta' => 'பிறந்த நட்சத்திரமும் அதன் பாதமும் பெயர் தொடங்க வேண்டிய எழுத்துகளைத் தீர்மானிக்கின்றன.',
                    'hi' => 'जन्म नक्षत्र और उसका पाद तय करते हैं कि नाम किन अक्षरों से शुरू होना चाहिए।',
                ]),
            ];
        }

        if ($topic === 'letters') {
            $padas = array_values(array_filter((array) ($n['padas'] ?? []), 'is_array'));
            $lines = [];
            foreach ($padas as $p) {
                $sound = self::pick($p['sound'] ?? '', $lang);
                if ($sound === '') {
                    continue;
                }
                $rasiName = self::pick($p['rasi'] ?? '', $lang);
                $lines[] = '• ' . self::t($lang, ['en' => 'Pada ', 'ta' => 'பாதம் ', 'hi' => 'पाद '])
                    . (int) ($p['pada'] ?? 0) . ' — ' . $sound . ($rasiName !== '' ? ' (' . $rasiName . ')' : '');
            }
            $bubbles = [$who . self::t($lang, [
                'en' => 'the sounds of ' . $star . ' for your baby (pada ' . ($pada > 0 ? (string) $pada : '—') . ' is the birth pada):',
                'ta' => 'உங்கள் குழந்தைக்கு ' . $star . ' நட்சத்திரத்தின் எழுத்துகள் (பிறந்த பாதம் ' . ($pada > 0 ? (string) $pada : '—') . '):',
                'hi' => 'आपके शिशु के लिए ' . $star . ' नक्षत्र के अक्षर (जन्म पाद ' . ($pada > 0 ? (string) $pada : '—') . '):',
            ])];
            if ($lines !== []) {
                $bubbles[] = implode("\n", $lines);
            }
            $bubbles[] = self::t($lang, [
                'en' => 'The sound to use: ' . $primary . '. A name beginning with it is the traditional choice for this birth star.',
                'ta' => 'பயன்படுத்த வேண்டிய ஒலி: ' . $primary . '. இந்த எழுத்தில் தொடங்கும் பெயர் இந்த ஜன்ம நட்சத்திரத்திற்கு மரபான தேர்வு.',
                'hi' => 'जिस ध्वनि का उपयोग करना है: ' . $primary . '. इसी से शुरू होने वाला नाम इस जन्म नक्षत्र के लिए पारंपरिक विकल्प है।',
            ]);
            return $bubbles;
        }

        if ($topic === 'suggestions' || $topic === 'meaning') {
            $names = array_values(array_filter((array) ($n['names'] ?? []), 'is_array'));
            $lines = [];
            foreach (array_slice($names, 0, 6) as $entry) {
                $nm = trim((string) ($entry['name'] ?? ''));
                $meaning = self::pick($entry['meaning'] ?? '', $lang);
                if ($nm === '') {
                    continue;
                }
                $lines[] = '• ' . $nm . ($meaning !== '' ? ' — ' . $meaning : '');
            }
            if ($lines === []) {
                return [self::t($lang, [
                    'en' => 'Your report lists the name bank for ' . $primary . ' on page 2 - it carries far more names than fit in a chat message.',
                    'ta' => 'உங்கள் அறிக்கையின் பக்கம் 2-ல் ' . $primary . ' எழுத்துக்கான பெயர்ப் பட்டியல் உள்ளது - உரையாடலில் அடங்குவதை விட பல பெயர்கள் அதில் உள்ளன.',
                    'hi' => 'आपकी रिपोर्ट के पृष्ठ 2 पर ' . $primary . ' अक्षर के लिए नाम-सूची है - चैट में समाने से कहीं अधिक नाम उसमें हैं।',
                ])];
            }
            $head = $topic === 'meaning'
                ? self::t($lang, [
                    'en' => 'the meanings your report gives for these names:',
                    'ta' => 'இந்தப் பெயர்களுக்கு உங்கள் அறிக்கை தரும் பொருள்கள்:',
                    'hi' => 'इन नामों के अर्थ आपकी रिपोर्ट में:',
                ])
                : self::t($lang, [
                    'en' => 'names from your report for the sound ' . $primary . ':',
                    'ta' => $primary . ' எழுத்துக்கு உங்கள் அறிக்கையிலிருந்து பெயர்கள்:',
                    'hi' => $primary . ' ध्वनि के लिए आपकी रिपोर्ट से नाम:',
                ]);
            return [$who . $head . "\n" . implode("\n", $lines)];
        }

        // our-name: the name recorded on the order, honestly stated.
        $provenance = is_array($n['provenance'] ?? null) ? $n['provenance'] : [];
        $supplied = trim((string) ($provenance['suppliedName'] ?? ''));
        if ($supplied === '') {
            return [self::t($lang, [
                'en' => 'No name was recorded on your order, so your report certifies none. The sound to match is ' . $primary
                    . '; your report lists names beginning with it.',
                'ta' => 'உங்கள் ஆர்டரில் பெயர் பதிவு செய்யப்படவில்லை; எனவே உங்கள் அறிக்கை எந்தப் பெயரையும் சான்றளிக்கவில்லை. பொருத்த வேண்டிய ஒலி '
                    . $primary . '; அந்த எழுத்தில் தொடங்கும் பெயர்களை உங்கள் அறிக்கை பட்டியலிடுகிறது.',
                'hi' => 'आपके ऑर्डर में कोई नाम दर्ज नहीं था, इसलिए आपकी रिपोर्ट किसी नाम को प्रमाणित नहीं करती। मिलने वाली ध्वनि '
                    . $primary . ' है; इसी से शुरू होने वाले नाम आपकी रिपोर्ट में सूचीबद्ध हैं।',
            ])];
        }
        return [
            self::t($lang, [
                'en' => 'Your order records the name "' . $supplied . '". Your report certifies names that begin with the birth-pada sound ' . $primary . '.',
                'ta' => 'உங்கள் ஆர்டரில் "' . $supplied . '" என்ற பெயர் பதிவாகியுள்ளது. பிறந்த பாத ஒலியான ' . $primary . ' இல் தொடங்கும் பெயர்களை உங்கள் அறிக்கை சான்றளிக்கிறது.',
                'hi' => 'आपके ऑर्डर में "' . $supplied . '" नाम दर्ज है। आपकी रिपोर्ट उन्हीं नामों को प्रमाणित करती है जो जन्म-पाद की ध्वनि ' . $primary . ' से शुरू हों।',
            ]),
            self::pick($provenance['note'] ?? '', $lang),
        ];
    }

    /** Subha Muhurtham answers: the report's own dates, windows and reasons. */
    private static function muhurthamBubbles(string $topic, array $mu, string $lang, string $name): array
    {
        $who = $name !== '' ? $name . ', ' : '';
        $months = array_values(array_filter((array) ($mu['months'] ?? []), 'is_array'));
        $recommended = array_values(array_filter((array) ($mu['recommended'] ?? []), 'is_array'));
        $event = self::pick($mu['event'] ?? '', $lang);
        $window = self::pick($mu['window'] ?? '', $lang);

        if ($topic === 'place') {
            $both = (string) ($mu['personalCheckMode'] ?? '') === 'both';
            return [
                $who . self::t($lang, [
                    'en' => 'yes - your dates were calculated for:',
                    'ta' => 'ஆம் - உங்கள் நாட்கள் இந்த இடத்திற்காக கணிக்கப்பட்டவை:',
                    'hi' => 'हाँ - आपकी तिथियाँ इसी स्थान के लिए गणना की गई हैं:',
                ]) . "\n" . self::placeWithCountry((string) ($mu['place'] ?? ''), (string) ($mu['country'] ?? '')),
                self::t($lang, [
                    'en' => 'The calendar covers ' . $window . ' and every time is local to that place. The dates were also checked against '
                        . ($both ? 'both charts (groom and bride).' : 'your chart (Janma Nakshatra).'),
                    'ta' => 'இந்தக் காலண்டர் ' . $window . ' வரை உள்ளது; எல்லா நேரங்களும் அந்த இடத்தின் உள்ளூர் நேரம். நாட்கள் '
                        . ($both ? 'இரு ஜாதகங்களோடும் (மணமகன் மற்றும் மணமகள்)' : 'உங்கள் ஜாதகத்தோடு (ஜன்ம நட்சத்திரம்)') . ' ஒப்பிடப்பட்டன.',
                    'hi' => 'यह कैलेंडर ' . $window . ' तक है; सभी समय उसी स्थान के स्थानीय समय में हैं। तिथियाँ '
                        . ($both ? 'दोनों कुंडलियों (वर और वधू)' : 'आपकी कुंडली (जन्म नक्षत्र)') . ' से भी जाँची गईं।',
                ]),
            ];
        }

        if ($topic === 'dates') {
            $lines = [];
            foreach (array_slice($recommended, 0, 6) as $d) {
                $lines[] = '• ' . self::prettyDate((string) ($d['date'] ?? '')) . ' (' . self::pick($d['weekday'] ?? '', $lang) . ') — '
                    . self::pick($d['nakshatra'] ?? '', $lang) . ' — ' . (string) ($d['grade'] ?? '');
            }
            $bubbles = [$who . self::t($lang, [
                'en' => 'your ' . $event . ' calendar covers ' . $window . ':',
                'ta' => 'உங்கள் ' . $event . ' காலண்டர் ' . $window . ' வரை:',
                'hi' => 'आपका ' . $event . ' कैलेंडर ' . $window . ' तक है:',
            ])];
            if ($lines !== []) {
                $bubbles[] = self::t($lang, [
                    'en' => 'Recommended dates:',
                    'ta' => 'பரிந்துரைக்கப்பட்ட நாட்கள்:',
                    'hi' => 'अनुशंसित तिथियाँ:',
                ]) . "\n" . implode("\n", $lines);
            }
            foreach (array_slice($months, 0, 3) as $m) {
                $bubbles[] = self::pick($m['name'] ?? '', $lang) . ' — ' . self::t($lang, [
                    'en' => (string) ((int) ($m['bestCount'] ?? 0)) . ' best, ' . (string) ((int) ($m['goodCount'] ?? 0)) . ' good',
                    'ta' => 'சிறந்தவை ' . (string) ((int) ($m['bestCount'] ?? 0)) . ', நல்லவை ' . (string) ((int) ($m['goodCount'] ?? 0)),
                    'hi' => 'सर्वोत्तम ' . (string) ((int) ($m['bestCount'] ?? 0)) . ', शुभ ' . (string) ((int) ($m['goodCount'] ?? 0)),
                ]);
            }
            return $bubbles;
        }

        // best / why / avoid all read the strongest recommended date.
        $day = $recommended[0] ?? null;
        if (!is_array($day)) {
            return [self::t($lang, [
                'en' => 'Your report marks no date in this window as recommended for ' . $event
                    . '. Please ask our astrologer to look at the calendar with you.',
                'ta' => 'இந்தக் காலத்தில் ' . $event . ' க்கு பரிந்துரைக்கப்பட்ட நாளாக உங்கள் அறிக்கை எந்த நாளையும் குறிக்கவில்லை. '
                    . 'எங்கள் ஜோதிடரிடம் இந்தக் காலண்டரைப் பார்க்கச் சொல்லுங்கள்.',
                'hi' => 'इस अवधि में ' . $event . ' के लिए आपकी रिपोर्ट किसी तिथि को अनुशंसित नहीं करती। कृपया हमारे ज्योतिषी से इस कैलेंडर को साथ देखने को कहें।',
            ])];
        }
        $dateLine = self::prettyDate((string) ($day['date'] ?? '')) . ' (' . self::pick($day['weekday'] ?? '', $lang) . ')';
        $dayLine = $dateLine . ' — ' . self::pick($day['nakshatra'] ?? '', $lang) . ' / ' . self::pick($day['tithi'] ?? '', $lang)
            . ' (' . (string) ($day['grade'] ?? '') . ')';

        if ($topic === 'best') {
            $bubbles = [$who . self::t($lang, [
                'en' => 'the strongest date in your report:',
                'ta' => 'உங்கள் அறிக்கையில் வலுவான நாள்:',
                'hi' => 'आपकी रिपोर्ट में सबसे शुभ तिथि:',
            ]) . "\n" . $dayLine];
            $nalla = array_values(array_filter((array) ($day['nallaNeram'] ?? []), static function ($w) { return trim((string) $w) !== ''; }));
            if ($nalla !== []) {
                $bubbles[] = self::t($lang, [
                    'en' => 'Nalla Neram (auspicious window):',
                    'ta' => 'நல்ல நேரம்:',
                    'hi' => 'नल्ल नेरम (शुभ समय):',
                ]) . "\n" . implode("\n", array_map(static function ($w) { return '• ' . $w; }, $nalla));
            }
            return $bubbles;
        }

        if ($topic === 'why') {
            $reasons = self::pick($day['reasons'] ?? '', $lang);
            return [
                $who . self::t($lang, [
                    'en' => 'why your report marks this date auspicious:',
                    'ta' => 'உங்கள் அறிக்கை இந்த நாளை ஏன் சுபமாகக் குறிக்கிறது:',
                    'hi' => 'आपकी रिपोर्ट इस तिथि को शुभ क्यों बताती है:',
                ]) . "\n" . $dayLine . ($reasons !== '' ? "\n" . $reasons : ''),
                self::t($lang, [
                    'en' => 'Every date in your report carries its own star, tithi and window - open the calendar page to compare them side by side.',
                    'ta' => 'உங்கள் அறிக்கையில் ஒவ்வொரு நாளும் அதன் நட்சத்திரம், திதி மற்றும் நேரத்துடன் உள்ளது - அவற்றை ஒப்பிட காலண்டர் பக்கத்தைத் திறக்கவும்.',
                    'hi' => 'आपकी रिपोर्ट में हर तिथि के साथ उसका नक्षत्र, तिथि और समय है - उनकी तुलना के लिए कैलेंडर पृष्ठ खोलें।',
                ]),
            ];
        }

        // avoid — the three inauspicious windows the report prints per date.
        $labels = [
            'rahuKalam' => ['en' => 'Rahu Kalam', 'ta' => 'இராகு காலம்', 'hi' => 'राहु काल'],
            'yamagandam' => ['en' => 'Yamagandam', 'ta' => 'எமகண்டம்', 'hi' => 'यमगण्ड'],
            'gulikai' => ['en' => 'Gulikai Kalam', 'ta' => 'குளிகை காலம்', 'hi' => 'गुलिक काल'],
        ];
        $lines = [];
        foreach (array_slice($recommended, 0, 4) as $d) {
            $windows = [];
            foreach ($labels as $key => $label) {
                $window = trim((string) ($d[$key] ?? ''));
                if ($window !== '') {
                    $windows[] = self::t($lang, $label) . ' ' . $window;
                }
            }
            if ($windows === []) {
                continue;
            }
            $lines[] = '• ' . self::prettyDate((string) ($d['date'] ?? '')) . ' — ' . implode(', ', $windows);
        }
        if ($lines === []) {
            return [self::t($lang, [
                'en' => 'Your report lists no avoidance window for these dates. The graded dates and their Nalla Neram windows are on the calendar page.',
                'ta' => 'இந்த நாட்களுக்கு தவிர்க்க வேண்டிய நேரம் உங்கள் அறிக்கையில் இல்லை. தரம் பிரிக்கப்பட்ட நாட்களும் அவற்றின் நல்ல நேரங்களும் காலண்டர் பக்கத்தில் உள்ளன.',
                'hi' => 'इन तिथियों के लिए आपकी रिपोर्ट में कोई वर्जित समय नहीं है। ग्रेड की गई तिथियाँ और उनके शुभ समय कैलेंडर पृष्ठ पर हैं।',
            ])];
        }
        return [
            $who . self::t($lang, [
                'en' => 'the windows your report marks to avoid on the recommended dates:',
                'ta' => 'பரிந்துரைக்கப்பட்ட நாட்களில் தவிர்க்க வேண்டிய நேரங்கள்:',
                'hi' => 'अनुशंसित तिथियों पर जिन समयों से बचना है:',
            ]) . "\n" . implode("\n", $lines),
            self::t($lang, [
                'en' => 'These are the traditional inauspicious windows; the auspicious Nalla Neram windows are listed beside each date in your report.',
                'ta' => 'இவை மரபான அசுப நேரங்கள்; சுபமான நல்ல நேரங்கள் உங்கள் அறிக்கையில் ஒவ்வொரு நாளுக்கும் அருகில் உள்ளன.',
                'hi' => 'ये पारंपरिक अशुभ समय हैं; शुभ नल्ल नेरम समय आपकी रिपोर्ट में हर तिथि के साथ दिए गए हैं।',
            ]),
        ];
    }

    /** The temple guidance behind the "Which temple should I visit?" option. */
    private static function templeText(string $lang): string
    {
        $reg = json_decode((string) file_get_contents(self::kbFile('/knowledge/ai-astrologer/rules/remedies.json')), true) ?: [];
        $offer = '';
        foreach (($reg['universal'] ?? []) as $u) {
            if (($u['id'] ?? '') === 'navagraha-sthalam') {
                $offer = (string) ($u['offer'] ?? '');
                break;
            }
        }
        if ($offer === '') {
            return '';
        }
        return self::t($lang, [
            'en' => 'Temple guidance:',
            'ta' => 'கோயில் வழிகாட்டல்:',
            'hi' => 'मंदिर मार्गदर्शन:',
        ]) . "\n" . $offer;
    }

    /**
     * Fixed acknowledgement for complaint options. Complaints are never
     * answered by rules — the endpoint has already queued the message for
     * the human team before this text is shown.
     */
    private static function complaintAck(string $lang): string
    {
        return self::t($lang, [
            'en' => 'Thank you — your message has been sent to our team. They will contact you shortly. The question list below is still here if you need anything else.',
            'ta' => 'நன்றி — உங்கள் செய்தி எங்கள் குழுவுக்கு அனுப்பப்பட்டுள்ளது. அவர்கள் விரைவில் தொடர்பு கொள்வார்கள். வேறு ஏதேனும் தேவையென்றால் கீழே உள்ள கேள்விப் பட்டியல் இங்கேயே உள்ளது.',
            'hi' => 'धन्यवाद — आपका संदेश हमारी टीम को भेज दिया गया है। वे जल्द ही संपर्क करेंगे। और कुछ चाहिए तो नीचे प्रश्न-सूची यहीं है।',
        ]);
    }

    /** Re-runs retrieval scoped to one area (used when only an extra phrase matched). */
    private static function retrieveArea(string $areaId, string $question, string $lang, ?array $chart): array
    {
        $kb = json_decode((string) file_get_contents(self::kbFile('/knowledge/ai-astrologer/rules/life-areas.json')), true) ?: [];
        foreach (($kb['areas'] ?? []) as $area) {
            if (($area['id'] ?? '') !== $areaId) {
                continue;
            }
            $rules = [];
            $sources = [];
            foreach (($area['rules'] ?? []) as $rule) {
                if (!AstroAiProvider::evaluateCondition($rule['condition'] ?? [], $chart, $question)) {
                    continue;
                }
                $labels = [];
                foreach (($rule['source'] ?? []) as $s) {
                    if (($s['level'] ?? 'book') !== 'suppressed') {
                        $labels[] = AstroAiProvider::formatCitation($s, $lang);
                    }
                }
                $rules[] = [
                    'id' => $rule['id'],
                    'meaning' => $rule['meaning'][$lang] ?? ($rule['meaning']['en'] ?? ''),
                    'easing' => $rule['easing'] ?? '',
                    'practical' => $rule['practical'] ?? [],
                    'sources' => $labels,
                ];
                $sources = array_merge($sources, $labels);
            }
            $unique = array_values(array_unique($sources));
            return [
                'areaId' => $areaId,
                'cardTitle' => $area['cardTitle'][$lang] ?? ($area['cardTitle']['en'] ?? $areaId),
                'rules' => $rules,
                'sourceLine' => $unique ? 'Source: ' . implode(' · ', array_slice($unique, 0, 3)) : '',
                'refusal' => null,
            ];
        }
        return ['areaId' => $areaId, 'cardTitle' => $areaId, 'rules' => [], 'sourceLine' => '', 'refusal' => null];
    }

    private static function kbFile(string $rel): string
    {
        foreach ([dirname(__DIR__, 2) . $rel, dirname(__DIR__) . $rel] as $candidate) {
            if (is_file($candidate)) {
                return $candidate;
            }
        }
        return dirname(__DIR__, 2) . $rel;
    }

    // ------------------------------------------------------------------
    // Chart-derived lines
    // ------------------------------------------------------------------

    private static function summaryText(array $chart, string $areaId, string $lang): string
    {
        $prefix = self::SUMMARY_KEYS[$areaId] ?? null;
        if ($prefix === null) {
            return '';
        }
        $suffix = $lang === 'ta' ? 'Ta' : ($lang === 'hi' ? 'Hi' : 'En');
        $text = trim((string) ($chart['summary'][$prefix . $suffix] ?? ''));
        if ($text === '' && $suffix !== 'En') {
            $text = trim((string) ($chart['summary'][$prefix . 'En'] ?? ''));
        }
        return $text;
    }

    private static function periodLine(?array $chart, string $lang): string
    {
        if ($chart === null) {
            return '';
        }
        $labels = $chart['labels'] ?? [];
        $maha = (string) ($labels['dasha'][$lang] ?? ($chart['currentDasha'] ?? ''));
        $bhukti = (string) ($labels['bhukti'][$lang] ?? ($chart['currentAntardasha'] ?? ''));
        $end = (string) ($chart['dashaEndDate'] ?? '');
        if ($maha === '') {
            return '';
        }
        if ($lang === 'ta') {
            return 'நீங்கள் தற்போது ' . $maha . ' மகாதசை' . ($bhukti !== '' ? ', ' . $bhukti . ' புக்தியில்' : 'யில்') . ' இருக்கிறீர்கள்'
                . ($end !== '' ? '; இந்த புக்தி ' . $end . ' வரை நீடிக்கும்.' : '.');
        }
        if ($lang === 'hi') {
            return 'आप अभी ' . $maha . ' महादशा' . ($bhukti !== '' ? ' और ' . $bhukti . ' भुक्ति' : '') . ' में हैं'
                . ($end !== '' ? '; यह भुक्ति ' . $end . ' तक चलेगी।' : '।');
        }
        return 'You are now in ' . $maha . ' Mahadasha' . ($bhukti !== '' ? ' with ' . $bhukti . ' Bhukti' : '')
            . ($end !== '' ? ', which runs until ' . $end . '.' : '.');
    }

    private static function starLine(array $chart, string $lang): string
    {
        $labels = $chart['labels'] ?? [];
        $star = (string) ($labels['nakshatra'][$lang] ?? ($chart['moonNakshatra'] ?? ''));
        $rasi = (string) ($labels['rasi'][$lang] ?? ($chart['moonSign'] ?? ''));
        $lagna = (string) ($labels['lagna'][$lang] ?? ($chart['lagna'] ?? ''));
        if ($star === '' && $rasi === '' && $lagna === '') {
            return '';
        }
        if ($lang === 'ta') {
            return 'உங்கள் லக்னம் ' . $lagna . ', ராசி ' . $rasi . ', நட்சத்திரம் ' . $star . '.';
        }
        if ($lang === 'hi') {
            return 'आपका लग्न ' . $lagna . ', राशि ' . $rasi . ' और नक्षत्र ' . $star . ' है।';
        }
        return 'Your Lagna is ' . $lagna . ', your Moon sign (Rasi) is ' . $rasi . ' and your birth star is ' . $star . '.';
    }

    /** Rule-vocabulary graha of the running Mahadasha, if a chart is attached. */
    private static function dashaPlanet(?array $chart): ?string
    {
        $p = (string) ($chart['currentDasha'] ?? '');
        return $p !== '' && isset(self::PLANET_NAMES[$p]) ? $p : null;
    }

    // ------------------------------------------------------------------
    // Remedies
    // ------------------------------------------------------------------

    private static function remedyText(?string $planet, string $lang): string
    {
        $reg = json_decode((string) file_get_contents(self::kbFile('/knowledge/ai-astrologer/rules/remedies.json')), true) ?: [];
        if ($planet !== null) {
            foreach (($reg['grahas'] ?? []) as $g) {
                if (($g['graha'] ?? '') !== $planet) {
                    continue;
                }
                $label = $lang === 'ta' ? (string) ($g['tamil'] ?? $planet) . ' (' . $planet . ')'
                    : ($lang === 'hi' ? (string) ($g['hindi'] ?? $planet) . ' (' . $planet . ')' : $planet);
                $l = self::t($lang, [
                    'en' => ['Simple remedies for ', 'Day: ', 'Prayer: ', 'Charity: ', 'Temple: '],
                    'ta' => [' - எளிய பரிகாரங்கள்', 'கிழமை: ', 'வழிபாடு: ', 'தானம்: ', 'கோயில்: '],
                    'hi' => [' - सरल उपाय', 'दिन: ', 'प्रार्थना: ', 'दान: ', 'मंदिर: '],
                ]);
                $head = $lang === 'en' ? $l[0] . $label . ':' : $label . $l[0] . ':';
                return $head
                    . "\n• " . $l[1] . ($g['weekday'] ?? '')
                    . "\n• " . $l[2] . ($g['mantra']['simple'] ?? '')
                    . "\n• " . $l[3] . ($g['charity'] ?? '')
                    . "\n• " . $l[4] . ($g['temple']['name'] ?? '')
                    . "\n" . self::t($lang, [
                        'en' => 'Do what you can with devotion - no costly ritual is needed.',
                        'ta' => 'உங்களால் முடிந்ததை பக்தியுடன் செய்யுங்கள் - செலவான சடங்குகள் தேவையில்லை.',
                        'hi' => 'जो संभव हो, श्रद्धा से करें - महंगे अनुष्ठान की आवश्यकता नहीं है।',
                    ]);
            }
        }
        $lines = [];
        foreach (($reg['universal'] ?? []) as $u) {
            $lines[] = '• ' . ($u['offer'] ?? '');
        }
        return self::t($lang, [
            'en' => 'Simple remedies our texts recommend for everyone:',
            'ta' => 'எல்லோருக்கும் எங்கள் நூல்கள் பரிந்துரைக்கும் எளிய பரிகாரங்கள்:',
            'hi' => 'हमारे ग्रंथ सबके लिए ये सरल उपाय बताते हैं:',
        ]) . "\n" . implode("\n", array_slice($lines, 0, 3));
    }

    private static function remedySourceLine(?string $planet): string
    {
        $reg = json_decode((string) file_get_contents(self::kbFile('/knowledge/ai-astrologer/rules/remedies.json')), true) ?: [];
        $ids = [];
        foreach (($reg['grahas'] ?? []) as $g) {
            if ($planet !== null && ($g['graha'] ?? '') === $planet) {
                foreach (($g['source'] ?? []) as $s) {
                    $ids[] = (string) ($s['id'] ?? '');
                }
            }
        }
        $ids = array_values(array_filter(array_unique($ids), [AstroAiProvider::class, 'isCitableId']));
        return $ids ? 'Source: ' . implode(' · ', array_slice($ids, 0, 3)) : '';
    }

    // ------------------------------------------------------------------
    // Fixed texts
    // ------------------------------------------------------------------

    private static function refusalText(string $route, string $routeText, string $lang): string
    {
        $isLegal = $route === 'decline-with-referral' && stripos($routeText, 'legal') !== false;
        $key = $isLegal ? 'legal' : $route;
        $texts = [
            'legal' => [
                'en' => 'Astrology cannot replace legal advice. For a court case or any legal matter, please speak to a qualified lawyer. If you like, I can explain the general nature of your current Dasha period instead.',
                'ta' => 'ஜோதிடம் சட்ட ஆலோசனைக்கு மாற்றாகாது. நீதிமன்ற வழக்கு அல்லது சட்ட விஷயங்களுக்கு தகுதியான வழக்கறிஞரை அணுகவும். விரும்பினால், உங்கள் தற்போதைய தசா காலத்தின் பொதுவான தன்மையை விளக்குகிறேன்.',
                'hi' => 'ज्योतिष कानूनी सलाह का विकल्प नहीं है। अदालत के मामले या किसी कानूनी विषय के लिए कृपया किसी योग्य वकील से मिलें। चाहें तो मैं आपकी वर्तमान दशा का सामान्य स्वरूप समझा सकता हूँ।',
            ],
            'decline-with-referral' => [
                'en' => 'I cannot give investment or trading advice. Please speak to a registered financial adviser before any investment. If you like, I can tell you what your chart says about wealth in general.',
                'ta' => 'முதலீடு அல்லது பங்கு வர்த்தக ஆலோசனை என்னால் வழங்க இயலாது. எந்த முதலீட்டிற்கும் முன் பதிவு பெற்ற நிதி ஆலோசகரை அணுகவும். விரும்பினால், உங்கள் ஜாதகத்தில் பொதுவான தன நிலையை சொல்கிறேன்.',
                'hi' => 'मैं निवेश या ट्रेडिंग की सलाह नहीं दे सकता। किसी भी निवेश से पहले पंजीकृत वित्तीय सलाहकार से मिलें। चाहें तो मैं बता सकता हूँ कि आपकी कुंडली धन के बारे में सामान्य रूप से क्या कहती है।',
            ],
            'health-guardrail' => [
                'en' => 'I cannot suggest any medicine, tablet or dose. Please follow the advice of a qualified doctor. I can share what your chart says about general well-being and simple routines, if that helps.',
                'ta' => 'எந்த மருந்தையோ மாத்திரையையோ அளவையோ என்னால் பரிந்துரைக்க இயலாது. தயவுசெய்து தகுதியான மருத்துவர் ஆலோசனையை பின்பற்றவும். விரும்பினால், உங்கள் ஜாதகப்படி பொதுவான நல்வாழ்வு பற்றி சொல்கிறேன்.',
                'hi' => 'मैं कोई दवा, गोली या खुराक नहीं बता सकता। कृपया योग्य डॉक्टर की सलाह मानें। चाहें तो मैं आपकी कुंडली के अनुसार सामान्य स्वास्थ्य-दिनचर्या के बारे में बता सकता हूँ।',
            ],
            'refuse-prediction' => [
                'en' => 'This is not something astrology should predict, and I will not try. What I can do is explain your current period and the simple remedies for it - or you can tap "Talk to our astrologer" and speak to our astrologer personally.',
                'ta' => 'இதை ஜோதிடம் கணிக்கக் கூடாது; நானும் முயற்சிக்க மாட்டேன். உங்கள் தற்போதைய காலத்தையும் அதற்கான எளிய பரிகாரங்களையும் விளக்க முடியும் - அல்லது "எங்கள் ஜோதிடருடன் பேசுங்கள்" என்பதை அழுத்தி எங்கள் ஜோதிடரிடம் நேரடியாக பேசலாம்.',
                'hi' => 'यह ऐसी बात नहीं है जिसकी भविष्यवाणी ज्योतिष को करनी चाहिए, और मैं ऐसा नहीं करूँगा। मैं आपकी वर्तमान अवधि और उसके सरल उपाय समझा सकता हूँ - या "हमारे ज्योतिषी से बात करें" दबाकर सीधे हमारे ज्योतिषी से बात करें।',
            ],
            'decline-respectfully' => [
                'en' => 'I cannot confirm or deny such things. The ordinary practices our texts recommend are a temple visit, daily japa and a small act of charity. If you feel troubled again and again, please tap "Talk to our astrologer".',
                'ta' => 'இது போன்றவற்றை உறுதிப்படுத்தவோ மறுக்கவோ என்னால் இயலாது. கோயில் தரிசனம், தினசரி ஜபம், சிறு தானம் ஆகியவையே எங்கள் நூல்கள் சொல்லும் எளிய வழிகள். தொடர்ந்து மன வருத்தம் இருந்தால் "எங்கள் ஜோதிடருடன் பேசுங்கள்" என்பதை அழுத்தவும்.',
                'hi' => 'मैं ऐसी बातों की पुष्टि या खंडन नहीं कर सकता। हमारे ग्रंथ सामान्य उपाय बताते हैं - मंदिर दर्शन, नित्य जप और थोड़ा दान। यदि बार-बार परेशानी हो, तो कृपया "हमारे ज्योतिषी से बात करें" दबाएँ।',
            ],
            'no-sales' => [
                'en' => 'Prices for all reports are shown on the Services page and at checkout in your dashboard. I am here for astrology questions - ask me anything about your chart.',
                'ta' => 'அனைத்து அறிக்கைகளின் விலையும் சேவைகள் பக்கத்திலும் உங்கள் டாஷ்போர்டில் செக்அவுட்டிலும் காட்டப்படும். ஜோதிட கேள்விகளுக்காக நான் இங்கே இருக்கிறேன் - உங்கள் ஜாதகம் பற்றி எதையும் கேளுங்கள்.',
                'hi' => 'सभी रिपोर्ट की कीमतें सेवाएँ पेज पर और आपके डैशबोर्ड के चेकआउट में दिखाई जाती हैं। मैं ज्योतिष प्रश्नों के लिए हूँ - अपनी कुंडली के बारे में कुछ भी पूछें।',
            ],
        ];
        return $texts[$key][$lang] ?? ($texts['refuse-prediction'][$lang]);
    }

    private static function generalAreaText(string $areaId, string $lang): string
    {
        $texts = [
            'health' => [
                'en' => 'Health is read mainly from the 1st house (Lagna) and its lord, which stand for the body and vitality, with the 6th house for minor ailments and recovery, and the 8th and 12th houses for long treatment and rest. The Moon shows the mind and sleep.',
                'ta' => 'உடல்நலம் முக்கியமாக 1-ஆம் வீடு (லக்னம்) மற்றும் லக்னாதிபதியால் பார்க்கப்படுகிறது - இவை உடலையும் உயிர்சக்தியையும் குறிக்கும். 6-ஆம் வீடு சிறு தொந்தரவுகளையும் குணமாவதையும், 8, 12-ஆம் வீடுகள் நீண்ட சிகிச்சையையும் ஓய்வையும் காட்டும். சந்திரன் மனதையும் தூக்கத்தையும் குறிக்கும்.',
                'hi' => 'स्वास्थ्य मुख्य रूप से पहले भाव (लग्न) और लग्नेश से देखा जाता है, जो शरीर और जीवन-शक्ति के कारक हैं। छठा भाव छोटी शिकायतें और स्वास्थ्य-लाभ, तथा आठवाँ और बारहवाँ भाव लंबा उपचार और विश्राम दिखाते हैं। चंद्रमा मन और नींद का कारक है।',
            ],
            'wealth' => [
                'en' => 'Wealth is read from the 2nd house (savings, family wealth and speech) and the 11th house (income and gains), with their lords. A link between these houses and the 6th, 8th or 12th shows expense or delay. Guru (Jupiter) is the natural significator of wealth.',
                'ta' => 'செல்வம் 2-ஆம் வீடு (சேமிப்பு, குடும்ப சொத்து, வாக்கு) மற்றும் 11-ஆம் வீடு (வருமானம், லாபம்), அவற்றின் அதிபதிகளால் பார்க்கப்படுகிறது. இவை 6, 8, 12-ஆம் வீடுகளுடன் தொடர்புடையால் செலவு அல்லது தாமதம் காட்டும். குரு செல்வத்தின் இயற்கை காரகர்.',
                'hi' => 'धन दूसरे भाव (बचत, पारिवारिक धन, वाणी) और ग्यारहवें भाव (आय और लाभ) तथा उनके स्वामियों से देखा जाता है। इनका छठे, आठवें या बारहवें भाव से संबंध खर्च या देरी दिखाता है। गुरु धन के नैसर्गिक कारक हैं।',
            ],
            'education' => [
                'en' => 'Education is read from the 5th house (learning, memory and intelligence) and its lord, from Budha (Mercury) for study and speech, and from the 9th house for higher study and teachers. The periods of Budha, Guru and Sukra are traditionally treated as supportive for exams.',
                'ta' => 'கல்வி 5-ஆம் வீடு (அறிவு, நினைவாற்றல்) மற்றும் அதன் அதிபதி, படிப்பு மற்றும் வாக்கிற்கு புதன், உயர்கல்வி மற்றும் ஆசிரியருக்கு 9-ஆம் வீடு ஆகியவற்றால் பார்க்கப்படுகிறது. புதன், குரு, சுக்கிரன் காலங்கள் தேர்வுகளுக்கு சாதகமாக கருதப்படுகின்றன.',
                'hi' => 'शिक्षा पाँचवें भाव (विद्या, स्मृति, बुद्धि) और उसके स्वामी, पढ़ाई व वाणी के लिए बुध, तथा उच्च शिक्षा और गुरु के लिए नवें भाव से देखी जाती है। बुध, गुरु और शुक्र की दशाएँ परीक्षा के लिए परंपरागत रूप से सहायक मानी जाती हैं।',
            ],
            'career' => [
                'en' => 'Career is read from the 10th house (profession and public standing) and its lord. The 7th house shows business and partners, and Sani (Saturn) shows steady, hard-earned work. The running Dasha and Bhukti show when change is favoured.',
                'ta' => 'தொழில் 10-ஆம் வீடு (உத்தியோகம், சமூக அந்தஸ்து) மற்றும் அதன் அதிபதியால் பார்க்கப்படுகிறது. 7-ஆம் வீடு வியாபாரம், கூட்டாளிகளை காட்டும்; சனி நிலையான உழைப்பை குறிக்கும். நடப்பு தசை, புக்தி மாற்றத்திற்கு சாதகமான காலத்தை காட்டும்.',
                'hi' => 'करियर दसवें भाव (व्यवसाय और प्रतिष्ठा) और उसके स्वामी से देखा जाता है। सातवाँ भाव व्यापार और साझेदार दिखाता है, और शनि स्थिर, परिश्रम से मिला काम। चल रही दशा और भुक्ति बताती है कि बदलाव कब अनुकूल है।',
            ],
            'marriage' => [
                'en' => 'Marriage is read from the 7th house (spouse and partnership) and its lord, with Sukra (Venus) as the significator of marriage, and Guru (Jupiter). Sevvai (Kuja) dosha is checked from the Lagna, Moon and Venus, and is always judged by matching both charts, never from one chart alone.',
                'ta' => 'திருமணம் 7-ஆம் வீடு (வாழ்க்கைத் துணை) மற்றும் அதன் அதிபதி, திருமண காரகர் சுக்கிரன், குரு ஆகியவற்றால் பார்க்கப்படுகிறது. செவ்வாய் தோஷம் லக்னம், சந்திரன், சுக்கிரனிலிருந்து பார்க்கப்படுகிறது; அது எப்போதும் இரு ஜாதகங்களையும் பொருத்திப் பார்த்தே முடிவு செய்யப்படும்.',
                'hi' => 'विवाह सातवें भाव (जीवनसाथी) और उसके स्वामी, विवाह के कारक शुक्र, और गुरु से देखा जाता है। मंगल (कुज) दोष लग्न, चंद्र और शुक्र से देखा जाता है, और हमेशा दोनों कुंडलियों के मिलान से ही आँका जाता है।',
            ],
            'property' => [
                'en' => 'Home, land and property are read from the 4th house and its lord, with the Moon for peace at home. Saturn, Rahu or Ketu in the 4th can show repeated moves or delays before settling.',
                'ta' => 'வீடு, நிலம், சொத்து 4-ஆம் வீடு மற்றும் அதன் அதிபதியால் பார்க்கப்படுகிறது; வீட்டு அமைதிக்கு சந்திரன். 4-ஆம் வீட்டில் சனி, ராகு அல்லது கேது இருந்தால் இடமாற்றங்கள் அல்லது நிலைபெற தாமதம் காட்டும்.',
                'hi' => 'घर, भूमि और संपत्ति चौथे भाव और उसके स्वामी से देखी जाती है, तथा घर की शांति के लिए चंद्रमा। चौथे भाव में शनि, राहु या केतु बार-बार स्थान-परिवर्तन या स्थिर होने में देरी दिखा सकते हैं।',
            ],
            'travel-foreign' => [
                'en' => 'Travel and fortune abroad are read from the 9th house (long journeys and fortune) and the 12th house (living away from the birthplace), with Rahu, which the classical texts link to foreign lands.',
                'ta' => 'பயணமும் வெளிநாட்டு அதிர்ஷ்டமும் 9-ஆம் வீடு (நீண்ட பயணம், பாக்கியம்), 12-ஆம் வீடு (பிறந்த இடத்தை விட்டு வாழ்வது), மற்றும் வெளிநாட்டுடன் தொடர்புடைய ராகு ஆகியவற்றால் பார்க்கப்படுகிறது.',
                'hi' => 'यात्रा और विदेश में भाग्य नवें भाव (लंबी यात्रा और भाग्य), बारहवें भाव (जन्मस्थान से दूर निवास) और राहु से देखे जाते हैं, जिसे शास्त्र विदेश से जोड़ते हैं।',
            ],
            'current-guidance' => [
                'en' => 'Your present phase of life is read from the Vimshottari Dasha system: the Mahadasha is the broad chapter of life you are in, and the Bhukti is the shorter section inside it. Saturn\'s transit from your Moon sign (including Sade Sati) adds the present-day layer.',
                'ta' => 'உங்கள் தற்போதைய வாழ்க்கை நிலை விம்சோத்தரி தசா முறையால் பார்க்கப்படுகிறது: மகாதசை வாழ்க்கையின் பெரிய அத்தியாயம், புக்தி அதற்குள் உள்ள சிறு பகுதி. உங்கள் ராசியிலிருந்து சனியின் கோசாரம் (ஏழரை சனி உட்பட) தற்போதைய நிலையை சேர்க்கும்.',
                'hi' => 'आपके जीवन का वर्तमान चरण विंशोत्तरी दशा पद्धति से देखा जाता है: महादशा जीवन का बड़ा अध्याय है और भुक्ति उसके भीतर का छोटा हिस्सा। आपकी चंद्र राशि से शनि का गोचर (साढ़े साती सहित) वर्तमान की परत जोड़ता है।',
            ],
        ];
        return $texts[$areaId][$lang] ?? ($texts[$areaId]['en'] ?? '');
    }

    private static function personalHint(string $lang): string
    {
        return self::t($lang, [
            'en' => 'For a reading of your own horoscope, open this chat from a completed report in My Dashboard - I can then answer from your own chart.',
            'ta' => 'உங்கள் சொந்த ஜாதகப் பலனுக்கு, என் டாஷ்போர்டில் முடிந்த அறிக்கையிலிருந்து இந்த உரையாடலைத் திறக்கவும் - அப்போது உங்கள் ஜாதகத்திலிருந்தே பதில் சொல்வேன்.',
            'hi' => 'अपनी कुंडली का फल जानने के लिए, मेरे डैशबोर्ड में किसी पूर्ण रिपोर्ट से यह चैट खोलें - तब मैं आपकी अपनी कुंडली से उत्तर दूँगा।',
        ]);
    }

    private static function doctorLine(string $lang): string
    {
        return self::t($lang, [
            'en' => 'This is an astrological indication only, not a diagnosis. For any health concern, please see a qualified doctor.',
            'ta' => 'இது ஜோதிட அறிகுறி மட்டுமே, நோய் கண்டறிதல் அல்ல. உடல்நலம் தொடர்பான எந்த கவலைக்கும் தகுதியான மருத்துவர் ஆலோசனையைப் பெறவும்.',
            'hi' => 'यह केवल ज्योतिषीय संकेत है, निदान नहीं। स्वास्थ्य की किसी भी चिंता के लिए कृपया योग्य डॉक्टर से मिलें।',
        ]);
    }

    private static function greeting(string $name, string $lang, bool $hasChart): string
    {
        $who = $name !== '' ? ' ' . $name : '';
        return self::t($lang, [
            'en' => 'Vanakkam' . $who . '! I am the ASTRO SIVAM astrology assistant. I answer from our own Tamil astrology sources'
                . ($hasChart ? ' and your horoscope.' : '.'),
            'ta' => 'வணக்கம்' . $who . '! நான் ASTRO SIVAM ஜோதிட உதவியாளர். எங்கள் சொந்த தமிழ் ஜோதிட நூல்களிலிருந்து'
                . ($hasChart ? ' உங்கள் ஜாதகத்தை வைத்து' : '') . ' பதில் சொல்கிறேன்.',
            'hi' => 'नमस्ते' . $who . '! मैं ASTRO SIVAM ज्योतिष सहायक हूँ। मैं हमारे अपने तमिल ज्योतिष स्रोतों'
                . ($hasChart ? ' और आपकी कुंडली' : '') . ' से उत्तर देता हूँ।',
        ]);
    }

    private static function topicsLine(string $lang): string
    {
        return self::t($lang, [
            'en' => 'You can ask me about: career, marriage, wealth, well-being, education, property, travel abroad, your current Dasha period, or remedies (pariharam). For example: "How is my career?"',
            'ta' => 'நீங்கள் கேட்கலாம்: தொழில், திருமணம், செல்வம், ஆரோக்கியம், கல்வி, சொத்து, வெளிநாட்டு பயணம், தற்போதைய தசை, அல்லது பரிகாரங்கள். உதாரணம்: "என் தொழில் எப்படி இருக்கும்?"',
            'hi' => 'आप पूछ सकते हैं: करियर, विवाह, धन, आरोग्य, शिक्षा, संपत्ति, विदेश यात्रा, वर्तमान दशा, या उपाय। उदाहरण: "मेरा करियर कैसा रहेगा?"',
        ]);
    }

    private static function noMatchText(string $lang): string
    {
        return self::t($lang, [
            'en' => 'I could not find this in our astrology sources, and I would rather not guess. You can tap "Talk to our astrologer" and our astrologer will reply to you personally.',
            'ta' => 'இதை எங்கள் ஜோதிட நூல்களில் என்னால் காண முடியவில்லை; ஊகித்து சொல்ல விரும்பவில்லை. "எங்கள் ஜோதிடருடன் பேசுங்கள்" என்பதை அழுத்தினால் எங்கள் ஜோதிடர் உங்களுக்கு நேரடியாக பதிலளிப்பார்.',
            'hi' => 'यह मुझे हमारे ज्योतिष स्रोतों में नहीं मिला, और मैं अनुमान नहीं लगाना चाहता। "हमारे ज्योतिषी से बात करें" दबाएँ, हमारे ज्योतिषी आपको स्वयं उत्तर देंगे।',
        ]);
    }

    // ------------------------------------------------------------------
    // Helpers
    // ------------------------------------------------------------------

    /** Picks the language entry from a {en,ta,hi} map. */
    private static function t(string $lang, array $map)
    {
        return $map[$lang] ?? $map['en'];
    }

    private static function containsAny(string $q, array $words): bool
    {
        foreach ($words as $w) {
            if (self::hasWord($q, (string) $w)) {
                return true;
            }
        }
        return false;
    }

    /**
     * Latin words match on word boundaries ("sun" must not match "sunday",
     * "uk" must not match "luck"); Tamil/Hindi match as substrings because
     * case endings attach to the word.
     */
    private static function hasWord(string $q, string $w): bool
    {
        $w = mb_strtolower(trim($w), 'UTF-8');
        if ($w === '') {
            return false;
        }
        if (preg_match('/^[a-z0-9 \']+$/', $w) === 1) {
            return preg_match('/(?<![a-z])' . preg_quote($w, '/') . '(?![a-z])/u', $q) === 1;
        }
        return mb_strpos($q, $w, 0, 'UTF-8') !== false;
    }

    /**
     * Small-talk replies (name, how are you, where from, thanks, bye, bot or human).
     * Returns [] when the question is not small talk, or is about an astrology area.
     */
    private static function smallTalkBubbles(string $q, string $lang): array
    {
        $q = str_replace(["\u{2019}", "\u{2018}"], "'", $q);
        if (mb_strlen($q, 'UTF-8') > 60) {
            return [];
        }
        foreach (self::SMALL_TALK_PHRASES as $id => $phrases) {
            if (self::containsAny($q, $phrases)) {
                // Remove the small-talk words first, then look for astrology words in
                // what is left: "thanks, what about my career" is astrology, while the
                // Hindi thanks word धन्यवाद only contains the wealth word धन.
                $rest = $q;
                foreach ($phrases as $phrase) {
                    $rest = str_replace(mb_strtolower($phrase, 'UTF-8'), ' ', $rest);
                }
                if (self::matchExtraArea($rest) !== null || self::containsAny($rest, self::REMEDY_WORDS)) {
                    return [];
                }
                $bubbles = [self::smallTalkText($id, $lang)];
                if ($id === 'help') {
                    $bubbles[] = self::topicsLine($lang);
                }
                return $bubbles;
            }
        }
        return [];
    }

    private static function smallTalkText(string $id, string $lang): string
    {
        $replies = [
            'nice' => [
                'en' => 'Nice to meet you too! How can I help with your astrology today?',
                'ta' => 'உங்களைச் சந்தித்ததில் மகிழ்ச்சி! இன்று ஜோதிடம் பற்றி எப்படி உதவட்டும்?',
                'hi' => 'आपसे मिलकर अच्छा लगा! आज ज्योतिष में किस बात में मदद करूँ?',
            ],
            'bye' => [
                'en' => 'Goodbye! Come back anytime you have a question.',
                'ta' => 'விடைபெறுகிறேன்! எப்போது வேண்டுமானாலும் மீண்டும் வாருங்கள்.',
                'hi' => 'अलविदा! जब भी कोई सवाल हो, फिर से आइए।',
            ],
            'thanks' => [
                'en' => 'You are welcome! Ask me anything else about your chart.',
                'ta' => 'நல்வரவு! உங்கள் ஜாதகம் பற்றி வேறு ஏதேனும் கேளுங்கள்.',
                'hi' => 'आपका स्वागत है! अपनी कुंडली के बारे में और कुछ पूछिए।',
            ],
            'wellbeing' => [
                'en' => 'I am doing well, thank you for asking! How can I help you with your astrology today?',
                'ta' => 'நான் நன்றாக இருக்கிறேன், கேட்டதற்கு நன்றி! இன்று உங்கள் ஜோதிடம் பற்றி எப்படி உதவட்டும்?',
                'hi' => 'मैं ठीक हूँ, पूछने के लिए धन्यवाद! आज आपकी ज्योतिष संबंधी किस बात में मदद करूँ?',
            ],
            'origin' => [
                'en' => 'I do not have a hometown. I am the ASTRO SIVAM astrology assistant, and I answer from ASTRO SIVAM\'s own Tamil astrology sources.',
                'ta' => 'எனக்கு சொந்த ஊர் இல்லை. நான் ASTRO SIVAM ஜோதிட உதவியாளர்; எங்கள் சொந்த தமிழ் ஜோதிட நூல்களிலிருந்து பதில் சொல்கிறேன்.',
                'hi' => 'मेरा कोई अपना शहर नहीं है। मैं ASTRO SIVAM का ज्योतिष सहायक हूँ और हमारे अपने तमिल ज्योतिष स्रोतों से उत्तर देता हूँ।',
            ],
            'name' => [
                'en' => 'I am the ASTRO SIVAM astrology assistant. Ask me anything about your chart.',
                'ta' => 'நான் ASTRO SIVAM ஜோதிட உதவியாளர். உங்கள் ஜாதகம் பற்றி எதையும் கேளுங்கள்.',
                'hi' => 'मैं ASTRO SIVAM का ज्योतिष सहायक हूँ। अपनी कुंडली के बारे में कुछ भी पूछिए।',
            ],
            'bot' => [
                'en' => 'I am an automated assistant, not a human. For a personal reply, tap "Talk to our astrologer".',
                'ta' => 'நான் ஒரு தானியங்கி உதவியாளர், மனிதர் அல்ல. தனிப்பட்ட பதில் வேண்டுமெனில் "எங்கள் ஜோதிடருடன் பேசுங்கள்" என்பதை அழுத்துங்கள்.',
                'hi' => 'मैं एक स्वचालित सहायक हूँ, इंसान नहीं। व्यक्तिगत उत्तर के लिए "हमारे ज्योतिषी से बात करें" दबाएँ।',
            ],
            'age' => [
                'en' => 'I do not have an age, I am an automated assistant. How can I help with your chart today?',
                'ta' => 'எனக்கு வயது இல்லை - நான் ஒரு தானியங்கி உதவியாளர். இன்று உங்கள் ஜாதகத்தில் எப்படி உதவட்டும்?',
                'hi' => 'मेरी कोई उम्र नहीं है, मैं एक स्वचालित सहायक हूँ। आज कुंडली में किस बात में मदद करूँ?',
            ],
            'help' => [
                'en' => 'I can answer questions about your chart and the topics below.',
                'ta' => 'உங்கள் ஜாதகம் மற்றும் கீழே உள்ள தலைப்புகள் பற்றி பதில் சொல்ல முடியும்.',
                'hi' => 'मैं आपकी कुंडली और नीचे दिए विषयों के बारे में उत्तर दे सकता हूँ।',
            ],
        ];
        return self::t($lang, $replies[$id]);
    }

    private static function isGreeting(string $q): bool
    {
        if (mb_strlen($q, 'UTF-8') > 30) {
            return false;
        }
        return self::containsAny($q, self::GREETING_WORDS) && self::matchExtraArea($q) === null
            && !self::containsAny($q, self::REMEDY_WORDS);
    }

    private static function areaPhrases(): array
    {
        static $phrases = null;
        if ($phrases !== null) {
            return $phrases;
        }
        $phrases = self::EXTRA_PHRASES;
        $kb = json_decode((string) file_get_contents(self::kbFile('/knowledge/ai-astrologer/rules/life-areas.json')), true) ?: [];
        foreach (($kb['areas'] ?? []) as $area) {
            $id = (string) ($area['id'] ?? '');
            foreach (($area['customerPhrases'] ?? []) as $list) {
                foreach ((array) $list as $p) {
                    $phrases[$id][] = (string) $p;
                }
            }
        }
        foreach ($phrases as $id => $list) {
            $phrases[$id] = array_values(array_unique($list));
        }
        return $phrases;
    }

    private static function matchExtraArea(string $q): ?string
    {
        $best = null;
        $bestScore = 0;
        $generic = 0;
        foreach (self::areaPhrases() as $areaId => $words) {
            $score = 0;
            foreach ($words as $w) {
                if (self::hasWord($q, $w)) {
                    $score += mb_strlen($w, 'UTF-8');
                }
            }
            // current-guidance is the generic fallback; any specific area wins over it.
            if ($areaId === 'current-guidance') {
                $generic = $score;
                continue;
            }
            if ($score > $bestScore) {
                $best = $areaId;
                $bestScore = $score;
            }
        }
        // A question about the period itself ("what is my current dasha")
        // stays with current-guidance even if it also names an area word;
        // a soft word like "this year" does not outrank a specific area.
        if ($best === null) {
            return $generic > 0 ? 'current-guidance' : null;
        }
        return self::containsAny($q, self::PERIOD_WORDS) ? 'current-guidance' : $best;
    }

    private static function mentionedPlanet(string $q): ?string
    {
        foreach (self::PLANET_NAMES as $graha => $names) {
            foreach ($names as $n) {
                if (self::hasWord($q, $n)) {
                    return $graha;
                }
            }
        }
        return null;
    }

    /**
     * Caps the bubbles at four, puts the source line on the last one, and runs
     * the same output guard on every local reply. A health word without a doctor
     * line gets the doctor line; anything else that fails ships the safe
     * fallback and offers the astrologer.
     */
    private static function finish(array $bubbles, string $sourceLine, ?string $areaId, bool $handoff, string $lang): array
    {
        $bubbles = array_values(array_filter(array_map('trim', $bubbles), static function ($b) {
            return $b !== '';
        }));
        if (count($bubbles) > 4) {
            $head = array_slice($bubbles, 0, 3);
            $head[] = implode("\n\n", array_slice($bubbles, 3));
            $bubbles = $head;
        }

        $check = AstroAiProvider::checkReply(implode("\n\n", $bubbles), $lang);
        if (!$check['ok'] && $check['violations'] === ['health topic without advising a qualified doctor']) {
            $bubbles[] = self::doctorLine($lang);
            $check = AstroAiProvider::checkReply(implode("\n\n", $bubbles), $lang);
        }
        if (!$check['ok']) {
            error_log('AI Astrologer (knowledge-base mode) guard rejected a reply: ' . implode('; ', $check['violations']));
            $fallback = AstroAiProvider::fallbackReply($lang);
            return ['content' => $fallback, 'bubbles' => [$fallback], 'sourceLine' => '',
                'areaId' => $areaId, 'handoff' => true, 'mode' => 'knowledge-base'];
        }

        if ($sourceLine !== '') {
            $bubbles[count($bubbles) - 1] .= "\n" . $sourceLine;
        }
        return [
            'content' => implode("\n\n", $bubbles),
            'bubbles' => $bubbles,
            'sourceLine' => $sourceLine,
            'areaId' => $areaId,
            'handoff' => $handoff,
            'mode' => 'knowledge-base',
        ];
    }
}
