/**
 * AUTO-GENERATED FILE — DO NOT EDIT BY HAND.
 *
 * Source of truth : data/namakaran_name_bank.tsv
 * Generator       : scripts/build_namakaran_bank.mjs
 * Content hash    : c15e1c5ff9dec371
 *
 * The same hash is written into api/astrology/namakaran_name_bank.php so the
 * live preview, the browser-side TypeScript and the official mPDF report can be proven to
 * show an identical name bank.
 */

export const NAMAKARAN_BANK_HASH = 'c15e1c5ff9dec371';

/** Page 2 of the Namakaran report shows at most this many names per side. */
export const NAMAKARAN_MAX_PER_SIDE = 8;

export type NamakaranNameStyle = 'south' | 'north';
export type NamakaranGender = 'M' | 'F';

export interface NamakaranBankEntry {
  /** Name in Roman script. */
  n: string;
  /** Short meaning. */
  m: string;
}

export interface NamakaranBankColumn {
  south: NamakaranBankEntry[];
  north: NamakaranBankEntry[];
}

export interface NamakaranBankAkshara {
  M: NamakaranBankColumn;
  F: NamakaranBankColumn;
}

/**
 * Keyed by the pada akshara (Tamil) of the birth star. Aksharas that share a
 * Tamil letter share one list on purpose: Tamil does not distinguish the
 * voiced/voiceless readings (ச = cha/sa, க = ka/ga ...), so one list serves
 * every pada that prints that letter.
 */
export const NAMAKARAN_BANK: Record<string, NamakaranBankAkshara> = {
  "சு": { M: { south: [{n:"Sudhan",m:"Wealth and virtue"},{n:"Suresh",m:"Lord of the celestials"},{n:"Sutharsan",m:"Handsome and virtuous"},{n:"Suganthan",m:"Fragrant, pleasing"},{n:"Sundaram",m:"Beautiful, auspicious"},{n:"Subramanian",m:"Fond of the divine"},{n:"Suriyan",m:"The Sun god"},{n:"Sureshkumar",m:"Lord of the celestials"},{n:"Sukkinan",m:"Noble and gentle"},{n:"Sudharshan",m:"Beautiful vision"}], north: [{n:"Sumer",m:"Very bright"},{n:"Sunil",m:"Deep blue, sapphire"},{n:"Sudhir",m:"Resolute and wise"},{n:"Sumit",m:"Good friend"},{n:"Sushant",m:"Calm and peaceful"},{n:"Suyash",m:"Success and fame"},{n:"Suhas",m:"Pleasant smile"},{n:"Sukrit",m:"Wise and virtuous"},{n:"Suryansh",m:"Part of the Sun"},{n:"Sumedh",m:"Wise and intelligent"},{n:"Shubh",m:"Auspicious"}] }, F: { south: [{n:"Suganya",m:"Sweet-natured"},{n:"Sudha",m:"Nectar, divine calm"},{n:"Sumathi",m:"Pure and wise mind"},{n:"Sundari",m:"Beautiful woman"},{n:"Sujatha",m:"Well-born, noble"},{n:"Sukirtha",m:"Good fame, auspicious"},{n:"Supriya",m:"Very dear"},{n:"Sunitha",m:"One with good conduct"},{n:"Suvetha",m:"Bright and fair"},{n:"Subiksha",m:"Prosperity and grace"},{n:"Suthanthira",m:"Freedom, liberty"}], north: [{n:"Suman",m:"Good-natured, calm"},{n:"Sunita",m:"Well-mannered"},{n:"Sushma",m:"Beautiful, good nature"},{n:"Surbhi",m:"Fragrance"},{n:"Suhani",m:"Pleasant and beautiful"},{n:"Sukriti",m:"Good deed, noble act"},{n:"Sudiksha",m:"Auspicious dedication"},{n:"Sumedha",m:"Wise, intelligent woman"},{n:"Suryanshi",m:"Ray of the Sun"},{n:"Sulekha",m:"Good writing, eloquent"},{n:"Sunanda",m:"Very pleasing, charming"}] } },
  "சே": { M: { south: [{n:"Senthil",m:"Lord Murugan, radiant"},{n:"Selvan",m:"Prosperous young man"},{n:"Selvam",m:"Wealth and prosperity"},{n:"Sekaran",m:"Lord Shiva"},{n:"Sethupathi",m:"Master of the bridge"},{n:"Senthilvelan",m:"Spear of Lord Murugan"},{n:"Selvakumar",m:"Prosperous prince"},{n:"Sekar",m:"Auspicious crest"},{n:"Senthamilan",m:"Sweet Tamil"},{n:"Sedhuraman",m:"Lord Rama of the bridge"}], north: [{n:"Sekhar",m:"Crest, Lord Shiva"},{n:"Seshnath",m:"Lord of serpents"},{n:"Seshadri",m:"Lord of the serpent hill"},{n:"Setu",m:"Sacred bridge"},{n:"Chetan",m:"Alive, conscious"}] }, F: { south: [{n:"Seetha",m:"Furrow, pure"},{n:"Selvi",m:"Respected lady"},{n:"Selvarani",m:"Prosperous queen"},{n:"Seethalakshmi",m:"Goddess Lakshmi"},{n:"Senthamarai",m:"Red lotus"},{n:"Selvarasi",m:"Queen of prosperity"},{n:"Sembaruthi",m:"Red hibiscus flower"}], north: [{n:"Sejal",m:"River water, pure"},{n:"Seerat",m:"Inner virtue"},{n:"Sehaj",m:"Natural, effortless"},{n:"Seemanti",m:"Lovely parting of hair"},{n:"Sevanti",m:"A white chrysanthemum"}] } },
  "சோ": { M: { south: [{n:"Somasundaram",m:"Lord Shiva, beautiful"},{n:"Chozhan",m:"Ancient Chola king"},{n:"Somanathan",m:"Lord of the moon"},{n:"Chokkalingam",m:"Lord of the thousand forms"},{n:"Somasundar",m:"Handsome as the moon"},{n:"Solaippan",m:"Lord of the groves"},{n:"Chozharasan",m:"Chola king"}], north: [{n:"Somesh",m:"Lord of the moon"},{n:"Sohan",m:"Pleasant and charming"},{n:"Somnath",m:"Lord of the moon"},{n:"Soham",m:"Divine realization"},{n:"Sohit",m:"Handsome and virtuous"},{n:"Someshwar",m:"Lord of the moon"}] }, F: { south: [{n:"Sobana",m:"Radiant and beautiful"},{n:"Sobanambika",m:"Goddess of radiance"},{n:"Sornambika",m:"Goddess of gold"},{n:"Sokkammal",m:"Graceful lady"},{n:"Sobana Devi",m:"Radiant goddess"}], north: [{n:"Sonal",m:"Golden"},{n:"Sonali",m:"Golden and beautiful"},{n:"Somya",m:"Gentle and calm"},{n:"Sohana",m:"Pleasant and lovely"},{n:"Sonam",m:"Fortunate, blessed"}] } },
  "லா": { M: { south: [{n:"Lavanyan",m:"Graceful and handsome"},{n:"Lakshmanan",m:"Auspicious, devoted"},{n:"Lalithan",m:"Graceful and charming"},{n:"Lakshminarayanan",m:"Lord Vishnu with Lakshmi"},{n:"Lakshan",m:"Auspicious mark"},{n:"Lakshmana",m:"Devoted brother"}], north: [{n:"Lakshay",m:"Aim, goal"},{n:"Lalit",m:"Graceful and charming"},{n:"Laxman",m:"Auspicious"},{n:"Laxmikant",m:"Lord Vishnu"},{n:"Lavesh",m:"Small, precious part"},{n:"Lav",m:"Lava, son of Rama"}] }, F: { south: [{n:"Lavanya",m:"Beauty and grace"},{n:"Lakshmi",m:"Goddess of wealth"},{n:"Lalitha",m:"Playful and graceful"},{n:"Lakshana",m:"Distinguished"},{n:"Lakshmipriya",m:"Dear to Lakshmi"},{n:"Lalithambal",m:"Graceful goddess"},{n:"Lavanyasri",m:"Graceful prosperity"},{n:"Lathika",m:"A delicate creeper"}], north: [{n:"Laxmi",m:"Goddess of fortune"},{n:"Latika",m:"Small creeper"},{n:"Lalita",m:"Charming, playful"},{n:"Lakshita",m:"Noted, distinguished"},{n:"Lavisha",m:"Loved and charming"},{n:"Lajja",m:"Modesty"},{n:"Lavina",m:"Beauty, charm"}] } },
  "லீ": { M: { south: [{n:"Lingesan",m:"Lord Shiva"},{n:"Lingeswaran",m:"Lord of the Lingam"},{n:"Lingappan",m:"Lord Shiva"},{n:"Lingarajan",m:"Lord Shiva"},{n:"Leelavarman",m:"Playful prince"},{n:"Leelakumaran",m:"Graceful prince"}], north: [{n:"Leeladhar",m:"Lord Vishnu"},{n:"Likhit",m:"Written, inscribed"},{n:"Likhil",m:"Learned"},{n:"Liyansh",m:"A little part"}] }, F: { south: [{n:"Leelavathi",m:"Playful goddess"},{n:"Leelambal",m:"Graceful mother"},{n:"Lingeswari",m:"Goddess of the Lingam"},{n:"Lipisha",m:"Sacred writing"},{n:"Leelamani",m:"Jewel of grace"},{n:"Leelavani",m:"Graceful speech"}], north: [{n:"Lipika",m:"Small script"},{n:"Lipi",m:"Sacred writing"},{n:"Leela",m:"Divine play"},{n:"Lila",m:"Playful, divine drama"},{n:"Lilavati",m:"Graceful and charming"}] } },
  "லூ": { M: { south: [{n:"Luhit",m:"Bright red glow"},{n:"Luhith",m:"Radiant red"}], north: [{n:"Luv",m:"Son of Lord Rama"},{n:"Luvan",m:"Handsome"},{n:"Luvansh",m:"Part of love"}] }, F: { south: [{n:"Lubna",m:"Sweet fragrance"},{n:"Lukshana",m:"Auspicious mark"},{n:"Lushika",m:"Radiant"}], north: [{n:"Lunita",m:"Bright and lovely"},{n:"Luvni",m:"Beloved"}] } },
  "லே": { M: { south: [{n:"Lekan",m:"Master of writing"},{n:"Lekesh",m:"Master of the arts"},{n:"Leelakarthik",m:"Playful and radiant"}], north: [{n:"Lekhan",m:"Writer, author"},{n:"Lekhraj",m:"King of writing"}] }, F: { south: [{n:"Lekha",m:"Divine writing, star"},{n:"Lekhashree",m:"Wealth of learning"},{n:"Lena",m:"Bright, shining"}], north: [{n:"Lekhita",m:"Beautifully written"},{n:"Lekhna",m:"Fine writing"},{n:"Leena",m:"Devoted, soft"}] } },
  "லோ": { M: { south: [{n:"Loganathan",m:"Protector of the world"},{n:"Loganayagan",m:"Leader of the world"},{n:"Lokesh",m:"Lord of the world"},{n:"Lokeshwaran",m:"Lord of the worlds"},{n:"Logan",m:"Worldly, wise"}], north: [{n:"Loknath",m:"Lord of the world"},{n:"Lopamudra",m:"Wise sage (unisex)"},{n:"Lochan",m:"The eye, Lord Vishnu"}] }, F: { south: [{n:"Lopamudra",m:"Wise sage woman"},{n:"Lohitha",m:"Red, radiant Lakshmi"},{n:"Logeshwari",m:"Goddess of the world"},{n:"Lojini",m:"Modest, graceful"}], north: [{n:"Lokeshi",m:"Goddess of the world"},{n:"Lokshana",m:"Distinguished"},{n:"Lona",m:"Bright light"}] } },
  "அ": { M: { south: [{n:"Arul",m:"Divine grace"},{n:"Anandhan",m:"Joyful and blissful"},{n:"Aravindhan",m:"The lotus"},{n:"Arun",m:"The rising Sun"},{n:"Azhagan",m:"Handsome and charming"},{n:"Anbu",m:"Love and affection"},{n:"Aadhavan",m:"The Sun"},{n:"Amudhan",m:"The nectar of life"},{n:"Arivazhagan",m:"Wise king"},{n:"Anbarasan",m:"King of love"},{n:"Arulmozhi",m:"Blessed speech"}], north: [{n:"Aarav",m:"Peaceful and calm"},{n:"Aditya",m:"The Sun god"},{n:"Ansh",m:"Part of the divine"},{n:"Arnav",m:"The ocean"},{n:"Abhay",m:"Fearless"},{n:"Akhil",m:"Complete, whole"},{n:"Anirudh",m:"Boundless"},{n:"Aryan",m:"Noble and honourable"},{n:"Advait",m:"Unique, non-dual"},{n:"Akshay",m:"Immortal"},{n:"Arjun",m:"Bright and shining"},{n:"Amit",m:"Limitless"}] }, F: { south: [{n:"Anjali",m:"An offering of devotion"},{n:"Aarthi",m:"Divine light"},{n:"Abinaya",m:"Graceful expression"},{n:"Amudha",m:"Nectar, sweetness"},{n:"Anitha",m:"Grace and favour"},{n:"Aruna",m:"The dawn"},{n:"Aadhira",m:"Lightning, first light"},{n:"Anbarasi",m:"Queen of love"},{n:"Agalya",m:"A spotless beauty"},{n:"Anusiya",m:"Kind and generous"},{n:"Amirthavalli",m:"A goddess of nectar"}], north: [{n:"Aanya",m:"Grace and favour"},{n:"Aaradhya",m:"Worthy of worship"},{n:"Aditi",m:"Mother of the gods"},{n:"Ananya",m:"Unique and matchless"},{n:"Akshara",m:"Imperishable"},{n:"Anika",m:"Graceful"},{n:"Aadya",m:"The first, primordial"},{n:"Avni",m:"The earth"},{n:"Anushka",m:"Radiant"},{n:"Amrita",m:"The nectar of immortality"},{n:"Aisha",m:"Prosperous, alive"}] } },
  "இ": { M: { south: [{n:"Ilango",m:"A youthful prince"},{n:"Ilamaran",m:"A youthful warrior"},{n:"Ilavarasan",m:"A young prince"},{n:"Iniyan",m:"Sweet-natured"},{n:"Ilakkiyan",m:"A literary scholar"},{n:"Isaiarasu",m:"King of music"},{n:"Ilayarasan",m:"A young king"},{n:"Iravan",m:"A valiant warrior"}], north: [{n:"Ishaan",m:"The Sun, Lord Shiva"},{n:"Ishwar",m:"God, the supreme Lord"},{n:"Indrajit",m:"Conqueror of Indra"},{n:"Ikshvaku",m:"Ancestor of Lord Rama"},{n:"Inderjit",m:"Conqueror of the gods"},{n:"Indubhushan",m:"Moon-adorned Lord Shiva"},{n:"Ivaan",m:"Radiant, the sun"}] }, F: { south: [{n:"Iniya",m:"Sweet and pleasant"},{n:"Ilakkiya",m:"Literature, poetry"},{n:"Ilamathi",m:"A young moon"},{n:"Inbavalli",m:"A lovable woman"},{n:"Isaiyarasi",m:"Queen of music"},{n:"Inbakodi",m:"Sweet and tender"},{n:"Inbavathi",m:"Full of love"}], north: [{n:"Isha",m:"Consort of Lord Shiva"},{n:"Ishita",m:"Superiority, a wish"},{n:"Ira",m:"The earth"},{n:"Indira",m:"Goddess Lakshmi"},{n:"Indu",m:"The moon"},{n:"Ipsita",m:"A wished-for child"},{n:"Ishani",m:"Goddess Parvati"},{n:"Ila",m:"The earth, speech"}] } },
  "உ": { M: { south: [{n:"Udhayan",m:"The rising Sun"},{n:"Uthaman",m:"The noblest one"},{n:"Ulaganathan",m:"Protector of the world"},{n:"Udhayakumar",m:"A rising prince"},{n:"Umapathy",m:"A ruling lord"},{n:"Uthayakumaran",m:"A rising prince"},{n:"Ulagan",m:"The world, worldly wise"}], north: [{n:"Uday",m:"The dawn"},{n:"Utkarsh",m:"Excellence"},{n:"Ujjwal",m:"Bright and radiant"},{n:"Umang",m:"Enthusiasm"},{n:"Udit",m:"Risen, awakened"},{n:"Umesh",m:"Lord of Uma"},{n:"Utpal",m:"The lotus"},{n:"Ullas",m:"Joy and delight"}] }, F: { south: [{n:"Uma",m:"Goddess Parvati"},{n:"Usha",m:"The dawn"},{n:"Udhaya",m:"The dawn"},{n:"Usharani",m:"A queen of dawn"},{n:"Umamaheswari",m:"Consort of Lord Shiva"},{n:"Uthra",m:"Highly noble"},{n:"Ulagammal",m:"Mother of the world"}], north: [{n:"Upasana",m:"Devoted worship"},{n:"Urvashi",m:"A celestial nymph"},{n:"Urmila",m:"Enchantress, devoted wife"},{n:"Urvi",m:"The earth"},{n:"Ujjwala",m:"Bright and luminous"},{n:"Unnati",m:"Progress and growth"},{n:"Uttara",m:"The north star"},{n:"Upasna",m:"Devout meditation"}] } },
  "எ": { M: { south: [{n:"Ezhilarasan",m:"A king of beauty"},{n:"Elango",m:"A prince"},{n:"Elangovan",m:"A handsome prince"},{n:"Ezhilan",m:"A beautiful young man"},{n:"Eesan",m:"Lord Shiva"},{n:"Ethirajan",m:"A noble king"},{n:"Ekambaram",m:"Lord Shiva of Kanchi"},{n:"Ezhilmaran",m:"A handsome youth"}], north: [{n:"Eklavya",m:"The devoted disciple"},{n:"Ekansh",m:"The whole, complete"},{n:"Eshan",m:"Lord Shiva"},{n:"Eknath",m:"A revered saint"},{n:"Ekagra",m:"Focused and attentive"},{n:"Ekam",m:"One, supreme"}] }, F: { south: [{n:"Ezhil",m:"Beauty and grace"},{n:"Ezhilarasi",m:"A queen of beauty"},{n:"Eeswari",m:"Goddess Parvati"},{n:"Elavarasi",m:"A young princess"},{n:"Ezhilnila",m:"A beautiful moon"},{n:"Elakkiya",m:"Literature and learning"}], north: [{n:"Esha",m:"Consort of Lord Shiva"},{n:"Ekta",m:"Unity and harmony"},{n:"Eshita",m:"Desired, superior"},{n:"Eesha",m:"The goddess"},{n:"Ekaja",m:"The only daughter"}] } },
  "ஒ": { M: { south: [{n:"Oviyan",m:"The painter"}], north: [{n:"Om",m:"The sacred syllable"},{n:"Omkar",m:"The sacred Om"},{n:"Ojas",m:"Brightness, vitality"},{n:"Omprakash",m:"Light of Om"},{n:"Omkarnath",m:"Lord of the Om"},{n:"Ojasvin",m:"Full of vitality"},{n:"Omesh",m:"Lord of Om"}] }, F: { south: [{n:"Oviya",m:"Graceful as art"},{n:"Oviammal",m:"Artistic goddess"}], north: [{n:"Ojaswini",m:"Full of vitality"},{n:"Oorja",m:"Energy and strength"},{n:"Ojasvi",m:"Bright and vital"},{n:"Oshi",m:"A lovely girl"},{n:"Omkari",m:"Goddess of Om"}] } },
  "வா": { M: { south: [{n:"Vasanthan",m:"Spring season"},{n:"Valavan",m:"Clever and skilled"},{n:"Vaanavan",m:"Sky-like, divine"},{n:"Varadhan",m:"Giver of boons"},{n:"Vaithianathan",m:"Lord of medicine"},{n:"Vasanthakumar",m:"Spring prince"},{n:"Vallavan",m:"Skilled and brave"},{n:"Vasudevan",m:"Lord Krishna"},{n:"Varadharajan",m:"Lord Vishnu"},{n:"Vallinayagam",m:"Lord Murugan"}], north: [{n:"Varun",m:"Lord of the waters"},{n:"Vansh",m:"Lineage, family"},{n:"Vardhaan",m:"Prosperity giver"},{n:"Vaibhav",m:"Prosperity, splendour"},{n:"Vatsal",m:"Affectionate"},{n:"Varad",m:"Bestower of boons"},{n:"Vasudev",m:"Lord Krishna"}] }, F: { south: [{n:"Vaishnavi",m:"Goddess Lakshmi"},{n:"Vasanthi",m:"Spring, cheerful"},{n:"Valli",m:"Vallikkanavan's consort"},{n:"Vasundhari",m:"Goddess of the earth"},{n:"Vaanathi",m:"Of the sky, celestial"},{n:"Vaijayanthi",m:"Garland of victory"},{n:"Valarmathi",m:"Radiant like the moon"}], north: [{n:"Vani",m:"Goddess Saraswati"},{n:"Vaishali",m:"Ancient city name"},{n:"Vandana",m:"Salutation, worship"},{n:"Varsha",m:"Rain, monsoon"},{n:"Varuna",m:"Goddess of the waters"},{n:"Vaidehi",m:"Sita, consort of Rama"},{n:"Vasumathi",m:"The earth, wealth"},{n:"Vatsala",m:"Loving and affectionate"}] } },
  "வீ": { M: { south: [{n:"Veeramani",m:"Brave jewel"},{n:"Veeran",m:"Brave warrior"},{n:"Vignesh",m:"Lord Ganesha"},{n:"Vigneshwaran",m:"Lord of obstacles"},{n:"Vijayan",m:"Victorious"},{n:"Veerapandian",m:"Brave Pandiya king"},{n:"Vidhya",m:"Knowledge"},{n:"Viswanathan",m:"Lord of the universe"},{n:"Vijayakumar",m:"Victorious prince"}], north: [{n:"Vihaan",m:"Dawn, morning"},{n:"Vivaan",m:"Full of life"},{n:"Vikram",m:"Valour"},{n:"Vijay",m:"Victory"},{n:"Vishesh",m:"Special, distinct"},{n:"Vinay",m:"Modesty, Lord Ganesha"},{n:"Vishwas",m:"Faith, trust"},{n:"Vinayak",m:"Lord Ganesha"},{n:"Vishal",m:"Vast, great"},{n:"Vivek",m:"Wisdom, discernment"},{n:"Vishnu",m:"The preserver god"}] }, F: { south: [{n:"Vidhya",m:"Knowledge, learning"},{n:"Vijayalakshmi",m:"Goddess of victory"},{n:"Vishnupriya",m:"Beloved of Lord Vishnu"},{n:"Veeralakshmi",m:"Brave Lakshmi"},{n:"Visalakshi",m:"Wide-eyed goddess"}], north: [{n:"Vidhi",m:"Destiny, fate"},{n:"Vidya",m:"Wisdom, knowledge"},{n:"Vibha",m:"Bright light"},{n:"Vira",m:"Brave, heroic"},{n:"Vishakha",m:"A star of the zodiac"},{n:"Vidushi",m:"Learned woman"},{n:"Vineeta",m:"Modest and humble"},{n:"Vidhatri",m:"Creator, sustainer"}] } },
  "வு": { M: { south: [{n:"Vuthaman",m:"A noble soul"}], north: [] }, F: { south: [], north: [] } },
  "வே": { M: { south: [{n:"Venkatesan",m:"Lord of Venkata hills"},{n:"Velmurugan",m:"Lord Murugan's spear"},{n:"Vetrivel",m:"Spear of victory"},{n:"Velan",m:"Lord Murugan"},{n:"Vedhagiri",m:"Sacred hill of wisdom"},{n:"Vedhanayagam",m:"Lord of the Vedas"}], north: [{n:"Vedant",m:"The conclusion of the Vedas"},{n:"Vedansh",m:"Part of the sacred knowledge"},{n:"Vedprakash",m:"Light of the Vedas"},{n:"Vedh",m:"Sacred knowledge"}] }, F: { south: [{n:"Velvizhi",m:"Sharp-eyed like a spear"},{n:"Vedhavalli",m:"A goddess of wisdom"},{n:"Vethika",m:"A wise girl"},{n:"Vedhalakshmi",m:"Goddess of sacred wisdom"},{n:"Vedhavathi",m:"Full of sacred knowledge"},{n:"Venmathi",m:"Moonlight, radiant"},{n:"Vennila",m:"White moon"}], north: [{n:"Vedika",m:"Altar of the Vedas"},{n:"Vedha",m:"Sacred knowledge"},{n:"Vedanshi",m:"Part of sacred knowledge"},{n:"Veda",m:"The sacred scriptures"},{n:"Vedavati",m:"A noble princess"}] } },
  "கா": { M: { south: [{n:"Karthikeyan",m:"Lord Murugan"},{n:"Kaarthik",m:"Bestower of courage"},{n:"Kavin",m:"Beautiful, handsome"},{n:"Kalyanasundaram",m:"Lord Shiva, ever auspicious"},{n:"Kamalakannan",m:"Lord Vishnu, lotus-eyed"},{n:"Kathiravan",m:"The Sun"},{n:"Kalaiselvan",m:"Artistic and prosperous"},{n:"Kalaivanan",m:"Full of art"},{n:"Karthikraja",m:"Radiant king"}], north: [{n:"Kartik",m:"Bestower of courage"},{n:"Kaushal",m:"Skill, excellence"},{n:"Kaustubh",m:"Divine gem"},{n:"Kanishk",m:"An ancient king"},{n:"Kailash",m:"Sacred Mount Kailash"},{n:"Karan",m:"Skilled, clever"},{n:"Kalpesh",m:"Lord of wishes"},{n:"Kamesh",m:"Lord of desire"}] }, F: { south: [{n:"Kavitha",m:"A poem"},{n:"Kalaiselvi",m:"Goddess of arts"},{n:"Kalyani",m:"Auspicious woman"},{n:"Kanimozhi",m:"Sweet words"},{n:"Kayalvizhi",m:"Fish-eyed beauty"},{n:"Kasthuri",m:"Fragrance, musk"},{n:"Karpagam",m:"Wish-fulfilling"},{n:"Kalaimagal",m:"Goddess of arts"},{n:"Kalaivani",m:"Goddess of arts"}], north: [{n:"Kavya",m:"Poetry"},{n:"Kanishka",m:"Golden, youthful"},{n:"Kalpana",m:"Imagination"},{n:"Kashish",m:"Attraction, charm"},{n:"Kajal",m:"Kohl, eyeliner"},{n:"Kamini",m:"Lovely woman"}] } },
  "கீ": { M: { south: [{n:"Keerthan",m:"Devotional song"},{n:"Keerthivasan",m:"Famous and prosperous"},{n:"Kirubakaran",m:"Blessing of grace"},{n:"Kiruthik",m:"Bestower of courage"},{n:"Kiran",m:"Ray of light"},{n:"Kishore",m:"Young and youthful"}], north: [{n:"Kirtan",m:"Devotional song"},{n:"Kishor",m:"Youthful"},{n:"Kiyansh",m:"Part of glory"},{n:"Kirtivardhan",m:"One who grows fame"},{n:"Kian",m:"Grace of God"}] }, F: { south: [{n:"Kirthika",m:"A star of the zodiac"},{n:"Keerthana",m:"Devotional song"},{n:"Kiruthiga",m:"Bestower of courage"},{n:"Kiran",m:"Ray of light"}], north: [{n:"Kirti",m:"Fame and honour"},{n:"Kishori",m:"Young maiden"},{n:"Kinnari",m:"Celestial musician"},{n:"Kiara",m:"Bright and clear"},{n:"Kritika",m:"A star of the zodiac"}] } },
  "கு": { M: { south: [{n:"Kumaran",m:"Lord Murugan"},{n:"Kumaravelan",m:"Lord Murugan's spear"},{n:"Kumaresan",m:"Lord Murugan"},{n:"Kugan",m:"Lord Murugan"},{n:"Gunanithi",m:"Treasure of virtue"},{n:"Gunasekaran",m:"Virtuous Lord Shiva"},{n:"Gurusamy",m:"Divine teacher"},{n:"Gurunathan",m:"Divine teacher"},{n:"Kumanan",m:"Wise and noble"}], north: [{n:"Kunal",m:"Lotus"},{n:"Kush",m:"Son of Lord Rama"},{n:"Kushagra",m:"Sacred grass"},{n:"Gulshan",m:"Flower garden"},{n:"Gulab",m:"Rose flower"},{n:"Gunwant",m:"Full of virtue"},{n:"Gurudutt",m:"Granted by the guru"}] }, F: { south: [{n:"Kumari",m:"Princess, young girl"},{n:"Kumudha",m:"Lotus flower"},{n:"Gunavathy",m:"Full of virtue"},{n:"Gunasundari",m:"Virtuous beauty"},{n:"Kunjamma",m:"Little darling"},{n:"Kumudhavalli",m:"Lotus creeper"}], north: [{n:"Kumud",m:"Lotus"},{n:"Gunjan",m:"Soft humming"},{n:"Gulnaar",m:"Pomegranate flower"},{n:"Kuhu",m:"Cuckoo's call"},{n:"Kumudini",m:"A lotus pond"},{n:"Kushi",m:"Happiness"},{n:"Khushi",m:"Happiness"}] } },
  "க": { M: { south: [{n:"Kannan",m:"Lord Krishna"},{n:"Kabilan",m:"Poet, learned man"},{n:"Kandan",m:"Lord Murugan"},{n:"Kanagaraj",m:"King of the forest"},{n:"Kalidasan",m:"Servant of Goddess Kali"},{n:"Kalimuthu",m:"Pearl of virtue"},{n:"Kanmani",m:"Precious gem"},{n:"Karpooram",m:"Camphor, pure"}], north: [{n:"Kabir",m:"Great, saintly poet"},{n:"Kamal",m:"Lotus"},{n:"Kapil",m:"An ancient sage"},{n:"Ghanashyam",m:"Dark as a cloud, Krishna"},{n:"Khanjan",m:"Restless bird"},{n:"Ghanendra",m:"Lord of the clouds"}] }, F: { south: [{n:"Kamala",m:"Lotus flower"},{n:"Kamakshi",m:"Goddess with loving eyes"},{n:"Karpagam",m:"Wish-fulfilling"},{n:"Kalaivani",m:"Goddess of arts"},{n:"Kanmani",m:"Precious gem"},{n:"Kalaichelvi",m:"Goddess of arts"}], north: [{n:"Kanika",m:"Golden"},{n:"Kasturi",m:"Musk, fragrance"},{n:"Kajri",m:"A monsoon melody"},{n:"Kamini",m:"Lovely woman"},{n:"Kalyani",m:"Auspicious woman"}] } },
  "ங": { M: { south: [{n:"Nganesan",m:"Lord of the varga sound"}], north: [{n:"Nagesh",m:"Lord of serpents"}] }, F: { south: [{n:"Nganeswari",m:"Goddess of the varga sound"}], north: [{n:"Nagina",m:"Jewel"}] } },
  "ச": { M: { south: [{n:"Shanmugam",m:"Lord Murugan"},{n:"Chandran",m:"The Moon"},{n:"Sankar",m:"Lord Shiva"},{n:"Sathish",m:"Lord of virtue"},{n:"Saravanan",m:"Lord Murugan"},{n:"Chandrasekar",m:"Lord of the moon"},{n:"Sathyaseelan",m:"Of noble conduct"},{n:"Shanthakumar",m:"Peaceful prince"}], north: [{n:"Chandan",m:"Sandalwood"},{n:"Charan",m:"Feet of the Lord"},{n:"Chaitanya",m:"Divine consciousness"},{n:"Chandresh",m:"Lord of the moon"},{n:"Chatur",m:"Clever and wise"}] }, F: { south: [{n:"Chandra",m:"Moonlight"},{n:"Chandrika",m:"Moonlight, radiant"},{n:"Saranya",m:"Surrendered to God"},{n:"Savitha",m:"The Sun, bright"},{n:"Sangeetha",m:"Music, melody"},{n:"Chandrakala",m:"Moonbeam"},{n:"Santhiya",m:"Peace and calm"}], north: [{n:"Charu",m:"Beautiful, graceful"},{n:"Charvi",m:"Beautiful woman"},{n:"Chhavi",m:"Radiance, beauty"},{n:"Chandni",m:"Moonlight"},{n:"Chameli",m:"Jasmine flower"}] } },
  "கே": { M: { south: [{n:"Kesavan",m:"Lord Vishnu"},{n:"Kesari",m:"Lion, brave"},{n:"Kesavaraj",m:"Lord Vishnu"},{n:"Ketharan",m:"Lord of the field"},{n:"Kesavakumar",m:"Prince of Lord Vishnu"}], north: [{n:"Keshav",m:"Lord Krishna"},{n:"Ketan",m:"Banner, symbol"},{n:"Keyur",m:"Armlet, ornament"},{n:"Keshavnath",m:"Lord Krishna"},{n:"Kedar",m:"Lord Shiva, mountain"}] }, F: { south: [{n:"Kethaki",m:"Screw-pine flower"},{n:"Keshavi",m:"Goddess Lakshmi"},{n:"Kethana",m:"Graceful"},{n:"Kesini",m:"Lovely haired"},{n:"Kayalvizhi",m:"Eyes like the kayal fish"}], north: [{n:"Ketaki",m:"Screw-pine flower"},{n:"Keya",m:"A fragrant flower"},{n:"Keshni",m:"Beautiful tresses"},{n:"Kesika",m:"Graceful"}] } },
  "கோ": { M: { south: [{n:"Kothandaraman",m:"Lord Rama, wielder of the bow"},{n:"Kothandapani",m:"Lord Rama"},{n:"Kovalan",m:"A celebrated hero"},{n:"Kovendhan",m:"King, ruler"},{n:"Kozhandai",m:"Little child"},{n:"Komalan",m:"Gentle and handsome"}], north: [{n:"Gopal",m:"Lord Krishna"},{n:"Govind",m:"Lord Krishna"},{n:"Gokul",m:"Krishna's childhood home"},{n:"Kovid",m:"Learned, wise"},{n:"Gopesh",m:"Lord of the cowherds"},{n:"Komal",m:"Soft, gentle"}] }, F: { south: [{n:"Kothai",m:"A name of Goddess Andal"},{n:"Kokila",m:"The cuckoo bird"},{n:"Komalavalli",m:"Gentle creeper"},{n:"Kovai",m:"A Tamil name"},{n:"Kogila",m:"Melodious bird"}], north: [{n:"Gopika",m:"A cowherd maiden"},{n:"Komali",m:"Gentle and sweet"},{n:"Koyal",m:"The cuckoo bird"}] } },
  "ஹா": { M: { south: [{n:"Hariharan",m:"Lord Vishnu and Shiva"},{n:"Harish",m:"Lord Vishnu"},{n:"Harikrishnan",m:"Lord Krishna"},{n:"Hariprasad",m:"Blessed by Lord Vishnu"},{n:"Hanumanthan",m:"Devoted to Lord Rama"},{n:"Harivarman",m:"Protected by Lord Vishnu"}], north: [{n:"Harsh",m:"Happiness, joy"},{n:"Harshit",m:"One who brings joy"},{n:"Hardik",m:"From the heart"},{n:"Harendra",m:"Lord Vishnu, Indra"},{n:"Hansraj",m:"King of swans"},{n:"Harshad",m:"Bestower of joy"}] }, F: { south: [{n:"Harini",m:"A deer, graceful"},{n:"Haritha",m:"Green, fresh"},{n:"Hasini",m:"Smiling, cheerful"},{n:"Harshitha",m:"Full of joy"},{n:"Hareni",m:"Graceful"}], north: [{n:"Harshita",m:"Full of joy"},{n:"Hansika",m:"Beautiful swan"},{n:"Harshada",m:"Bestower of joy"},{n:"Hansa",m:"A swan"},{n:"Hastalekha",m:"Fine handwriting"}] } },
  "ஹீ": { M: { south: [{n:"Hiranmayan",m:"Golden, radiant"},{n:"Hitesh",m:"Well-wisher"},{n:"Himesh",m:"Lord of the snow"},{n:"Himavan",m:"Lord of the Himalayas"}], north: [{n:"Himanshu",m:"The moon, snow"},{n:"Hiten",m:"Well-wisher"},{n:"Hitansh",m:"Well-wisher"},{n:"Hiresh",m:"Lord of diamonds"}] }, F: { south: [{n:"Hima",m:"Snow, winter"},{n:"Hiranmayi",m:"Golden woman"},{n:"Himaja",m:"Daughter of the snows"},{n:"Hiranya",m:"Golden, wealth"}], north: [{n:"Himani",m:"Snow-covered mountains"},{n:"Hiral",m:"Diamond, radiant"},{n:"Hina",m:"Henna, fragrance"}] } },
  "ஹு": { M: { south: [], north: [{n:"Hukum",m:"Authority, command"},{n:"Hunar",m:"Skill and talent"},{n:"Hulash",m:"Joy and delight"}] }, F: { south: [], north: [{n:"Huma",m:"A celestial bird"},{n:"Hunarpreet",m:"Love of talent"}] } },
  "ஹே": { M: { south: [{n:"Hemanthan",m:"Lord of gold"},{n:"Hemachandran",m:"Golden moon"},{n:"Heman",m:"Golden one"}], north: [{n:"Hemanth",m:"Lord of gold, winter"},{n:"Hemant",m:"Winter season"},{n:"Hemraj",m:"Golden king"}] }, F: { south: [{n:"Hema",m:"Golden, Goddess Lakshmi"},{n:"Hemalatha",m:"Golden creeper"},{n:"Hemavathi",m:"Golden, radiant"},{n:"Hemasri",m:"Golden prosperity"},{n:"Hema Malini",m:"Golden garland"}], north: [{n:"Hetal",m:"Cheerful, friendly"},{n:"Hemlata",m:"Golden creeper"},{n:"Hemangi",m:"Golden-bodied"},{n:"Hemakshi",m:"Golden-eyed"}] } },
  "ஹோ": { M: { south: [{n:"Hovindan",m:"Lord Vishnu"}], north: [{n:"Hosh",m:"Joy, delight"}] }, F: { south: [{n:"Homa",m:"A sacred offering"}], north: [{n:"Hoshi",m:"Radiant star"}] } },
  "டா": { M: { south: [{n:"Dhanasekaran",m:"Lord of wealth"},{n:"Dakshan",m:"Skilled, able"},{n:"Dayalan",m:"The compassionate one"},{n:"Dharman",m:"Embodiment of righteousness"}], north: [{n:"Daksh",m:"Capable, excellent"},{n:"Darsh",m:"Divine sight"},{n:"Dhanraj",m:"Lord of wealth"},{n:"Daivik",m:"Divine"},{n:"Dharmesh",m:"Lord of righteousness"}] }, F: { south: [{n:"Damayanthi",m:"Noble woman"},{n:"Dayamayi",m:"Full of compassion"},{n:"Datchayani",m:"Daughter of Daksha"},{n:"Daya",m:"Compassion, mercy"}], north: [{n:"Damini",m:"Lightning, bright"},{n:"Darshana",m:"Divine sight"},{n:"Dakshita",m:"Skilled and talented"}] } },
  "டீ": { M: { south: [{n:"Dinesh",m:"Lord of the day, Sun"},{n:"Dineshkumar",m:"Lord of the day"},{n:"Divakaran",m:"The Sun"},{n:"Deepak",m:"Lamp of light"},{n:"Dileepan",m:"Protector, king"}], north: [{n:"Divyansh",m:"Part of the divine light"},{n:"Dilip",m:"Protector of the world"},{n:"Divit",m:"Immortal, divine"},{n:"Dinkar",m:"The Sun"}] }, F: { south: [{n:"Divya",m:"Divine, heavenly"},{n:"Divyadharshini",m:"Beautiful divine sight"},{n:"Deepa",m:"Light, lamp"},{n:"Divyabharathi",m:"Divine speech"},{n:"Deepthi",m:"Light, radiance"},{n:"Dilsha",m:"Radiant smile"},{n:"Divyashree",m:"Divine radiance"}], north: [{n:"Divyanshi",m:"Part of the divine light"},{n:"Diksha",m:"Sacred initiation"},{n:"Divisha",m:"Divine blessing"},{n:"Dipti",m:"Illumination"},{n:"Deepali",m:"Row of lamps"},{n:"Divija",m:"Born of the divine"},{n:"Disha",m:"Direction, guidance"},{n:"Divyanka",m:"Divine glow"},{n:"Dikshita",m:"One who is initiated"},{n:"Dimpal",m:"Dimple, cheerful"}] } },
  "டூ": { M: { south: [{n:"Durai",m:"Chief, leader"},{n:"Duraisamy",m:"Our chief"},{n:"Duraiswamy",m:"Our chief"},{n:"Dushyanthan",m:"Destroyer of evil"},{n:"Durgaprasad",m:"Blessed by Goddess Durga"},{n:"Duraipandian",m:"Tamil chieftain, leader"}], north: [{n:"Dushyant",m:"Destroyer of evil"},{n:"Durajan",m:"Lord of the age"},{n:"Durgesh",m:"Lord of the fort"}] }, F: { south: [{n:"Durgadevi",m:"Goddess Durga"},{n:"Duraimozhi",m:"Sweet speaker"},{n:"Durgambal",m:"Goddess Durga"},{n:"Duraiammal",m:"Goddess Durai, protector"},{n:"Durgai",m:"Goddess Durga"},{n:"Duraisundari",m:"Beautiful consort of Durai"}], north: [{n:"Durga",m:"Goddess Durga"},{n:"Durgawati",m:"Devoted to Goddess Durga"},{n:"Dulari",m:"Very dear one"},{n:"Durgeshwari",m:"Goddess of the fort"},{n:"Dushala",m:"Mahabharata princess"}] } },
  "டே": { M: { south: [{n:"Devanathan",m:"Lord of the gods"},{n:"Devanesan",m:"Lord Shiva"},{n:"Devan",m:"God, divine one"},{n:"Devendran",m:"King of the gods"},{n:"Devakumar",m:"Divine prince"},{n:"Devarajan",m:"King of the gods"},{n:"Dayanandhan",m:"Bliss of compassion"}], north: [{n:"Devansh",m:"Part of the divine"},{n:"Devendra",m:"King of the gods"},{n:"Devang",m:"Divine part"},{n:"Teyjas",m:"Radiance, brilliance"},{n:"Devrath",m:"A divine chariot"}] }, F: { south: [{n:"Devaki",m:"Mother of Lord Krishna"},{n:"Devanayaki",m:"Divine queen"},{n:"Devi",m:"Goddess"},{n:"Devika",m:"A little goddess"},{n:"Devarathi",m:"Divine chariot"},{n:"Devayani",m:"Divine maiden"},{n:"Devasena",m:"Wife of Lord Kartikeya"},{n:"Devapriya",m:"Dear to the gods"},{n:"Devadharshini",m:"Divine sight"}], north: [{n:"Devina",m:"Beloved goddess"},{n:"Devangi",m:"Like a goddess"},{n:"Tejaswini",m:"Full of radiance"},{n:"Devanshi",m:"Divine, of the gods"},{n:"Devya",m:"Little goddess"},{n:"Devyani",m:"Celestial maiden"}] } },
  "டோ": { M: { south: [{n:"Dolan",m:"Fragrant"},{n:"Doraisamy",m:"Our chief"}], north: [{n:"Dola",m:"Swing, delight"}] }, F: { south: [{n:"Dorathy",m:"Divine gift"},{n:"Dolly",m:"Beloved, darling"}], north: [{n:"Dorika",m:"Divine gift"},{n:"Doyel",m:"Songbird, nightingale"},{n:"Doel",m:"Nightingale, songbird"},{n:"Dola",m:"Swing, delight"}] } },
  "மா": { M: { south: [{n:"Maaran",m:"Brave warrior"},{n:"Madhavan",m:"Lord Krishna"},{n:"Mahendran",m:"King of kings"},{n:"Manikandan",m:"Lord Ayyappa"},{n:"Manivannan",m:"Precious jewel"},{n:"Magesh",m:"Lord of the divine"},{n:"Mahadevan",m:"The great Lord"},{n:"Manoharan",m:"Beautiful and charming"},{n:"Marudhachalam",m:"A sacred hill"},{n:"Manimaran",m:"Lord Murugan, bejewelled"},{n:"Maran",m:"Brave and steadfast"},{n:"Mahalingam",m:"The great Lord Shiva"}], north: [{n:"Madhav",m:"Lord Krishna"},{n:"Manav",m:"Human, kind-hearted"},{n:"Mahir",m:"Skilled and expert"},{n:"Mahesh",m:"The great Lord Shiva"},{n:"Manish",m:"Lord of the mind"},{n:"Mangal",m:"Auspicious"},{n:"Mayank",m:"The moon"},{n:"Manan",m:"Deep reflection"},{n:"Mayur",m:"Peacock"},{n:"Mahipal",m:"Protector of the earth"},{n:"Manvendra",m:"Lord of men"}] }, F: { south: [{n:"Malar",m:"Flower"},{n:"Malarvizhi",m:"Graceful-eyed"},{n:"Mahalakshmi",m:"Goddess of fortune"},{n:"Malathi",m:"Fragrant flower"},{n:"Malavika",m:"A princess"},{n:"Manimekalai",m:"A celebrated heroine"},{n:"Malarvili",m:"Beautiful flower"},{n:"Mangalam",m:"Auspicious"}], north: [{n:"Mahi",m:"The earth"},{n:"Maya",m:"Divine illusion"},{n:"Mahika",m:"Great earth"},{n:"Malini",m:"A gardener, fragrant"},{n:"Manisha",m:"Wish, desire"},{n:"Mansi",m:"Of the mind"},{n:"Malti",m:"Jasmine flower"},{n:"Mannat",m:"A sacred wish"}] } },
  "மீ": { M: { south: [{n:"Meenakshisundaram",m:"Lord Shiva of Madurai"},{n:"Meeran",m:"Chief, respected one"}], north: [{n:"Mihir",m:"The Sun, gentle breeze"},{n:"Mitesh",m:"Friend of all"},{n:"Mitul",m:"Measured, limited"},{n:"Milan",m:"Union, meeting"}] }, F: { south: [{n:"Meenakshi",m:"Goddess of Madurai"},{n:"Meena",m:"A precious gem, fish"},{n:"Meenambal",m:"Goddess of the fish eyes"},{n:"Meena Sundari",m:"Beautiful like a gem"},{n:"Meerabai",m:"Devoted princess"}], north: [{n:"Meera",m:"Devout princess"},{n:"Misha",m:"Sweet smile"},{n:"Minal",m:"Precious gem"},{n:"Mitali",m:"Friendship"},{n:"Mitanshi",m:"A friendly soul"}] } },
  "மூ": { M: { south: [{n:"Moorthy",m:"Divine form"},{n:"Moovendan",m:"Three mighty kings"},{n:"Moovarasan",m:"King of the three realms"},{n:"Mookan",m:"Feather, beautiful"}], north: [{n:"Mukesh",m:"Lord of liberation"},{n:"Mukund",m:"Lord Krishna"},{n:"Mukul",m:"Budding blossom"},{n:"Muneesh",m:"Great sage"}] }, F: { south: [{n:"Mookambika",m:"Goddess of Kollur"},{n:"Mookambal",m:"The Goddess mother"},{n:"Mookambigai",m:"Goddess of Kollur"},{n:"Mudhumathi",m:"Of ancient wisdom"}], north: [{n:"Mukta",m:"Liberated soul"},{n:"Mukti",m:"Liberation"},{n:"Mukulika",m:"Blossoming jasmine"},{n:"Mudrika",m:"A sacred ring"}] } },
  "மே": { M: { south: [{n:"Meiyappan",m:"Lord Ayyappa"},{n:"Meikandan",m:"Lord Murugan"},{n:"Meiyalagan",m:"Truly handsome"},{n:"Meghanathan",m:"Lord of the clouds"},{n:"Megharajan",m:"King of the clouds"},{n:"Meyyappan",m:"Lord Ayyappa"}], north: [{n:"Mehul",m:"Rain cloud"},{n:"Mayank",m:"The moon"},{n:"Medhansh",m:"A wise part"},{n:"Meghdoot",m:"Messenger of the clouds"}] }, F: { south: [{n:"Meghala",m:"Goddess Parvati"},{n:"Meghana",m:"Cloud-like, graceful"},{n:"Meghavathi",m:"Full of clouds"}], north: [{n:"Meghna",m:"Cloud, holy river"},{n:"Medha",m:"Intelligence, wisdom"},{n:"Mekhala",m:"Goddess Durga's waistband"},{n:"Mehar",m:"Grace, kindness"},{n:"Menka",m:"A celestial beauty"}] } },
  "மோ": { M: { south: [{n:"Mohan",m:"Charming, Lord Krishna"},{n:"Mohanraj",m:"Charming king"},{n:"Mohandoss",m:"A devotee of Krishna"},{n:"Mohankumar",m:"Charming prince"},{n:"Mohanasundaram",m:"Beautiful and charming"}], north: [{n:"Mohit",m:"Attracted, charming"},{n:"Mohak",m:"Charming"},{n:"Mohnish",m:"A charming sage"}] }, F: { south: [{n:"Mohana",m:"Charming, beautiful"},{n:"Mohanapriya",m:"Charming and dear"},{n:"Mohini",m:"An enchantress"}], north: [{n:"Mohita",m:"Attracted, charmed"},{n:"Mohisha",m:"Charming woman"},{n:"Moksha",m:"Liberation, salvation"}] } },
  "பா": { M: { south: [{n:"Pandian",m:"Ancient Pandya king"},{n:"Parthiban",m:"Arjuna, son of Pritha"},{n:"Palanisamy",m:"Lord Murugan"},{n:"Pandurangan",m:"Lord Vithoba"},{n:"Pandidurai",m:"Righteous chief"},{n:"Palanivel",m:"Lord Murugan's spear"},{n:"Parasuraman",m:"Lord Vishnu's axe-bearer"},{n:"Pandiarajan",m:"Pandya king"},{n:"Palavesam",m:"Auspicious"}], north: [{n:"Parth",m:"Arjuna"},{n:"Pankaj",m:"Lotus"},{n:"Paresh",m:"Supreme Lord"},{n:"Pavan",m:"Wind, breeze"},{n:"Paritosh",m:"Deep satisfaction"},{n:"Bhavesh",m:"Lord of the world"},{n:"Pranav",m:"The sacred syllable Om"},{n:"Prakash",m:"Light, radiance"},{n:"Prashant",m:"Calm and peaceful"}] }, F: { south: [{n:"Padmavathi",m:"Goddess Lakshmi"},{n:"Parvathi",m:"Goddess Parvati"},{n:"Pavithra",m:"Pure and sacred"},{n:"Padmini",m:"Lotus-eyed woman"},{n:"Panchali",m:"Draupadi"},{n:"Pavai",m:"A graceful girl"},{n:"Padmalaya",m:"Lotus abode"}], north: [{n:"Pallavi",m:"A budding leaf, verse"},{n:"Pari",m:"A fairy, angel"},{n:"Parul",m:"A flower"},{n:"Pankhudi",m:"A flower petal"},{n:"Paridhi",m:"The horizon"},{n:"Palak",m:"Graceful and lovely"},{n:"Bhavika",m:"Cheerful and happy"},{n:"Bhavisha",m:"The future"},{n:"Prachi",m:"The east"}] } },
  "பீ": { M: { south: [{n:"Peethambaran",m:"Lord Krishna"},{n:"Peethambaram",m:"Yellow silk garment"},{n:"Bheeman",m:"Bhima, the mighty"},{n:"Peeyush",m:"Nectar of the gods"}], north: [{n:"Bheem",m:"Mighty and strong"},{n:"Piyush",m:"Nectar, ambrosia"},{n:"Bhishma",m:"The vow-keeper"},{n:"Bittu",m:"A little darling"}] }, F: { south: [{n:"Peethambari",m:"A yellow-clad goddess"},{n:"Beena",m:"A stringed instrument"},{n:"Beena Devi",m:"Melodious goddess"}], north: [{n:"Pihu",m:"A little cuckoo"},{n:"Piya",m:"Beloved"},{n:"Bindiya",m:"A small dot, drop"}] } },
  "பூ": { M: { south: [{n:"Poovarasan",m:"King of flowers"},{n:"Bhoopalan",m:"King of the earth"},{n:"Bhoominathan",m:"Lord of the earth"},{n:"Poornachandran",m:"The full moon"},{n:"Poornananthan",m:"Complete joy"},{n:"Poongundran",m:"Lord of flowers"}], north: [{n:"Bhuvan",m:"The world"},{n:"Bhupendra",m:"King of the earth"},{n:"Bhupesh",m:"Lord of the earth"},{n:"Poornachandra",m:"The full moon"},{n:"Bhunesh",m:"Lord of the world"}] }, F: { south: [{n:"Poonguzhali",m:"A flower creeper"},{n:"Poonkodi",m:"A flowering creeper"},{n:"Poornima",m:"The full moon night"},{n:"Poovizhi",m:"Flower-like eyes"},{n:"Bhuvaneswari",m:"Goddess of the world"},{n:"Poongothai",m:"A fragrant flower"}], north: [{n:"Pooja",m:"Worship, prayer"},{n:"Poonam",m:"The full moon"},{n:"Bhumika",m:"The earth"},{n:"Bhuvana",m:"The world"},{n:"Poorvi",m:"A pleasant eastern melody"}] } },
  "ஷா": { M: { south: [{n:"Shanmugam",m:"Lord Murugan"},{n:"Shankar",m:"Lord Shiva"},{n:"Shanthakumar",m:"A peaceful prince"},{n:"Shanmugaraj",m:"Lord Murugan"},{n:"Shanmuganathan",m:"Lord Murugan"},{n:"Sharvendran",m:"A great Lord"}], north: [{n:"Shaan",m:"Pride and glory"},{n:"Shashank",m:"The moon"},{n:"Shantanu",m:"A peaceful king"},{n:"Shaurya",m:"Valour and bravery"},{n:"Shakti",m:"Divine power"}] }, F: { south: [{n:"Shanthi",m:"Peace"},{n:"Shakunthala",m:"A bird, a heroine"},{n:"Sharmila",m:"A shy, modest woman"},{n:"Shalini",m:"Modest and graceful"},{n:"Shanmugapriya",m:"Beloved of Lord Murugan"}], north: [{n:"Shatakshi",m:"A hundred-eyed goddess"},{n:"Shagun",m:"Auspicious omen"},{n:"Shashi",m:"The moon"},{n:"Shaila",m:"Goddess of the mountains"},{n:"Sharda",m:"Goddess Saraswati"},{n:"Shanta",m:"Peaceful and calm"},{n:"Shachi",m:"Consort of Indra"}] } },
  "ணா": { M: { south: [{n:"Nandhivarman",m:"A noble king"}], north: [] }, F: { south: [{n:"Nandhini",m:"A joyful daughter"}], north: [] } },
  "பே": { M: { south: [{n:"Pethan",m:"Beloved of the village"}], north: [{n:"Bhairav",m:"Lord Shiva"},{n:"Bheru",m:"A friend"}] }, F: { south: [{n:"Pechiammal",m:"Graceful village goddess"},{n:"Pechi",m:"A friendly girl"}], north: [] } },
  "போ": { M: { south: [], north: [{n:"Bholenath",m:"Lord Shiva"},{n:"Bholesh",m:"Lord Shiva"}] }, F: { south: [{n:"Ponni",m:"A sacred river"}], north: [{n:"Bholi",m:"Simple and innocent"}] } },
  "ரா": { M: { south: [{n:"Raman",m:"Lord Rama, delightful"},{n:"Rajan",m:"A king, Lord Shiva"},{n:"Raghavan",m:"A descendant of Raghu"},{n:"Ravichandran",m:"Sun and moon"},{n:"Ramakrishnan",m:"Lord Rama and Krishna"},{n:"Rajendran",m:"King of kings"},{n:"Ramachandran",m:"The delightful moon"},{n:"Rajarajan",m:"The great emperor"},{n:"Raam",m:"Lord Rama"}], north: [{n:"Raj",m:"A king"},{n:"Rahul",m:"Efficient and able"},{n:"Rajesh",m:"Lord of kings"},{n:"Ramesh",m:"Lord of Rama"},{n:"Raghav",m:"Lord Rama"},{n:"Ranveer",m:"Brave in battle"},{n:"Rakesh",m:"Lord of the full moon"},{n:"Ravi",m:"The Sun"}] }, F: { south: [{n:"Rajalakshmi",m:"Goddess of royal fortune"},{n:"Rajeshwari",m:"Goddess of kings"},{n:"Ramya",m:"Beautiful and charming"},{n:"Rathi",m:"The charioteer of love"},{n:"Ranjani",m:"A melodious night"},{n:"Rani",m:"A queen"},{n:"Radhika",m:"A devoted gopi"},{n:"Rajathi",m:"A royal queen"}], north: [{n:"Rashi",m:"A collection, zodiac"},{n:"Ranjana",m:"Entertaining, charming"},{n:"Rakhi",m:"A sacred thread"},{n:"Rashmi",m:"A ray of light"},{n:"Rachana",m:"Creation, composition"}] } },
  "ரீ": { M: { south: [{n:"Rithik",m:"Prosperous and learned"},{n:"Rithish",m:"Lord of truth"},{n:"Rishikesan",m:"Lord Vishnu"},{n:"Rishi",m:"A sage, a seer"},{n:"Rishabhan",m:"The noble bull"},{n:"Rithwikan",m:"An ancient sage"}], north: [{n:"Rishabh",m:"The best, a bull"},{n:"Rishikesh",m:"Lord Vishnu"},{n:"Ritvik",m:"A learned priest"},{n:"Ridhaan",m:"Pleasing and kind"},{n:"Ritul",m:"A season"},{n:"Ritesh",m:"Lord of truth"},{n:"Rishit",m:"The best, celebrated"}] }, F: { south: [{n:"Rithika",m:"A stream of water"},{n:"Rithanya",m:"Righteous and cheerful"},{n:"Rishitha",m:"A sage-like woman"},{n:"Rithikaa",m:"A stream, graceful"}], north: [{n:"Riya",m:"Singer, graceful"},{n:"Riddhi",m:"Prosperity and growth"},{n:"Ritika",m:"A stream of water"},{n:"Ridhima",m:"Beautiful and kind"},{n:"Rishika",m:"A sage-like girl"},{n:"Ritu",m:"A season"}] } },
  "ரூ": { M: { south: [{n:"Rudhran",m:"The fierce Lord Shiva"},{n:"Rudhramoorthy",m:"Divine form of Lord Shiva"},{n:"Rupan",m:"Handsome and graceful"},{n:"Rukesh",m:"Lord of the moon"}], north: [{n:"Rupesh",m:"Rich in beauty"},{n:"Rudra",m:"The fierce Lord"},{n:"Ruhaan",m:"A spiritual soul"},{n:"Rudransh",m:"Part of Lord Shiva"}] }, F: { south: [{n:"Rukmini",m:"Consort of Lord Krishna"},{n:"Rudhra",m:"The fierce goddess"},{n:"Rupa",m:"Beauty and form"},{n:"Rupavathi",m:"Full of beauty"}], north: [{n:"Ruhi",m:"A soul, spirit"},{n:"Rupali",m:"Beautiful woman"},{n:"Ruhani",m:"Spiritual and divine"}] } },
  "ரே": { M: { south: [{n:"Rethinavel",m:"Lord Murugan's spear"},{n:"Rethik",m:"Full of love"},{n:"Renjith",m:"Coloured, delighted"},{n:"Revanth",m:"Radiant, son of the Sun"}], north: [{n:"Reyansh",m:"A part of the Sun"},{n:"Revansh",m:"Part of the sacred river Reva"}] }, F: { south: [{n:"Revathi",m:"A star of the zodiac"},{n:"Renuka",m:"Mother of Lord Parasurama"},{n:"Renugadevi",m:"Goddess Renuka"},{n:"Rethika",m:"A flowing river"}], north: [{n:"Rekha",m:"A line, a streak"},{n:"Reet",m:"Sacred tradition"},{n:"Reva",m:"A sacred river"}] } },
  "ரோ": { M: { south: [{n:"Rohith",m:"Radiant and splendid"},{n:"Roshan",m:"A bright light"},{n:"Rohinthan",m:"Lord of the moon"}], north: [{n:"Rohan",m:"Growing, ascending"},{n:"Rochak",m:"Interesting and pleasing"},{n:"Ronak",m:"A bright light"},{n:"Ronit",m:"Bright and charming"},{n:"Romil",m:"Lovable and charming"}] }, F: { south: [{n:"Rohini",m:"An auspicious star"},{n:"Roshini",m:"A bright ray of light"},{n:"Roshni",m:"Radiance, light"}], north: [{n:"Ronika",m:"A bright light"},{n:"Roshika",m:"Radiant and lovely"},{n:"Rohita",m:"One who is red, dear"}] } },
  "தா": { M: { south: [{n:"Tharun",m:"Youthful and bright"},{n:"Thangaraj",m:"King of gold"},{n:"Thangavel",m:"Lord Murugan"},{n:"Thamizharasan",m:"King of Tamil"},{n:"Dhanasekaran",m:"Lord of wealth"},{n:"Dharanidharan",m:"Lord who upholds the earth"},{n:"Thavamani",m:"Jewel of penance"},{n:"Thamodaran",m:"Lord Krishna"},{n:"Thayumanavan",m:"The compassionate Lord"}], north: [{n:"Tapan",m:"The radiant Sun"},{n:"Dhanush",m:"The bow of Lord Rama"}] }, F: { south: [{n:"Thamarai",m:"Lotus flower"},{n:"Thangam",m:"Gold, precious"},{n:"Thangamalar",m:"Golden flower"},{n:"Tharani",m:"The earth"},{n:"Thara",m:"Star, Tara"},{n:"Dhanalakshmi",m:"Goddess of wealth"},{n:"Dharani",m:"The earth"},{n:"Dharshini",m:"Lord of the sight"}], north: [{n:"Tarini",m:"Saviour goddess"},{n:"Dhara",m:"The earth, a stream"},{n:"Dhanya",m:"Great, blessed"},{n:"Dhanvi",m:"Wealthy"},{n:"Tanvi",m:"Slender and beautiful"}] } },
  "தீ": { M: { south: [{n:"Theerthan",m:"Devoted and pure"},{n:"Theeban",m:"Bright and shining"},{n:"Theekshan",m:"Sharp-witted"},{n:"Theerthagiri",m:"Sacred hill"},{n:"Dheenadayalan",m:"Compassionate giver"}], north: [{n:"Dheeraj",m:"Patience and courage"},{n:"Dhiraj",m:"Steady and brave"},{n:"Dheeman",m:"Intelligent and wise"},{n:"Dhir",m:"Courageous"},{n:"Theerth",m:"Sacred pilgrimage"}] }, F: { south: [{n:"Theertha",m:"Sacred water"},{n:"Theekshana",m:"Sharp-witted girl"},{n:"Dheekshika",m:"Sacred initiation"},{n:"Thilagavathi",m:"Goddess Lakshmi"}], north: [{n:"Divyanshi",m:"Part of divine light"},{n:"Dhriti",m:"Patience and courage"},{n:"Dheera",m:"Wisdom and courage"},{n:"Dhiya",m:"A divine light"}] } },
  "தூ": { M: { south: [{n:"Thulasiraman",m:"Lord Rama of the Tulsi"},{n:"Thulasidharan",m:"One who wears the Tulsi"},{n:"Thooran",m:"A learned poet"},{n:"Thuyavan",m:"Pure and clear"},{n:"Thulasi",m:"Sacred basil"}], north: [{n:"Dushyant",m:"Destroyer of evil"},{n:"Durgesh",m:"Lord of the fort"},{n:"Dhruv",m:"The pole star"}] }, F: { south: [{n:"Thulasi",m:"Sacred basil plant"},{n:"Thulir",m:"A tender new leaf"},{n:"Thulasi Priya",m:"Beloved of the Tulsi"}], north: [{n:"Durga",m:"Goddess Durga"},{n:"Duhita",m:"Daughter"},{n:"Dushyanta",m:"A noble king"},{n:"Tulika",m:"A fine paintbrush"}] } },
  "தே": { M: { south: [{n:"Thendralan",m:"Gentle breeze"},{n:"Thevan",m:"God, divine one"},{n:"Thevakumar",m:"Divine prince"},{n:"Thevaraj",m:"Divine king"},{n:"Thevaguru",m:"Divine teacher"},{n:"Dhayalan",m:"The compassionate Lord"}], north: [{n:"Tejas",m:"Radiance, brilliance"},{n:"Tej",m:"Radiance, light"},{n:"Teyjas",m:"Full of light"},{n:"Dev",m:"God, divine"}] }, F: { south: [{n:"Thenmozhi",m:"Sweet-spoken"},{n:"Thendral",m:"Gentle breeze"},{n:"Thejaswini",m:"Full of radiance"},{n:"Devagi",m:"Mother of Krishna"},{n:"Deivanayaki",m:"Divine queen"}], north: [{n:"Tejaswi",m:"Full of radiance"},{n:"Tejaswini",m:"Full of radiance"},{n:"Tesha",m:"A star"},{n:"Devna",m:"Divine blessing"},{n:"Tejal",m:"Radiance, glow"}] } },
  "தோ": { M: { south: [{n:"Tholkappiyan",m:"Ancient Tamil scholar"},{n:"Thooyavan",m:"Pure and sacred"},{n:"Tholkappiyar",m:"The great Tamil grammarian"},{n:"Tholan",m:"An ancient poet"},{n:"Thozhan",m:"Friend and companion"}], north: [{n:"Dorian",m:"Beloved"}] }, F: { south: [{n:"Thooyamathi",m:"Pure and wise"},{n:"Thozhi",m:"Friend"}], north: [{n:"Dorita",m:"A gift of God"},{n:"Toral",m:"A garland, toran"}] } },
  "நா": { M: { south: [{n:"Naveen",m:"Bright and new"},{n:"Nandakumar",m:"Lord Krishna's son"},{n:"Natarajan",m:"Lord of the cosmic dance"},{n:"Nagarajan",m:"King of serpents"},{n:"Nallasivam",m:"The auspicious Shiva"},{n:"Naganathan",m:"Lord of serpents"},{n:"Naavalan",m:"Eloquent and learned"},{n:"Nambirajan",m:"Lord Vishnu"},{n:"Narendran",m:"King of men"},{n:"Navaneethan",m:"Fresh butter, Krishna"},{n:"Nachiappan",m:"Lord Nataraja"}], north: [{n:"Nakul",m:"The fourth Pandava"},{n:"Naksh",m:"A star"},{n:"Naman",m:"A respectful salutation"},{n:"Nandan",m:"A son, joyful"},{n:"Naren",m:"Lord Narayana"},{n:"Naresh",m:"King of men"},{n:"Navin",m:"New, fresh"},{n:"Naithik",m:"Moral, righteous"}] }, F: { south: [{n:"Nandhini",m:"A daughter, joyful"},{n:"Nalini",m:"A lotus flower"},{n:"Narmadha",m:"A sacred river"},{n:"Nandhitha",m:"Joyful, pleased"},{n:"Nagavalli",m:"A snake goddess"},{n:"Nalayini",m:"A lotus-eyed beauty"},{n:"Nappinnai",m:"Consort of Lord Krishna"},{n:"Nangai",m:"Respected lady"}], north: [{n:"Nandini",m:"A daughter, cheerful"},{n:"Naina",m:"The eyes"},{n:"Nandita",m:"Cheerful and happy"},{n:"Nayanika",m:"Eyes, a guide"},{n:"Namrata",m:"Humility and modesty"},{n:"Navya",m:"New, young"},{n:"Navika",m:"A boat, young girl"},{n:"Namita",m:"Modest and humble"},{n:"Nandika",m:"A little daughter"}] } },
  "நீ": { M: { south: [{n:"Nithyanandhan",m:"Eternal bliss"},{n:"Nithilan",m:"Full of virtue"},{n:"Niranjan",m:"The spotless Lord"},{n:"Nivethan",m:"An offering to God"},{n:"Nithish",m:"Lord of the night"},{n:"Neelakandan",m:"Lord Shiva, blue-throated"}], north: [{n:"Nikhil",m:"Complete, whole"},{n:"Nitesh",m:"Lord of law, master"},{n:"Nipun",m:"Skilled and dexterous"},{n:"Nirav",m:"Quiet and calm"},{n:"Nihal",m:"Rain cloud"},{n:"Niraj",m:"The lotus flower"},{n:"Nishant",m:"Dawn, ending of night"},{n:"Nishith",m:"Night, Lord Shiva"}] }, F: { south: [{n:"Nithya",m:"Eternal, constant"},{n:"Nivedha",m:"An offering"},{n:"Niranjani",m:"The spotless goddess"},{n:"Nila",m:"Blue, the moon"},{n:"Neelambal",m:"Blue-throated goddess"},{n:"Nithila",m:"Beautiful"},{n:"Nithyashree",m:"Eternal prosperity"},{n:"Nivedhitha",m:"Dedicated offering"}], north: [{n:"Nisha",m:"Night"},{n:"Nidhi",m:"A treasure"},{n:"Niharika",m:"A misty shower"},{n:"Niyati",m:"Destiny, fate"},{n:"Nivedita",m:"Dedicated, offered"},{n:"Nikita",m:"Unconquered, victorious"},{n:"Nimisha",m:"A blink of the eye"}] } },
  "நூ": { M: { south: [{n:"Nuthan",m:"Fresh and new"},{n:"Noothan",m:"New, fresh"}], north: [{n:"Nutan",m:"New and unique"},{n:"Nupur",m:"Anklet"}] }, F: { south: [{n:"Nuthana",m:"New and fresh"},{n:"Nuthana Sri",m:"Fresh and prosperous"},{n:"Noothana",m:"New, ever fresh"}], north: [{n:"Nutan",m:"New, fresh"},{n:"Nupur",m:"An anklet"},{n:"Nuha",m:"A wise young woman"}] } },
  "நே": { M: { south: [{n:"Nedunchezhiyan",m:"The ancient Tamil king"},{n:"Nethaji",m:"The great leader"},{n:"Nesan",m:"A dear friend"},{n:"Nesamani",m:"A friendly leader"},{n:"Nedumanan",m:"Wise and noble"}], north: [{n:"Nayan",m:"The eyes"},{n:"Neminath",m:"A revered Jain saint"},{n:"Netesh",m:"A leader"}] }, F: { south: [{n:"Nethra",m:"The eyes"},{n:"Nethira",m:"A beautiful eyed girl"},{n:"Nesari",m:"Graceful friend"}], north: [{n:"Neha",m:"Love and affection"},{n:"Nehal",m:"A lovely girl"},{n:"Netra",m:"The eyes"}] } },
  "நோ": { M: { south: [], north: [{n:"Nohit",m:"Much praised"}] }, F: { south: [], north: [{n:"Norika",m:"Graceful"}] } },
  "யா": { M: { south: [{n:"Yathavan",m:"Lord Krishna"},{n:"Yaazh",m:"The ancient lute"},{n:"Yalavan",m:"Skilled musician"}], north: [{n:"Yash",m:"Fame and glory"},{n:"Yashwant",m:"Full of glory"},{n:"Yashraj",m:"King of glory"},{n:"Yatin",m:"A sage, ascetic"},{n:"Yadvendra",m:"Lord of the Yadavas"},{n:"Yateendra",m:"Lord of ascetics"}] }, F: { south: [{n:"Yaazhini",m:"Song of the lute"},{n:"Yamini",m:"A serene night"},{n:"Yashodha",m:"Mother of Lord Krishna"},{n:"Yamuna",m:"A sacred river"}], north: [{n:"Yashvi",m:"Fame and success"},{n:"Yashika",m:"Famous and successful"},{n:"Yashaswini",m:"Full of fame"},{n:"Yami",m:"The Yamuna river"},{n:"Yashoda",m:"Mother of Lord Krishna"}] } },
  "யீ": { M: { south: [{n:"Yeeshwaran",m:"Lord of glory"}], north: [{n:"Yihan",m:"A friendly soul"}] }, F: { south: [], north: [] } },
  "யூ": { M: { south: [{n:"Yuvan",m:"Youthful and bright"},{n:"Yugan",m:"An era, united"},{n:"Yugendran",m:"King of the ages"},{n:"Yuthishthiran",m:"The righteous king"}], north: [{n:"Yuvraj",m:"A crown prince"},{n:"Yug",m:"An era, age"},{n:"Yudhvir",m:"Brave in battle"},{n:"Yudhishthir",m:"The righteous king"}] }, F: { south: [{n:"Yuvasri",m:"Youthful prosperity"},{n:"Yuvathi",m:"A young woman"},{n:"Yuvanika",m:"Youthful and graceful"},{n:"Yuktha",m:"United, suited"}], north: [{n:"Yukti",m:"Skill and reasoning"},{n:"Yukta",m:"United, capable"},{n:"Yuvika",m:"A young girl"}] } },
  "யே": { M: { south: [{n:"Yegappan",m:"A famous Tamil name"},{n:"Yegnesh",m:"Lord of the sacred fire"}], north: [{n:"Yeyash",m:"Glory and success"}] }, F: { south: [{n:"Yegammai",m:"Tamil goddess name"}], north: [{n:"Yesha",m:"Fame and grace"},{n:"Yeshika",m:"Full of fame"},{n:"Yeshaswini",m:"Full of fame"},{n:"Yeshita",m:"Achieved, successful"}] } },
  "யோ": { M: { south: [{n:"Yogendran",m:"Lord of yoga"},{n:"Yogarasan",m:"A king of yoga"},{n:"Yogi",m:"A yogi, ascetic"},{n:"Yogeshwaran",m:"Lord of yoga"}], north: [{n:"Yogesh",m:"Lord of yoga"},{n:"Yogendra",m:"Lord of yoga"}] }, F: { south: [{n:"Yogalakshmi",m:"Goddess of yoga"},{n:"Yogitha",m:"One who is united"},{n:"Yogini",m:"A female ascetic"}], north: [{n:"Yogita",m:"Focused, united"},{n:"Yogeswari",m:"Goddess of yoga"}] } },
  "ஜா": { M: { south: [{n:"Jagan",m:"The world"},{n:"Jagannathan",m:"Lord of the world"},{n:"Jayakumar",m:"A victorious prince"},{n:"Jayapalan",m:"A victorious protector"},{n:"Jagadheesan",m:"Lord of the universe"},{n:"Jambulingam",m:"Lord Shiva"},{n:"Jayanthan",m:"The victorious one"}], north: [{n:"Jagdish",m:"Lord of the world"},{n:"Jai",m:"Victory"},{n:"Jayant",m:"Victorious"},{n:"Jagat",m:"The universe"},{n:"Jairaj",m:"Victorious king"},{n:"Jatin",m:"A disciplined ascetic"}] }, F: { south: [{n:"Janaki",m:"Sita, daughter of Janaka"},{n:"Jayanthi",m:"A victorious festival"},{n:"Jaya",m:"Victory"},{n:"Janani",m:"A mother, creator"},{n:"Jayalakshmi",m:"Goddess of victory"},{n:"Jayasudha",m:"Nectar of victory"}], north: [{n:"Janhvi",m:"A sacred river"},{n:"Jagruti",m:"Awakening, awareness"},{n:"Jayshree",m:"Goddess of victory"}] } },
  "ஜீ": { M: { south: [{n:"Jeevan",m:"Life"},{n:"Jeevananthan",m:"Life and joy"},{n:"Jeevagan",m:"The living soul"},{n:"Jeevithan",m:"Full of life"}], north: [{n:"Jitendra",m:"Lord of victory"},{n:"Jitesh",m:"Lord of victory"},{n:"Jignesh",m:"A curious soul"},{n:"Jishnu",m:"Lord Vishnu"},{n:"Jivin",m:"Full of life"}] }, F: { south: [{n:"Jeevitha",m:"Life and vitality"},{n:"Jeevalakshmi",m:"Living goddess of fortune"},{n:"Jeevanya",m:"Full of life"}], north: [{n:"Jiya",m:"A sweet heart"},{n:"Jinal",m:"A precious gem"},{n:"Jivika",m:"Full of life"}] } },
  "கூ": { M: { south: [{n:"Guhan",m:"Lord Murugan"},{n:"Gunasekaran",m:"Virtuous Lord Shiva"},{n:"Gurunathan",m:"Divine teacher"},{n:"Gunalan",m:"Full of virtue"},{n:"Guruprasad",m:"Blessed by the guru"}], north: [{n:"Gurdeep",m:"Light of the guru"},{n:"Gurudutt",m:"Granted by the guru"},{n:"Gunwant",m:"Full of virtue"},{n:"Guptesh",m:"Hidden Lord"},{n:"Gulshan",m:"Flower garden"},{n:"Gunvant",m:"Full of virtues"}] }, F: { south: [{n:"Kuzhali",m:"A melodious flute"},{n:"Kuzhalini",m:"Sweet-voiced"},{n:"Gunavathy",m:"Full of virtue"},{n:"Kuyili",m:"Tamil warrior, courage"}], north: [{n:"Gunjita",m:"Softly humming"},{n:"Gulika",m:"A celestial star"},{n:"Guneet",m:"Full of virtue"},{n:"Gunjan",m:"Soft humming, song"},{n:"Gunita",m:"Endowed with virtues"}] } },
  "சா": { M: { south: [{n:"Sakthivel",m:"Lord Murugan, powerful"},{n:"Santhosh",m:"Contentment, joy"},{n:"Sampath",m:"Prosperity, wealth"},{n:"Sathyan",m:"Truthful"},{n:"Sakthi",m:"Divine power"},{n:"Sadhasivam",m:"Lord Shiva, ever good"},{n:"Sanjeevan",m:"One who gives life"},{n:"Santhanakrishnan",m:"Lord Krishna"},{n:"Sankaran",m:"Lord Shiva"},{n:"Sarangan",m:"Lord Vishnu"}], north: [{n:"Saarthak",m:"Meaningful, purposeful"},{n:"Sachin",m:"Pure, truthful"},{n:"Sagar",m:"Ocean"},{n:"Sahil",m:"Leader, guide"},{n:"Samar",m:"Companion in battle"},{n:"Sanjay",m:"Victorious"},{n:"Satvik",m:"Pure and virtuous"},{n:"Sanket",m:"Signal, sacred hint"},{n:"Sarthak",m:"Accomplished"}] }, F: { south: [{n:"Santhi",m:"Peace, tranquillity"},{n:"Sandhya",m:"Evening twilight"},{n:"Sangeetha",m:"Music, melody"},{n:"Savitha",m:"The Sun"},{n:"Sasirekha",m:"Beautiful crescent"},{n:"Santhiya",m:"Peaceful"},{n:"Sathya",m:"Truth"},{n:"Sakthipriya",m:"Beloved of the goddess"},{n:"Samundeeswari",m:"Goddess of the ocean"}], north: [{n:"Sanjana",m:"Gentle, soft-spoken"},{n:"Saanvi",m:"Goddess Lakshmi"},{n:"Sakshi",m:"Witness, evidence"},{n:"Sanya",m:"Distinguished"},{n:"Sarika",m:"Thrush bird, melodious"},{n:"Sadhana",m:"Devoted practice"},{n:"Sanika",m:"Gracious"},{n:"Saumya",m:"Gentle and graceful"},{n:"Sahana",m:"Melodic, patient"},{n:"Sameera",m:"Early morning breeze"}] } },
  "சீ": { M: { south: [{n:"Sivakumar",m:"Lord Shiva"},{n:"Sivanesan",m:"Lord Shiva"},{n:"Sivaraman",m:"Lord Shiva, delightful"},{n:"Sivaguru",m:"Lord Shiva"},{n:"Siddharth",m:"One who has attained"},{n:"Chidambaram",m:"Lord Nataraja"},{n:"Chinmayan",m:"Full of consciousness"},{n:"Sivaprakash",m:"Light of Lord Shiva"},{n:"Sitharthan",m:"Accomplished one"},{n:"Sivakumaran",m:"Beloved of Shiva"}], north: [{n:"Chirag",m:"Lamp, bright light"},{n:"Shivam",m:"Auspicious, Lord Shiva"},{n:"Shivansh",m:"Part of Lord Shiva"},{n:"Chiranjeev",m:"Long-lived"},{n:"Shivendra",m:"Lord of Lord Shiva"},{n:"Siddhant",m:"Doctrine, principle"},{n:"Sidhak",m:"Perfected"},{n:"Shivank",m:"Mark of Lord Shiva"},{n:"Siddhesh",m:"Lord of the accomplished"}] }, F: { south: [{n:"Sivagami",m:"Consort of Lord Shiva"},{n:"Sivaranjani",m:"Divine melody"},{n:"Sindhu",m:"Ocean, river"},{n:"Sithara",m:"Star, morning star"},{n:"Chitra",m:"Painting, art"},{n:"Sivasakthi",m:"Power of Lord Shiva"},{n:"Sindhuja",m:"Born of the ocean"},{n:"Sivapriya",m:"Beloved of Lord Shiva"},{n:"Sitharani",m:"Queen of stars"},{n:"Chinmayi",m:"Full of consciousness"}], north: [{n:"Shivani",m:"Consort of Lord Shiva"},{n:"Siddhi",m:"Perfection, attainment"},{n:"Shikha",m:"Flame, crest"},{n:"Shivi",m:"Kind, benevolent"},{n:"Siya",m:"Blessed, divine"},{n:"Shivangi",m:"Beautiful Goddess"},{n:"Chitrangana",m:"Beautiful art"},{n:"Shivpriya",m:"Beloved of Lord Shiva"},{n:"Chitralekha",m:"Beautiful picture"}] } },
  "சூ": { M: { south: [{n:"Surya",m:"The Sun"},{n:"Sooryanarayanan",m:"Sun-like Lord Vishnu"},{n:"Suryakumar",m:"Sun prince"},{n:"Suryaprakash",m:"Light of the Sun"},{n:"Sooriyan",m:"The Sun god"},{n:"Suryadevan",m:"Sun god"}], north: [{n:"Sooraj",m:"Radiant sun"},{n:"Suryansh",m:"Part of the Sun"},{n:"Suryakant",m:"Sun's beloved"},{n:"Suryaveer",m:"Brave as the Sun"},{n:"Suryadeep",m:"Lamp of the Sun"}] }, F: { south: [{n:"Soorya",m:"Sun, radiant"},{n:"Suryakala",m:"Art of the Sun"},{n:"Suryavathi",m:"Sun-like brightness"},{n:"Sooriyakumari",m:"Sun princess"},{n:"Suryaprabha",m:"Sunlight"}], north: [{n:"Suryanshi",m:"Ray of the Sun"},{n:"Suhani",m:"Pleasant and lovely"},{n:"Sunaina",m:"Beautiful-eyed"},{n:"Suruchi",m:"Good taste, refined"},{n:"Sushri",m:"Very auspicious"},{n:"Suchita",m:"Pure in mind"}] } },
  "த": { M: { south: [{n:"Thamizhselvan",m:"Mighty Tamil scholar"},{n:"Thandapani",m:"Lord Shiva"},{n:"Thambidurai",m:"Lord of the family"},{n:"Thangaraju",m:"Golden king"},{n:"Thavam",m:"Penance, devotion"}], north: [{n:"Thaman",m:"Beloved"},{n:"Thakur",m:"A leader"},{n:"Tanmay",m:"Absorbed in the divine"},{n:"Tarak",m:"A star, protector"},{n:"Tanish",m:"Lord of the night"},{n:"Tanuj",m:"A beloved son"}] }, F: { south: [{n:"Thamizhselvi",m:"Graceful Tamil girl"},{n:"Thamizharasi",m:"Queen of Tamil"},{n:"Thangammal",m:"Golden lady"},{n:"Thavamalar",m:"Flower of penance"},{n:"Thamizhini",m:"Sweet Tamil maiden"}], north: [{n:"Thara",m:"Star"},{n:"Thakshvi",m:"A graceful swan"},{n:"Tanishka",m:"A small star"},{n:"Tanya",m:"A fairy queen"},{n:"Taruna",m:"Young, tender"}] } },
  "ஜ": { M: { south: [], north: [] }, F: { south: [], north: [{n:"Jhalak",m:"A glimpse, sparkle"},{n:"Jhilmil",m:"A soft twinkle"}] } },
  "ஞ": { M: { south: [], north: [{n:"Trailokya",m:"The three worlds"},{n:"Trilok",m:"The three realms"},{n:"Trishank",m:"A noble king"}] }, F: { south: [{n:"Trisha",m:"A wish, desire"}], north: [{n:"Triveni",m:"Meeting of three rivers"}] } }
};
