/**
 * ASTRO SIVAM — PHP twin generator for the Birth Jathagam page 3 (Short Summary).
 *
 * The page-3 data and the ONE classification rule live in TypeScript
 * (src/services/jathagamDoshaData.ts + src/services/jathagamPlanetSummary.ts).
 * The mPDF renderer must print exactly the same lists, so this script emits the
 * PHP twin of that data and rule:
 *
 *   npx tsx scripts/emit-php-summary.ts > /tmp/summary-block.php
 *
 * and the emitted block replaces the region between the
 * `// BIRTH JATHAGAM - PAGE 3 (SHORT SUMMARY)` banner and the
 * `// MARRIAGE COMPATIBILITY - 1 PAGE HTML` marker inside
 * api/astrology/pdf_mpdf_reports.php's AstroReportViews class.
 *
 * Keep the two sides in sync: `tests/jathagam-summary-parity.test.php` (CI PHP)
 * and `tests/jathagam-summary-parity.test.ts` (Node) both check their engine
 * against tests/fixtures/jathagam-summary-parity.json, so any drift fails the
 * build on one side or the other.
 */
import {
  JATHAGAM_PLANET_PROFILES,
  NAVAGRAHA_DOSHA_DATA,
  NAVAGRAHA_ORDER,
  SHORT_SUMMARY_DONATION,
  SHORT_SUMMARY_LAMP_OIL,
  SHORT_SUMMARY_MANTRA,
  SHORT_SUMMARY_REMEDY_LABELS,
  SHORT_SUMMARY_TEXT,
  DoshaLanguage
} from '../src/services/jathagamDoshaData';
import { GRAHA_NAMES_REPORT } from '../src/services/jathagamHtmlBuilder';
import {
  EXALTATION_SIGN,
  OWN_SIGNS,
  SIGN_EXALTED_BY,
  SIGN_LORDS
} from '../src/lib/astrology/dignity';

const languages: DoshaLanguage[] = ['en', 'ta', 'hi'];

/** PHP single-quoted string literal. */
const q = (value: string): string => `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

/** One `'en' => '…', 'ta' => '…', 'hi' => '…'` group, one language per line. */
const triple = (values: Record<string, string>, indent: string, trailingComma = true): string =>
  languages
    .map((lang, index) => `${indent}${q(lang)} => ${q(values[lang] ?? '')}${index === languages.length - 1 && !trailingComma ? '' : ','}`)
    .join('\n');

const lines: string[] = [];
const push = (...parts: string[]) => lines.push(...parts);

push('    // =====================================================================');
push('    // BIRTH JATHAGAM - PAGE 3 (SHORT SUMMARY)');
push('    //');
push('    // Generated by `npx tsx scripts/emit-php-summary.ts` from');
push('    // src/services/jathagamDoshaData.ts and src/services/jathagamPlanetSummary.ts.');
push('    // Do not hand-edit: regenerate instead, and re-run the parity fixture');
push('    // (tests/fixtures/jathagam-summary-parity.json) on both stacks.');
push('    //');
push('    // The Short Summary is a plain-language readback of pages 1 and 2. Its');
push('    // supportive / needs-care lists come from ONE named rule mirrored from');
push('    // src/services/jathagamPlanetSummary.ts, and every remedy line reuses the');
push('    // report\'s existing Navagraha material (deity, weekday, charity) plus the');
push('    // additive lamp-oil and mantra fields. No second remedy system exists.');
push('    // =====================================================================');
push('');

// ---------------------------------------------------------------------------
// Data: names, deity/day/charity (existing reference table), lamp/mantra/
// donation (additive) and the plain-language support / difficulties lines.
// ---------------------------------------------------------------------------
push('    /**');
push('     * Per-graha page-3 material. `name`/`deity`/`day`/`charity` are the');
push('     * existing Navagraha reference entries; `lamp`/`mantra`/`donation`/');
push('     * `support`/`difficulties` are the additive Short Summary fields.');
push('     */');
push('    public static function jathagamSummaryRemedyData(): array');
push('    {');
push('        return [');
for (const key of NAVAGRAHA_ORDER) {
  const info = NAVAGRAHA_DOSHA_DATA[key];
  const profile = JATHAGAM_PLANET_PROFILES[key];
  push(`            ${q(key)} => [`);
  push(`                'name' => [`);
  push(triple(GRAHA_NAMES_REPORT[key] as unknown as Record<string, string>, '                    '));
  push(`                ],`);
  push(`                'deity' => [`);
  push(triple(info.deity as unknown as Record<string, string>, '                    '));
  push(`                ],`);
  push(`                'day' => [`);
  push(triple(info.day as unknown as Record<string, string>, '                    '));
  push(`                ],`);
  push(`                'charity' => [`);
  push(triple(info.charity as unknown as Record<string, string>, '                    '));
  push(`                ],`);
  push(`                'lamp' => [`);
  push(triple(SHORT_SUMMARY_LAMP_OIL[key], '                    '));
  push(`                ],`);
  push(`                'donation' => [`);
  push(triple(SHORT_SUMMARY_DONATION[key], '                    '));
  push(`                ],`);
  push(`                'mantra' => [`);
  push(triple(SHORT_SUMMARY_MANTRA[key], '                    '));
  push(`                ],`);
  push(`                'support' => [`);
  push(triple(profile.support, '                    '));
  push(`                ],`);
  push(`                'difficulties' => [`);
  push(triple(profile.difficulties, '                    '));
  push(`                ]`);
  push(`            ],`);
}
push('        ];');
push('    }');
push('');

// ---------------------------------------------------------------------------
// Data: every page-3 string, in the three languages (the renderer picks one).
// ---------------------------------------------------------------------------
const textKeys = Object.keys(SHORT_SUMMARY_TEXT.en);
const labelKeys = Object.keys(SHORT_SUMMARY_REMEDY_LABELS.en);
push('    /**');
push('     * Every fixed page-3 string, three languages. The renderer selects `$lang`,');
push('     * so a missing translation cannot silently fall back.');
push('     */');
push('    public static function jathagamSummaryText(string $lang): array');
push('    {');
push('        $lang = in_array($lang, [\'en\', \'ta\', \'hi\'], true) ? $lang : \'en\';');
push('        $text = [');
for (const key of textKeys) {
  push(`            ${q(key)} => [`);
  push(
    triple(
      Object.fromEntries(languages.map(lang => [lang, (SHORT_SUMMARY_TEXT[lang] as unknown as Record<string, string>)[key] ?? ''])),
      '                '
    )
  );
  push(`            ],`);
}
push('        ];');
push('        $labels = [');
for (const key of labelKeys) {
  push(`            ${q(key)} => [`);
  push(
    triple(
      Object.fromEntries(languages.map(lang => [lang, (SHORT_SUMMARY_REMEDY_LABELS[lang] as unknown as Record<string, string>)[key] ?? ''])),
      '                '
    )
  );
  push(`            ],`);
}
push('        ];');
push('        $outText = [];');
push('        foreach ($text as $key => $values) { $outText[$key] = $values[$lang] ?? \'\'; }');
push('        $outLabels = [];');
push('        foreach ($labels as $key => $values) { $outLabels[$key] = $values[$lang] ?? \'\'; }');
push('        return [\'text\' => $outText, \'labels\' => $outLabels];');
push('    }');
push('');

// ---------------------------------------------------------------------------
// The ONE rule, mirrored statement-for-statement from the TypeScript module.
// ---------------------------------------------------------------------------
push('    /**');
push('     * The ONE Birth Jathagam page-3 rule, mirrored statement-for-statement');
push('     * from src/services/jathagamPlanetSummary.ts::classifyJathagamPlanetsForSummary().');
push('     *');
push('     * Same dignity tables (src/lib/astrology/dignity.ts == AstroEngine::planetDignityTable()),');
push('     * same houses, same 10-degree conjunction orb, same scoring, same ordering.');
push('     * tests/fixtures/jathagam-summary-parity.json holds the outputs both stacks');
push('     * must reproduce.');
push('     *');
push('     * @return array{supportive: list<array{key: string, house: ?int, support: string}>,');
push('     *               needsCare: list<array<string, mixed>>, compact: bool,');
push('     *               assessedCount: int, assessmentComplete: bool, incompleteNote: string}');
push('     */');
push('    public static function classifyJathagamPlanetsForSummary($result, string $lang): array');
push('    {');
push('        $lang = in_array($lang, [\'en\', \'ta\', \'hi\'], true) ? $lang : \'en\';');
push('        $data = self::jathagamSummaryRemedyData();');
push('        $summaryText = self::jathagamSummaryText($lang);');
push('');
push('        // Classical dignity tables, value-for-value with src/lib/astrology/dignity.ts.');
push('        $signLords = ' + phpLiteral(SIGN_LORDS as unknown as Record<string, string>) + ';');
push('        $exaltationSign = ' + phpLiteral(EXALTATION_SIGN as unknown as Record<string, number>) + ';');
push('        $ownSigns = ' + phpLiteral(OWN_SIGNS as unknown as Record<string, number[]>) + ';');
push('        $signExaltedBy = ' + phpLiteral(SIGN_EXALTED_BY as unknown as Record<string, string>) + ';');
push('        $challengingHouses = [6, 8, 12];');
push('        $supportiveHouses = [1, 4, 5, 7, 9, 10, 11];');
push('        $lordSupportiveHouses = [1, 2, 4, 5, 7, 9, 10, 11];');
push('        $malefics = [\'mars\', \'saturn\', \'rahu\', \'ketu\'];');
push('        $nodeDebilitation = [\'rahu\' => 8, \'ketu\' => 2];');
push('        $conjunctionOrb = 10;');
push('        $supportiveLimit = 3;');
push('        $compactThreshold = 5;');
push('');
push('        $validRasi = static function ($value): bool {');
push('            return $value !== null && $value !== \'\' && is_numeric($value)');
push('                && (float) $value == (int) $value && (int) $value >= 1 && (int) $value <= 12;');
push('        };');
push('');
push('        $positions = [];');
push('        foreach ((array) ($result[\'planetPositions\'] ?? []) as $position) {');
push('            if (!is_array($position) || !isset($position[\'graha\'], $position[\'rasi\'])) continue;');
push('            $key = (string) $position[\'graha\'];');
push('            if (!isset($data[$key]) || !$validRasi($position[\'rasi\'])) continue;');
push('            $positions[] = $position;');
push('        }');
push('        $lagnaRasi = $validRasi($result[\'lagnaRasi\'] ?? null) ? (int) $result[\'lagnaRasi\'] : null;');
push('        $lagnaLord = $lagnaRasi === null ? null : ($signLords[$lagnaRasi] ?? null);');
push('');
push('        // Neecha Bhanga, as dignity.ts defines it: the graha exalted in the');
push('        // occupied sign, or the dispositor, conjunct the graha or in a kendra.');
push('        $neechaBhangaHolds = static function (string $graha, int $rasi) use ($lagnaRasi, $positions, $signExaltedBy, $signLords): bool {');
push('            if ($lagnaRasi === null) return false;');
push('            $rasiByGraha = [];');
push('            foreach ($positions as $p) { $rasiByGraha[(string) $p[\'graha\']] = (int) $p[\'rasi\']; }');
push('            $kendra = [1, 4, 7, 10];');
push('            $houseFrom = static function (int $target, int $reference): int {');
push('                return (($target - $reference + 12) % 12) + 1;');
push('            };');
push('            $exaltationGraha = $signExaltedBy[$rasi] ?? null;');
push('            if ($exaltationGraha !== null && isset($rasiByGraha[$exaltationGraha])) {');
push('                if ($exaltationGraha !== $graha && $rasiByGraha[$exaltationGraha] === $rasi) return true;');
push('                if (in_array($houseFrom($rasiByGraha[$exaltationGraha], $lagnaRasi), $kendra, true)) return true;');
push('            }');
push('            $dispositor = $signLords[$rasi] ?? null;');
push('            if ($dispositor !== null && $dispositor !== $graha && isset($rasiByGraha[$dispositor])) {');
push('                if (in_array($houseFrom($rasiByGraha[$dispositor], $lagnaRasi), $kendra, true)) return true;');
push('            }');
push('            return false;');
push('        };');
push('');
push('        $supportive = [];');
push('        $needsCare = [];');
push('        $orderIndex = array_flip(' + phpLiteral(NAVAGRAHA_ORDER) + ');');
push('');
push('        foreach (' + phpLiteral(NAVAGRAHA_ORDER) + ' as $key) {');
push('            $position = null;');
push('            foreach ($positions as $p) { if ((string) $p[\'graha\'] === $key) { $position = $p; break; } }');
push('            if ($position === null) continue;');
push('            $rasi = (int) $position[\'rasi\'];');
push('            $house = isset($position[\'bhavaNumber\']) && $validRasi($position[\'bhavaNumber\']) ? (int) $position[\'bhavaNumber\'] : null;');
push('');
push('            $classicalDebilitation = isset($exaltationSign[$key]) ? (($exaltationSign[$key] - 1 + 6) % 12) + 1 : null;');
push('            $nodeDebilitationSign = $nodeDebilitation[$key] ?? null;');
push('            $isDebilitated = $classicalDebilitation === $rasi || $nodeDebilitationSign === $rasi;');
push('            $isExalted = ($exaltationSign[$key] ?? null) === $rasi;');
push('            $isOwnSign = in_array($rasi, $ownSigns[$key] ?? [], true);');
push('            $isChallengingHouse = $house !== null && in_array($house, $challengingHouses, true);');
push('            $conjunctMalefic = false;');
push('            foreach ($positions as $other) {');
push('                $otherKey = (string) $other[\'graha\'];');
push('                if ($otherKey === $key || !in_array($otherKey, $malefics, true)) continue;');
push('                if ($house === null || !isset($other[\'bhavaNumber\']) || !$validRasi($other[\'bhavaNumber\'])) continue;');
push('                if ((int) $other[\'bhavaNumber\'] !== $house) continue;');
push('                $a = isset($position[\'degrees\']) && is_numeric($position[\'degrees\']) ? (float) $position[\'degrees\'] : null;');
push('                $b = isset($other[\'degrees\']) && is_numeric($other[\'degrees\']) ? (float) $other[\'degrees\'] : null;');
push('                if ($a === null || $b === null) { $conjunctMalefic = true; break; } // same house, no degrees: classical reading');
push('                $separation = abs($a - $b);');
push('                if (min($separation, 30 - $separation) <= $conjunctionOrb) { $conjunctMalefic = true; break; }');
push('            }');
push('            $isCombust = !empty($position[\'isCombust\']) && !$isExalted && !$isOwnSign;');
push('            $isSupportiveHouse = $house !== null && in_array($house, $supportiveHouses, true);');
push('            $isLagnaLord = $lagnaLord !== null && $lagnaLord === $key;');
push('            $lordInSupportiveHouse = $isLagnaLord && $house !== null && in_array($house, $lordSupportiveHouses, true);');
push('            $neechaBhangaApplies = ($isDebilitated && $classicalDebilitation !== null)');
push('                ? $neechaBhangaHolds($key, $rasi)');
push('                : false;');
push('');
push('            $careScore = 0;');
push('            if ($isDebilitated) { $careScore += $neechaBhangaApplies ? 1 : 2; }');
push('            if ($isCombust) { $careScore += 1; }');
push('            if ($isChallengingHouse) { $careScore += 1; }');
push('            if ($conjunctMalefic) { $careScore += 1; }');
push('            if ($isLagnaLord && $isChallengingHouse) { $careScore += 1; }');
push('');
push('            $supportScore = 0;');
push('            if ($isExalted) { $supportScore += 3; }');
push('            if ($isOwnSign) { $supportScore += 2; }');
push('            if ($lordInSupportiveHouse) { $supportScore += 2; }');
push('            if ($isSupportiveHouse) { $supportScore += 1; }');
push('');
push('            if ($careScore > 0) {');
push('                $worship = $data[$key][\'deity\'][$lang] . \' · \' . $data[$key][\'day\'][$lang];');
push('                $lamp = (string) ($data[$key][\'lamp\'][$lang] ?? \'\');');
push('                $donation = (string) ($data[$key][\'donation\'][$lang] ?? \'\');');
push('                $mantra = (string) ($data[$key][\'mantra\'][$lang] ?? \'\');');
push('                $compactParts = [explode(\' · \', $worship)[0], $data[$key][\'day\'][$lang], $lamp, $donation, $mantra];');
push('                $compactParts = array_values(array_filter($compactParts, static function ($part) { return trim((string) $part) !== \'\'; }));');
push('                $needsCare[] = [');
push('                    \'key\' => $key,');
push('                    \'house\' => $house,');
push('                    \'score\' => $careScore,');
push('                    \'difficulties\' => (string) ($data[$key][\'difficulties\'][$lang] ?? \'\'),');
push('                    \'worship\' => $worship,');
push('                    \'lamp\' => $lamp,');
push('                    \'donation\' => $donation,');
push('                    \'mantra\' => $mantra,');
push('                    \'compactLine\' => implode(\' · \', $compactParts)');
push('                ];');
push('                continue;');
push('            }');
push('');
push('            if ($supportScore > 0) {');
push('                $supportive[] = [\'key\' => $key, \'house\' => $house, \'score\' => $supportScore];');
push('            }');
push('        }');
push('');
push('        $assessedCount = 0;');
push('        foreach (' + phpLiteral(NAVAGRAHA_ORDER) + ' as $key) {');
push('            foreach ($positions as $p) { if ((string) $p[\'graha\'] === $key) { $assessedCount++; break; } }');
push('        }');
push('        $assessmentComplete = $assessedCount >= count(' + phpLiteral(NAVAGRAHA_ORDER) + ');');
push('');
push('        $sortScoreFirst = static function (array $a, array $b) use ($orderIndex): int {');
push('            return $b[\'score\'] - $a[\'score\'] ?: $orderIndex[$a[\'key\']] - $orderIndex[$b[\'key\']];');
push('        };');
push('        usort($needsCare, $sortScoreFirst);');
push('        usort($supportive, $sortScoreFirst);');
push('');
push('        $supportiveOut = [];');
push('        foreach (array_slice($supportive, 0, $supportiveLimit) as $entry) {');
push('            $supportiveOut[] = [');
push('                \'key\' => $entry[\'key\'],');
push('                \'house\' => $entry[\'house\'],');
push('                \'support\' => (string) ($data[$entry[\'key\']][\'support\'][$lang] ?? \'\')');
push('            ];');
push('        }');
push('        $needsCareOut = [];');
push('        foreach ($needsCare as $entry) {');
push('            $needsCareOut[] = [');
push('                \'key\' => $entry[\'key\'],');
push('                \'house\' => $entry[\'house\'],');
push('                \'difficulties\' => $entry[\'difficulties\'],');
push('                \'worship\' => $entry[\'worship\'],');
push('                \'lamp\' => $entry[\'lamp\'],');
push('                \'donation\' => $entry[\'donation\'],');
push('                \'mantra\' => $entry[\'mantra\'],');
push('                \'compactLine\' => $entry[\'compactLine\']');
push('            ];');
push('        }');
push('');
push('        return [');
push('            \'supportive\' => $supportiveOut,');
push('            \'needsCare\' => $needsCareOut,');
push('            \'compact\' => count($needsCareOut) >= $compactThreshold,');
push('            \'assessedCount\' => $assessedCount,');
push('            \'assessmentComplete\' => $assessmentComplete,');
push('            \'incompleteNote\' => $summaryText[\'text\'][\'assessmentIncomplete\']');
push('        ];');
push('    }');
push('');

process.stdout.write(lines.join('\n') + '\n');

/** Renders a JS object as a PHP array literal, keys quoted when needed. */
function phpLiteral(value: unknown): string {
  if (Array.isArray(value)) {
    return '[' + value.map(item => phpLiteral(item)).join(', ') + ']';
  }
  if (value && typeof value === 'object') {
    return '[' + Object.entries(value as Record<string, unknown>)
      .map(([key, item]) => `${/^-?\d+$/.test(key) ? key : q(key)} => ${phpLiteral(item)}`)
      .join(', ') + ']';
  }
  if (typeof value === 'number') return String(value);
  return q(String(value));
}
