/**
 * Freezes the Birth Jathagam page-3 contract for both stacks.
 *
 *   npx tsx scripts/emit-jathagam-summary-parity.ts
 *
 * writes tests/fixtures/jathagam-summary-parity.json: for every chart below and
 * every report language it stores the chart input the rule reads plus the lists
 * the Short Summary must print. The Node suite
 * (tests/jathagam-summary-parity.test.ts) and the PHP suite
 * (tests/jathagam-summary-parity.test.php) each classify the same input with
 * their own engine and must reproduce the frozen lists, so "Node and PHP agree
 * on the planet lists for the same chart" is enforced by the build, not by eye.
 *
 * Re-run this script only when the rule itself changes on purpose.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { calculatePrecisionHoroscope } from '../server/astrology/astronomy';
import { classifyJathagamPlanetsForSummary, SummaryChartInput } from '../src/services/jathagamPlanetSummary';
import { DoshaLanguage } from '../src/services/jathagamDoshaData';

const LANGUAGES: DoshaLanguage[] = ['en', 'ta', 'hi'];

const priya = calculatePrecisionHoroscope(
  'Priya Devi', '1998-06-15', '06:30', 'Chennai, Tamil Nadu, India', 13.0827, 80.2707, 5.5, 'India', 'F'
);
const longName = calculatePrecisionHoroscope(
  'Lakshminarayanan Subramanian Venkatesan Ramanathan Chidambaranathan',
  '1979-11-23', '04:15', 'Thiruvananthapuram, Kerala State, India (Thampanoor Junction)',
  8.5241, 76.9366, 5.5, 'India', 'M'
);
const karthik = calculatePrecisionHoroscope(
  'Karthik Raman', '2000-01-01', '02:00', 'Chennai, Tamil Nadu, India', 13.0827, 80.2707, 5.5, 'India', 'M'
);
const suva = calculatePrecisionHoroscope(
  'Reminder Test', '2000-01-01', '12:00', 'Suva', -18.1416, 178.4419, 12, 'Fiji', 'M'
);

const charts: Array<[string, SummaryChartInput]> = [
  ['normal-priya', priya],
  ['long-name', longName],
  ['all-nine-needing-care', { ...priya, planetPositions: priya.planetPositions.map(p => ({ ...p, bhavaNumber: 12 })) }],
  ['karthik-2000', karthik],
  ['suva-2000', suva]
];

/** Only the fields the rule reads, so the fixture stays readable. */
const chartInput = (chart: SummaryChartInput) => ({
  lagnaRasi: chart.lagnaRasi ?? null,
  planetPositions: (chart.planetPositions ?? []).map(p => ({
    graha: p.graha,
    rasi: p.rasi ?? null,
    degrees: p.degrees ?? null,
    bhavaNumber: p.bhavaNumber ?? null,
    isCombust: Boolean(p.isCombust)
  }))
});

const cases = [] as Array<Record<string, unknown>>;
for (const [id, chart] of charts) {
  const input = chartInput(chart);
  for (const lang of LANGUAGES) {
    cases.push({ id: `${id}|${lang}`, chart: id, lang, input, expected: classifyJathagamPlanetsForSummary(input, lang) });
  }
}

const target = resolve(import.meta.dirname, '..', 'tests', 'fixtures', 'jathagam-summary-parity.json');
mkdirSync(dirname(target), { recursive: true });
writeFileSync(
  target,
  JSON.stringify(
    {
      note: 'Generated by scripts/emit-jathagam-summary-parity.ts. Both engines must reproduce these lists.',
      rule: 'src/services/jathagamPlanetSummary.ts == AstroReportViews::classifyJathagamPlanetsForSummary()',
      cases
    },
    null,
    1
  ) + '\n'
);
console.log(`wrote ${cases.length} cases to ${target}`);
